floating-ui/floating-ui

_includes/example3-code.html

**Description**
The extra `the` word makes the text a bit strange (and harder to read too if you're not an advanced or native English speaker), thus, removing it will help the general understanding of the this piece of text/example
**Changes**
- Removal of extra `the` word from copy

Remove extra word from example 3 copy

---

src/popper.js
tests/test-popper.js

This pull requests fixes popper.js code in order to correctly calculate outerSize of popper element and its arrows, event if they are set as `display: none`. This will fix the issue #46 .
This codepen is using the new popper.js script and doesnt have the re-positioning bug:
http://codepen.io/rafaelverger/pen/WwPNEd

Fix calculation of popper elements' outerSizes

---

Gruntfile.js
README.md
bower.json
package.json
src/popper.js
tests/test-popper.js

This PR allows 3rd party modifiers to hook inside the `applyStyles` modifier.
Thanks to this edit, your custom modifier can now apply custom styling to the popper element defining the CSS properties inside `data.styles`.
Example:
```js
function hidePopperModifier(data) {
data.styles.display = 'none';
return data;
}
```
This should help with #52

added ability to set custom styles

---

src/popper.js
tests/test-popper.js

This fixes #56.
Similar to how the parent's position is checked, I added a check for any transformations on the parent. If transforms are present, Popper changes the way it calculates offsets. This is necessary because when a parent has a transform applied, the origin of the transform switches to that element instead of the viewport. See the [W3C Spec](http://www.w3.org/TR/css3-2d-transforms/#transform-rendering):
> In the HTML namespace, any value other than none for the transform results in the creation of both a stacking context and a containing block. The object acts as a containing block for fixed positioned descendants.
Since I added the check for `isParentTransformed`, any existing Popper should (in theory) work the same way. I tried to mimic the existing code flow/style as much as …

Added support for a reference el that is both fixed and transformed.

---

src/utils/getStyleComputedProperty.js

When a popper's reference element is inside shadowRoot, popper fails.
Codepen:
https://codepen.io/nadiam84/pen/yJQvkB
It happens inside getScrollParent function, when it tries to  up the tree here: `getScrollParent(element.parentNode)`. At some point parentNode of an element inside shadowRoot is going to be shadowRoot itself, and apparently you can't do `getComputedStyle` on it. This PR is fixing this problem.
All tests were green locally btw

fixes issue with shadowRoot and computed styles

---

src/utils/getParentNode.js
src/utils/getScrollParent.js
src/utils/isFixed.js
src/utils/isTransformed.js

When one of those functions (isFixed, isTransformed, getScrollParent) is trying to get the parent of the element it also should check for the `host` element. Because if the element is inside the shadowRoot it woudn't step outside of it just using `parentNode`, since the shadowRoot doesn't have any parents.

Fix parent node

---

src/popper/index.js
tests/functional/lifecycle.js

Added what we talked about in https://github.com/FezVrasta/popper.js/issues/117

Add enable/disable method

---

src/popper/utils/getOuterSizes.js

Removing these lines, our updates takes 0.33ms instead of 1ms, it's a huge improvement!
@rafaelverger may you please test this PR and let me know what happens?
You initially inserted these lines in https://github.com/FezVrasta/popper.js/commit/660849a3e6d73d0b6d502b2db0ed1d6cd330be9d but I'm not sure they are needed anymore since removing them the tests are passing.
You have more context than me about these changes so I would like to get feedbacks from you before merging.

get rid of DOM manipulations that cause reflows

---

scripts/karma.conf.js

Most likely we'll want to change the files structure or move Tooltip.js to its own repository in the future.

make karma (and rollup) ignore the tooltip dist files

---

src/popper/utils/getOffsetRectRelativeToCustomParent.js
tests/functional/core.js

fix popper's behavior when it doesn't have any parents (#136)

---

docs/_includes/popper-documentation.md
docs/_includes/tooltip-documentation.md
src/popper/index.js
src/tooltip/index.js

The position for "bottom-end" was wrong in the documentation, it said "bottom-right". I fixed those typos.
Sorry for the 4 commits, I did the edits on github, you should squash them when you merge it :)

Fixing position documentation

---

.babelrc
scripts/karma.conf.js

This should fix problems with webpack. ping @Spone
To test this out you have to clone the repository, run `yarn build:tooltip` (or `npm run build:tooltip`) and copy the `dist/tooltip*` to `node_modules/tooltip.js/dist`.
Please let me know if this fixes the problem once for all.

define popper alias only during tests (fix #144)

---

src/popper/utils/debounce.js

Currently the [util/debounce.js](https://github.com/FezVrasta/popper.js/blob/master/src/popper/utils/debounce.js) file is accessing `navigator` and `window` objects at the time of import. This causes universal applications that involve any server side rendering/static generation to fail on importing Popper.js. 
I understand this is a client side library, and I'm not entirely sure where the responsibility should be placed to gracefully handle this, but conditional imports are nasty, and I don't think attaching mock objects to `global` should be the way to go. 
_If_ you're ok with this fix, as for testing the _"universalness"_ in the future, I don't know much about Karma (I'm a mocha man) but a very quick search and I can't see a way to emulate a non-browser env?

[fix]: Importing into universal apps

---

docs/css/main.scss

As someone who frequently visits the documentation, I would like to reduce the path to navigation by one click. What do you think?
On smaller devices it looks the same as before.

Make navigation immediately visible on desktop

---

.gitignore
.npmignore
package.json
scripts/bundle.js
scripts/rollup.config.js
src/tooltip/.npmignore
src/tooltip/package.json

Fix for #219
Now the `dist` folder has in the top directory, the ESM + ES6 code.
In the `dist/esm` folder there's the ESM + ES5 code.
In `dist/umd` there's the UMD + ES5 code.
`main` is `dist/umd/popper.js` and `module` is `dist/esm/popper.js`
```
▶ ls -R dist
esm/
umd/
popper.js
popper.js.map
popper.min.js
popper.min.js.map
tooltip.js
tooltip.js.map
tooltip.min.js
tooltip.min.js.map
popper-utils.js
popper-utils.js.map
popper-utils.min.js
popper-utils.min.js.map
dist/esm:
popper.js
popper.js.map
popper.min.js
popper.min.js.map
tooltip.js
tooltip.js.map
tooltip.min.js
tooltip.min.js.map
popper-utils.js
popper-utils.js.map
popper-utils.min.js
popper-utils.min.js.map
dist/umd:
popper.js
popper.js.map
popper.min.js
popper.min.js.map
tooltip.js
tooltip.js.map
tooltip.min.js
tooltip.min.js.map …
```

fix: Transpile to ES5 the `module` bundle

---

package.json
src/popper/modifiers/offset.js
tests/functional/offset.js

Previously there was a bug that prevented to use a negative offset value, e.g. `-50%`.

[fix] Allow negative %/vh/vw offsets

---

package.json
src/popper/index.js
src/popper/modifiers/applyStyle.js
src/popper/utils/computeAutoPlacement.js
tests/functional/core.js

fixes #231
@imkremen may you check this out? It's enough to use this URL:
https://rawgit.com/FezVrasta/8c9b742ced8e78e45fbbc1166f366430/raw/60902150babc6dcca2541e571a4c8b48ac219d63/popper-1.8.4.js

[fix] Make `auto` placement use `flip.boundariesElement`

---

README.md
src/popper/modifiers/index.js
src/popper/utils/runModifiers.js
tests/functional/core.js

It was an unfortunate choice to use `function` as property for the modifiers, since `function` is a reserved word 😓
Now it's called `fn`.
To keep backward compatibility, the old `function` property is still supported but will throw a warning.
Still for backward compatibility, `function` will take precedence over `fn` in case both the properties are defined, to avoid to break instances where a built-in modifier had its `function` property replaced.
I'll keep the PR here for few days to collect feedbacks and see if someone notices some hidden breaking change.

[update] Renamed modifier.function to modifier.fn

---

docs/_includes/popper-documentation.md
src/popper/index.js

This removes the expectation of popper that `window` is defined at import time (which is incorrect for any non-browser environment).
fixes #241

fix: expectation of `window` being defined at import time

---

src/popper/utils/findCommonOffsetParent.js
tests/functional/core.js
tests/utils/appendNewRef.js

Fixes #233 
If the test coverage isn't quite there, happy to add additional tests if pointed in the right direction. I'm not quite sure where the tests for this change are/should be

support poppers that are children of their reference

---

docs/_includes/popper-documentation.md
package.json
src/popper/modifiers/index.js
src/popper/modifiers/offset.js
tests/functional/offset.js
tests/unit/parseOffset.js

fix #228, pinging @shmax for review.
New documentation:
> The `offset` modifier can shift your popper on both its axis.
> 
> It accepts the following units:
>  - `px` or unitless, interpreted as pixels
>  - `%` or `%r`, percentage relative to the length of the reference element
>  - `%p`, percentage relative to the length of the popper element
>  - `vw`, CSS viewport width unit
> - `vh`, CSS viewport height unit
> 
>  For length is intended the main axis relative to the placement of the popper.
>  This means that if the placement is `top` or `bottom`, the length will be the
>  `width`. In case of `left` or `right`, it will be the height.
> 
>  You can provide a single value (as `Number` or `String`), or a pair of values
>  as `String` divided by a comma or one (or more) white spaces.
> …

[feature] Allow math operations in offset modifier

---

docs/_includes/popper-documentation.md
src/popper/modifiers/index.js

- the reference to `data.offsets.arro` should mean `data.offsets.arrow`
PR conditions:
1. Tests are passing;
2. No additional tests needed as this PR addresses documentation;

fix dataObject documentation typo

---

package.json
src/popper/modifiers/preventOverflow.js
src/popper/utils/getOffsetRectRelativeToArbitraryNode.js
tests/functional/core.js

So, I had to perform a kinda-major change in the way `preventOverflow` works to fix this problem.
Look like the test that checks the functionality of poppers when relative to their own reference element never worked and it completely blown up when I fixed #310 
Now, `preventOverflow` used `offsetParent` as boundaries element when the popper was child of a relative reference. This leaded to a weird behavior, because `preventOverflow` tried to avoid the popper from overflowing from the `reference` element.
If this is the correct behavior if we think about the strict requirements of `preventOverflow`, isn't a desirable behavior in any circumstance I can think of.
To avoid this problem when the popper has as boundariesElement its own reference element, I'm going to change the meaning of …

[fix] Fixed #310

---

.github/PULL_REQUEST_TEMPLATE.md
packages/popper/.npmignore
packages/popper/index.d.ts
packages/popper/package.json

- add `index.d.ts` to popper package (and `types` entry in package.json)
- add a note in PULL_REQUEST_TEMPLATE to remind folks to keep this updated

add typescript definitions

---

packages/popper/src/utils/getSupportedPropertyName.js

Vendor-prefixed names are case sensitive in JavaScript. They should be:
* `ms`
* `Moz`
* `O`
* `Webkit`
Technically `webkit` is also acceptable, but I'm using the capitalized version here because if this is used in a React component, React expects it to be capitalized (and beyond that I'm not aware of the benefits of using one over the other).
Fixes #355

Use correct casing for JavaScript vendor-prefixes

---

packages/popper/package.json
packages/popper/src/utils/getOffsetParent.js
packages/popper/src/utils/isOffsetContainer.js
packages/popper/tests/functional/core.js

I'm a bit concerned about performance problems...
These should/could kick in only when the returned `offsetParent` is a `TD` or a `TABLE`, but still..

[fix] Fixed #276

---

packages/popper/index.d.ts

Fixes issues introduced by included type definitions conflicting with `@types` definitions.
Also includes improved modifier definitions, as well as exposing the `options` property on the `Popper` class.

feat(popper): Improved type definitions

---

packages/popper/src/utils/getWindowSizes.js
packages/popper/tests/functional/core.js

This should fix #302, I'm not sure if this may introduce unwanted regressions, the whole test suite seem to pass just fine.
I'd love some feedback from all the interested people that reported the bug in #302.
cc @Johann-S because this should affect (possibly positively) Bootstrap v4.

fix(popper): Fixed #302

---

packages/popper/src/utils/getBoundaries.js
packages/popper/src/utils/getWindowSizes.js

This should fix #401 and don't break #302.
Please @atomiks may you verify that both the tickets are properly fixed please?

fix(popper): Fixed regression #401

---

package.json
packages/popper/src/utils/getScrollParent.js
packages/popper/src/utils/setupEventListeners.js

This PR fixes an issue related to cases where references are contained within iframes, e.g.:
```html
<div class="popper">...</div>
<iframe src="..."></iframe>
```
```js
const popper = document.querySelector('.popper')
const iframe = document.querySelector('iframe')
const reference = iframe.contentDocument.querySelector('.reference')
new Popper(reference, popper, { ... })
```
The `getScrollParent()` and `setupEventListeners()` utilities will now correctly return the `body` and `window` references, respectively, of the associated iframe rather than the host frame.

Support references within iframes

---

packages/popper/src/utils/runModifiers.js

fix #437 by not using the reserved keyword function as property

---

packages/popper/src/utils/getBoundaries.js
packages/popper/src/utils/getOffsetParent.js
packages/popper/src/utils/getScroll.js
packages/popper/src/utils/getViewportOffsetRectRelativeToArtbitraryNode.js
packages/popper/src/utils/getWindow.js
packages/popper/src/utils/removeEventListeners.js
packages/popper/src/utils/setupEventListeners.js

This is a continuation of #415 that ensures that both poppers and reference elements rely on `ownerDocument` references whenever needed in order to support poppers and reference elements residing within iframes. Upon further testing I encountered some cases that #415 did not address that this PR does.

Rely on `ownerDocument` references for both poppers and reference elements

---

packages/popper/src/utils/debounce.js

I came along this issue where certain server side renderers have window defined but no document.
This will add an additional check if `window.document` is not undefined.

Don't rely only on a defined window to determine if we have a DOM

---

packages/tooltip/src/index.js

If popper.options.removeOnDestroy is set, then calling tooltip.dispose() will throw an error `removeClild() of undefined` because it is being called in tooltip.js and in popper.js. This pull request resolves this conflict.

Resolve conflict in tooltip.dispose()

---

packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

When you call dispose() on a tip that hasn't been shown at least once, it
leaves behind some events that will still render the tip.
See issue #466

Fix bug with `dispose()`

---

packages/popper/src/utils/getBoundaries.js
packages/popper/tests/functional/core.js

Fix for https://github.com/FezVrasta/popper.js/issues/453

fix detecting scrollParent: use reference as source, not popper. Fixes #453

---

packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

This may introduce a possibly unwanted behavior tho.
If you have a tooltip that can be triggered both by `hover` and `click`, and you hover and then click on the reference before the tooltip has been shown, the tooltip will not get shown.
This because the first event (hover) triggers the "scheduleShow", but the second event (click) triggers the "scheduleHide".
I can't think of ways to avoid the #399 bug without introducing this behavior.

fix(tooltip): fixed #399

---

README.md

This is an attempt to improve user experience for people who are not fans of JS package managers and browser-ifier transpilers.
* Added link to minified JS file — to make it more accessible to people who would rather just use a ready link to a CDN instead of investing in the npm/yarn/bower/nuget/package-manager-du-jour ecosystem.
* Emphasise need to use UMD — so it stands out to help people get stuff done if they happen to use said package manager, but don’t use webpack.

Add link to minified JS file on unpkg and emphasise need to use UMD

---

packages/popper/src/utils/getScrollParent.js

Had some problems with the popups not following the scroll. Turns out we are using `overflow: overlay `. And after some digging, it seems that it is forgotten in this repo. 
(Overlay is the property of overflow that makes the scrollbar not affect the size of the element)

Find parents with CSS property overflow: overlay;

---

packages/popper/src/methods/destroy.js
packages/popper/tests/functional/lifecycle.js

Should I write a test for every possible style modification or the popper element?

fix: Add missing will-change cleanup for the Destroy method (#542)

---

.codeclimate.yml
docs/_includes/tooltip-documentation.md
packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

Tests updated, but not sure if the typescript definition should be as well, since this is a tooltip exclusive change. ❓Please let me know  
I'm reusing some code to insert the new String|HTMLElement
DEMO:

feat(tooltip): Added function to update the tooltip's content

---

packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

Updating the title via `updateTitleContent` may cause the tooltip to be misaligned.
Triggering an update to the underlying popper instance will reposition the tooltip, fixing the issue.

Trigger a popper update when changing tooltip title

---

packages/popper/src/utils/getSupportedPropertyName.js

Fixes https://github.com/FezVrasta/popper.js/issues/568
- Fix the statement 2 of the loop to run through all autoprefixers.

Fix the statement 2 of the loop to run through all autoprefixer

---

docs/index.html

I had just noticed that "need" was misspelled; this just fixes that.

Fixes typo in documentation ("neeed" to "need")

---

packages/popper/index.d.ts

I extracted the _behaviors_ in their own type.
So they can be used by other libraries, especially Bootstrap v4 TypeScript definition.
@giladgray
Edit: Travis CI fail is not related to this...

TypeScript definitions: extract Behavior type

---

packages/popper/index.d.ts
packages/popper/tests/types/type-tests.ts

Fixes the breaking change in https://github.com/FezVrasta/popper.js/pull/539#issuecomment-372728264

Fix regression in Popper namespace typings

---

packages/popper/src/modifiers/computeStyle.js

As mentioned in #551, this will allow for "pixel-perfect" positioning if desired, since subpixel `top/left` positioning doesn't cause blurriness unlike `translate3d`.

Fix rounding

---

packages/popper/src/methods/update.js

#251 has been left open too long I think, and this is the solution that @kybishop suggested, and the one I use personally, but it should be placed in `update()` so it works for resizing too.
Yes, it accesses the DOM and will reduce performance, but I don't think there's another way.  Please test the performance difference before/after to see.
`Object.assign()` is being used, which I believe is already being ponyfilled in the lib.

fix #251 (finally)

---

README.md

This PR adds a section entitled, “**How to use Popper.js in Jest**”, to the readme as discussed in https://github.com/FezVrasta/popper.js/issues/478
I included the section on manual mocking too, as I thought it was useful as well.  I can remove it if you'd prefer not to include it.  Otherwise feel free to edit as you see fit.

Add “How to use Popper.js in Jest” to readme

---

docs/_includes/popper-documentation.md
packages/popper/src/index.js
packages/popper/src/methods/defaults.js
packages/popper/src/methods/destroy.js
packages/popper/src/methods/disableEventListeners.js
packages/popper/src/modifiers/arrow.js
packages/popper/src/modifiers/index.js

Hi!
Thanks for making this awesome library. 🎉 I noticed that there were a few typos and grammatical errors in the Popper docs. Also, I noticed that the docs are generated from the JSDocs. For now, I've edited the `.md` file directly in order to get your feedback. Once you're OK with the changes, I'll change the source files.
Things I've done:
1. Corrected typos
1. Highlighted some strings as `code` as they're referring to actual code
1. Split some sentences into two to make them grammatically correct
1. Normalized the placement of `.`s in the docs
1. No `.`s in the doc tables
1.  `.`s at the end of API descriptions

Fix some typos and grammar.

---

packages/popper/src/utils/getBoundaries.js
packages/popper/src/utils/getBoundingClientRect.js
packages/popper/src/utils/getOffsetRect.js
packages/popper/src/utils/getWindowSizes.js

After some digging I found that when `getWindowSizes` is called it looks at the parent document which get incorrect values when using this inside of an iframe.
I created a test case here: https://codesandbox.io/s/8n31m5132j
First one is in an iframe and always puts it at the bottom even though it doesn't have enough room.
The second one shows the same thing but not wrapped in a iframe. This correctly moved the popper to the top of the element and upon scrolling moves it to the bottom.

feat: Get elements ownerDocument for correct measurements

---

packages/popper/index.js.flow
packages/popper/package.json
packages/tooltip/tests/functional/tooltip.js

This PR adds Flow type annotations to Popper.js 🍾

feat: Add Flow types to Popper.js

---

packages/popper/src/utils/getBoundaries.js
packages/popper/src/utils/getWindowSizes.js
packages/popper/tests/unit/getBoundaries.js
packages/popper/tests/unit/getBoundaries.padding.js

There were no tests for this class already, but all existing tests still pass.

feat: Add specific padding to boundaries (#518)

---

docs/_includes/popper-documentation.md
packages/popper/src/methods/placements.js

`auto-right` isn't a valid placement.

Fix erroneous docs on `placement`

---

docs/index.html

Fix typo on docs ("gzpipped" -> "gzipped")

---

packages/popper/.npmignore

I believe that flow typings should be published alongside typescript typings :)

Unignore flow typings from npm publish

---

packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

Visibility can be animated, but display cannot. Because the tooltips already have `position: absolute` added, ultimately, this has no bearing on the way these tooltips work other than the fact that they can be animated more easily than display. For example, the below makes the tooltip fade in and out:
```css
@keyframes fade-in {
0% { opacity: 0; }
100% { opacity: 1; }
}
.tooltip {
animation: fade-in 100ms ease-in;
}
.tooltip[aria-hidden="true"] {
transition: opacity 100ms ease-in, visibility 100s linear;
opacity: 0;
}
.tooltip[aria-hidden="false"] {
transition: opacity 100ms ease-in, visibility 0s linear;
opacity: 1;
}
```
whereas using `display` prevents the `opacity` transition from happening, and the tooltip appears and disappears immediately after the first fade-in animation. …

feat: use visibility instead of display for tooltip

---

docs/_includes/tooltip-documentation.md
packages/tooltip/index.d.ts
packages/tooltip/src/index.js
packages/tooltip/tests/types/type-tests.ts

* Remove all `PlacementFunction`

fix #654 options.placement only accepts string

---

packages/tooltip/index.d.ts

Updated outdated typings of tooltip.js (see #643)
Can you release again to use the new features with proper typings?

fix: update tooltip typings

---

packages/popper/src/utils/getOffsetParent.js
packages/popper/tests/functional/core.js

Some element (eg. svg) does not have `.offsetParent` so we can try the
nextElementSibling of it
Closes #653

fix #653 Skip elements that does not have `.offsetParent` correctly

---

packages/popper/src/utils/getOffsetParent.js
packages/popper/tests/functional/core.js

#363 fixed the positioning issue for td elements, but the problem still existed for th elements.
This PR adds a fix for th elements as well.

fix: add support for th elements (#276)

---

packages/popper/src/utils/getOuterSizes.js
packages/popper/src/utils/getStyleComputedProperty.js

I work on an embedded JavaScript app. We inject an iframe into the page that we're embedded on and the JavaScript is inserted and run in the context of that iframe so we can run in isolation from the parent page. 
This works well, [but there's an issue in Firefox, specifically with `getComputedStyle()`](https://bugzilla.mozilla.org/show_bug.cgi?id=548397), where, if you try to run this method in the context of an iframe, it always returns `null`. 
I'm looking to introduce Popper into my embedded app, but because of the bug above, Popper can't position my elements because `getComputedStyle` returns `null`. Unfortunately, this issue has been open for almost a decade and is unlikely to be fixed any time soon.
Because the elements themselves live on the parent page, we can work around this by …

Run getComputedStyle in the same context as the target element

---

yarn.lock

[Yarn 1.10](https://github.com/yarnpkg/yarn/releases/tag/v1.10.0) added integrity SHAs to the lock file. Adding them to the lock file here so people working with Yarn 1.10+ don't get an updated lock file each time they run yarn.

Add integrity sha to yarn lockfile

---

MENTIONS.md

Updates `MENTIONS.md` to include ember-tooltips, which uses `Popper.js` in the recently-released version `3.0.0` of ember-tooltips.

Add ember-tooltips to Popper.js mentions

---

packages/popper/src/utils/getOuterSizes.js
packages/popper/tests/unit/getOuterSizes.js

When the element is not attach at the DOM the `getComputedStyle` returns
a empty string making the convertion to float `parseFloat(styles.marginTop)`
return NaN.

fix: getOuterSizes returning NaN for virtual elements

---

packages/popper/src/utils/getRoundedOffsets.js

We forgot to round the element widths before checking their width parity (since elements' widths are usually not always integers)
https://codepen.io/anon/pen/aQVVwO

Additional rounding patch: round element widths before checking width parity

---

packages/popper/src/utils/isFixed.js
packages/popper/tests/unit/isFixed.js

Hi there,
We use popper.js with Vue.js, and we noticed that it generates a lot of errors noise when a DOM element gets detached and the `preventOverflow` is called: `isFixed` tries to go up the DOM tree and tries to resolve a `nodeName` of an undefined parent.
So here is a fix for the isFixed util to avoid crashing on detached DOM elements (this works perfectly with this patch).
Thanks!

fix: isFixed with detached DOM element

---

packages/popper/index.d.ts
packages/popper/index.js.flow

Added types of padding, that are missing since #615 PR.

Fix TS: padding types of `flip` and `preventOverflow` #518

---

packages/popper/index.d.ts
packages/popper/index.js.flow
packages/popper/src/modifiers/flip.js
packages/popper/src/modifiers/index.js
packages/popper/tests/functional/flips.js

Should close #512 
Basically, `flipVariations` switches the variation if **reference element** overflows boundaries (good when reference element is larger than popper)
This PR adds `flipVariationsByContent`, which switches the variation if **popper itself** overflows boundaries (good when popper content is larger than the reference element, usually a button or input)

Add 'flipVariationsByContent' option to flip modifier

---

packages/popper/package.json
packages/tooltip/package.json

On the Tippy.js website under [CDN](https://atomiks.github.io/tippyjs/getting-started/#option-1-cdn), it would be nice to have consistent formats

Add "unpkg" field to package.json to link to minified version

---

packages/popper/index.d.ts
packages/popper/index.js.flow
packages/popper/src/index.js

Reference: https://github.com/FezVrasta/popper.js/blob/bd1faa9a27499433443bb4c42b3dea9ecf055777/packages/popper/src/index.js#L37-L38

Fix(types): add missing `reference` and `popper` class properties

---

packages/popper/src/utils/isBrowser.js

Some implementations of server-side rendering support `window` and `document` objects but `navigator` could be undefined. To prevent error-prone behavior we should check the existence of `navigator` object in global scope.

Update isBrowser.js - check if navigator is available

---

packages/popper/.npmignore

Popper publishes source maps to NPM (great!) but it doesn't publish the `/src` folder that the sourcemaps point to. This makes it harder to debug into & set breakpoints in popper code from Chrome or an IDE like VSCode.  This PR updates .npmignore to ensure that the `/src` folder is also (along with `/dist`) published to NPM.
This shouldn't change anything about Popper's runtime user-facing behavior and the tests probably operate on the source (not a package downloaded from NPM), so I wasn't sure how to build a test to validate these changes. Let me know if you think that new tests are needed. 
Fixes #785.

Remove /src from .npmignore (for debugging)

---

packages/tooltip/src/index.js
packages/tooltip/tests/functional/tooltip.js

Tooltip.js allows the title to be provided via:
1) string
2) dom node
3) function
If a dom node is provided, it is accepted so long as the `allow html` option is enabled. However, currently, the function can only return a string. I think the function should also be allowed to return a dom node / frag, so long as the `allow html` flag is enabled.
It would be consistent, and useful, so I made a patch.

allow TitleFunction to return a DomNode or DocumentFragment 

---

packages/popper/src/utils/getBoundingClientRect.js

I would add a test for this but it seems like this function doesn't already have tests (or at least I was unable to find them). Please advise if they are in fact just hiding somewhere.
Resolves #789.

Fixed calculation that results in NaN

---

packages/popper/index.d.ts

TypeScript definitions only declared `Padding` as available via a namespace, rather than ESM style exports. This is a one-liner to fix that.

fix: ESM style export of Padding in TS typedefs

---

packages/popper/index.d.ts
packages/popper/index.js.flow
packages/popper/src/utils/getBoundaries.js
packages/popper/src/utils/getReferenceNode.js
packages/popper/src/utils/getReferenceOffsets.js
packages/popper/tests/functional/core.js

Fix for #800 
Basically popper.js was assuming popper's were always in global (client) coordinates when a reference object was provided instead of a reference element. ~~We now detect reference object usage and calculate coordinates relative to the popper's parent node.~~
There is now an additional property, `referenceNode`, which can be provided on a "reference object". popper.js will now position relative to this node when the property is specified.

feat: referenceNode support for reference objects (closes #800)

---

packages/popper/package.json
packages/popper/src/utils/debounce.js
packages/tooltip/package.json

This sets the package.json field sideEffects to false. This allows for better tree shaking by downstream consumers, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free for more information.
I skimmed over all included files and I did not see anything that would count following webpack's definition of tree shaking other than the line in `debounce.js` I fixed.

Declared packages side effect free and fixed existing side effects

---

packages/popper/index.js.flow
packages/popper/package.json

Hi,
in the current state of affairs, the `umd/popper.js.flow` definitions shipped alongside the `umd/popper.js` (package main entry) just doesn't work. It all resolves to `any`.
That's why you have to do [this sort of thing](https://github.com/FezVrasta/react-popper/blob/fa1b2956255666244ae102ae62f97d521f42a0a7/.flowconfig#L9) which should not be necessary. 
Causes:
1. There's a typo in the file name :) (this PR fixes it)
2. `.js.flow` declaration files have a different behaviour and syntax than "library definitions".
- They need a `// @flow` pragma
- They can't use the `declare modules` wrapper
- Types needs to be exported `export type ...`
So I managed to make this file work locally by applying all the points above, but I'm not sure how would you like to integrate it in the build …

Fix `.js.flow` definitions

---

package.json
rollup.config.js
src/index.js

You already had `process.env.NODE_ENV` check, but I had to refactor it so it'll work for consumers (and replaced with easy `__DEV__` variable). 
I also added `"sideEffects": false` as I'm not sure if DCE for these branches works without it (it needed to be added anyway).
Resolves #841

feat: implement DEV-only messages

---

package.json
rollup.config.js
yarn.lock

1. We need to use Babel's dev expression plugin because of the `"module"` field being generated by Babel
2. Enables loose mode for the spread polyfill

fix: use babel dev expression plugin and enable loose mode

---

README.md
rollup.config.js

I also renamed `popper-minimal` to `popper-base` because I kept getting "minimal" confused with "lite". IMO this is much less confusing naming.
I kind of want to add little picture examples at the top of what Popper solves in the introduction as well

docs: add usage for different formats

---

src/modifiers/computeStyles.js

Let's discuss techniques here before merging
We could:
1. Force `top/left` for  <`@2x` DPI displays (current PR)
2. Round offsets but keep `gpuAcceleration`, however sometimes this still causes blurry text (seen in several issues) due to the accelerated layer or whatever, and can cause 0.5px rounding errors for centered poppers

fix: blurry text

---

src/index.js
src/utils/debounce.js
src/utils/debounce.test.js

In v1 we had the `onUpdate` and `onCreate` callbacks. I previously used this to read the state so that I can update my tooltip (which is rendered in react).
Given that now we no longer have these callbacks, we should be able to do `tooltip.update().then(lastRenderedState => ...)`.
However, the debounce function was swallowing the last resolved value of the debounced function. So let's fix this, simplifying the implemementation of debounce.

fix(debounce): simplify debounce to always return the last resolved value

---

src/index.js
src/modifiers/applyStyles.js
src/modifiers/arrow.js
src/modifiers/computeStyles.js
src/modifiers/detectOverflow.js
src/modifiers/flip.js
src/modifiers/offset.js
src/modifiers/popperOffsets.js
src/modifiers/preventOverflow.js
src/types.js

Changes the modifiers signature to accept an object rather than multiple arguments.
This should make it easier to extend the API if needed.

feat: change modifiers signature

---

src/dom-utils/getDocumentRect.js
src/dom-utils/getViewportRect.js
src/enums.js
src/modifiers/detectOverflow.js
src/modifiers/flip.js
src/modifiers/preventOverflow.js

This fixes bug 8. in #617 
I'm not sure how `flip` could use "clippingParent" or if it even should? Also in v1, you could specify your own boundary for flip but now it's forced to use viewport. Does it even make sense to use anything else - is there a case where it's not suitable?
I'm not good with the functional test thingies if you could add that would be good 🙏

fix: flip should use viewport rect

---

src/index.js
src/modifiers/eventListeners.js
src/modifiers/index.js
src/popper-lite.js
src/types.js

With this we lose the `instance.enableEventListeners` method.
We have 3 options:
1. add it back (kinda hack-ish)
2. tell users to destroy + create when they need different options
3. create a global method to update an instance options
3 is something some people asked in the past, but considered how lightweight the popper instantiation is, I don't know if it's worth it.
(with this PR, popper-base goes below the 2kB (1.92 kB))

feat: move event listeners to modifier

---

src/modifiers/arrow.js

After a nightmarish bug hunt I found out why the arrow randomly broke after a build commit change - it was being placed before `preventOverflow`, but it relies on `preventOverflow`'s mutations to `popperOffsets` to work.
However, this uncovered a separate bug: `preventOverflow` relies on `state.elements.arrow` for its `edges` tether option, but it doesn't exist until after load. So the first load will have the arrow overflow the ref bounds if the popper is coincidentally placed in a location where that will happen, since it's being placed before `arrow`.
I'm not sure if it's possible to allow `arrow` to run before `preventOverflow` though, because it needs to know the real `popperOffsets` value that gets altered due to overflow prevention... D; so maybe the arrow element shouldn't be …

fix: run arrow modifier after preventOverflow

---

src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js

After testing, subpixel values like `.75px` causes blurry text on my retina display, so we'll need to round the values. We can do this to the nearest suitable subpixel reported by `window.devicePixelRatio`
We still need to disable `transform` on low PPI displays because layer acceleration can disable subpixel rendering which leads to slightly blurry text
Fixes #764 (forever hopefully)

fix: blurry text (better)

---

packages/popper/src/utils/getBordersSize.js
packages/popper/src/utils/getOffsetRectRelativeToArbitraryNode.js

Fix superfluous argument passed to `parseFloat()`.

---

src/index.js

The `previouslyAppliedPlacement` thing we discussed only works if the margins are the same for vertical/horizontal placement, if they differ it doesn't work still. 
This trick is also lightest on bundle size.

fix: arrow jitter

---

src/dom-utils/getClippingRect.js
src/enums.js
src/modifiers/detectOverflow.js
src/popper.js
tests/visual/modifiers/flip/index.html

We need to be able to specify a "root" area that overflow will fallback to.
`flip` goes from `clippingParents` to the `viewport` root, while `preventOverflow` (usually) goes back to the `document` root while "skipping" the viewport. Sometimes users choose viewport for preventOverflow  for the root though.
```ts
type Options = {
area: OverflowArea,
rootArea: RootOverflowArea,
elementContext: Context,
altArea: boolean,
};
```
There was an idea to specify `[area, ...fallbackAreas]` but it didn't really work.

feat: root overflow areas

---

src/modifiers/arrow.js

`arrow` requires `preventOverflow`, but `preventOverflow` requires arrow, but the element isn't until after the first load, so the initial position may be wrong.

fix: set arrow element onLoad

---

package.json

so that patch-package doesn't run when popperjs imported as a dependency
Installing popper.js@next as a dependency in a project will typically fail, because "patch-package" likely won't be present in the host project
It seems that the patches are only needed at build-time - in this case, switching to `prepare` achieves the same effect without affecting downstream dependents

Use prepare instead of postinstall for patch-package

---

package.json
src/dom-utils/getClippingRect.js
src/enums.js
src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js
src/modifiers/eventListeners.js
src/modifiers/flip.js
src/modifiers/hide.js
src/modifiers/offset.js
src/modifiers/preventOverflow.js
src/popper.js
src/utils/detectOverflow.js

Working on the docs helped me realize to refactor these:
- Rename `OverflowArea` to `Boundary` and use `boundary` over `area`
- Remove `viewport` as a `Boundary` (it's a root)
- Use 2D transforms when `gpuAcceleration` is enabled for low PPI displays. I think that only 3D transforms disable subpixel text rendering?
- Change `offset` to `main` phase since `detectOverflow` is no longer a modifier
- Export `hide` as a default modifier (only `0.2kb` gzip for the full file)
- Change `computeStyles` phase to `beforeWrite`
- Change the default `esm` to the full Popper like `cjs` and `umd`. I think it's too confusing to make Lite default – tree-shaking should be opt-in, than opt-out by default. I can see this being a frustrating default. A lot of people likely just want it to "work" on first try …

refactor: various apis

---

docs/src/components/Layout.js
docs/src/components/Navigation.js
docs/src/pages/docs/utils/detectOverflow.mdx
docs/src/pages/docs/utils/index.mdx
docs/src/utils/processRoutes.js

We want to order like:
- `Home`
- `Documentation`
- `Modifiers`
- `Popper Offsets`
- `...` (based on default dependencies and phase, we can manually specify this?)
- `Utils`
- `Detect Overflow`
- `Typings`
Tried using `index` in the frontmatter but the `MdxRoutes` plugin doesn't seem to pick it up.
`docs/src/utils/processRoutes.js` algorithm is so inefficient/brittle 😥, needs improvement, pls help @FezVrasta 😄

docs: route ordering and utils docs

---

src/dom-utils/getClippingRect.js
src/enums.js
src/modifiers/__snapshots__/offset.test.js.snap
src/modifiers/hide.js
src/modifiers/offset.js
src/types.js
src/utils/detectOverflow.js
src/utils/getFreshSideObject.js
src/utils/mergePaddingObject.js

This is because the viewport bottom could be above the clippingParents bottom, for example. 
This allows for the `[...boundaryElements, rootBoundary]` pattern, so you can use an array of elements for `boundary` (#598):
```js
// Gets the minimum bounds of all of these boundaries
// (aka the maximum area the element is visible in)
boundary: [element1, element2, ...],
rootBoundary: 'viewport'
```
It doesn't really work like a "fallback", rather a list of elements whose rects will be reduced into a virtual area that can clip the element. @whitecolor
I think it still makes sense to split the `root`, as it can be easy to forget to need to use an array to specify a root placement when using an element.
There was a problem with `detectOverflow`'s `offset` calculation. It was using the …

fix: getClippingRect / detectOverflow calculations

---

src/__snapshots__/index.test.js.snap
src/index.js
src/index.test.js
src/modifiers/applyStyles.js
src/modifiers/arrow.js
src/modifiers/computeStyles.js
src/modifiers/eventListeners.js
src/modifiers/flip.js
src/modifiers/hide.js
src/modifiers/offset.js
src/modifiers/popperOffsets.js
src/modifiers/preventOverflow.js
src/types.js
src/utils/uniqueBy.js
src/utils/uniqueBy.test.js

- Runs `onLoad` and `onDestroy` in `.setOptions()`
- I don't see the need to `return state` since the user just modifies a permanent state object. There's no returning of a clone involved, so it's not necessary? It's easy to forget to remember to return the state object too so this seems less bug prone.
- `validateModifiers` was not running for modifiers if they got filtered out of `state.orderedModifiers` (e.g. they have no `phase` property - I kept forgetting it)
- Adds the `state` object to the instance

fix: popper instance

---

src/index.js
src/types.js
src/utils/unwrapJqueryElement.js

Should fix #917 @HHogg 
I removed the whole `jQueryWrapper` handling because I don't think it's useful moving forward with such a modern library, Tippy doesn't handle this at all and doesn't get complaints.

fix: createPopper argument types

---

docs/src/components/Demos.js
docs/src/components/Popper.js
docs/src/pages/docs/virtual-elements.mdx
docs/src/utils/processRoutes.js
src/dom-utils/unwrapVirtualElement.js
src/types.js
src/utils/detectOverflow.js
tests/visual/virtual.html

There's no need for `contextElement` anymore since the offsetParent is always relative to the popper element.

refactor(VirtualElement): remove contextElement and add docs

---

docs/src/pages/docs/modifiers/index.mdx
src/__snapshots__/index.test.js.snap
src/index.js
src/index.test.js
src/modifiers/applyStyles.js
src/modifiers/arrow.js
src/modifiers/eventListeners.js
src/types.js
src/utils/validateModifiers.js

This replaces `onLoad` / `onDestroy` and works like React's `useEffect` where the cleanup function is returned as a function:
```js
function effect() {
// perform side effects
return () => {
// cleanup side effects
};
}
```
This naming works better with `.setOptions()` since `onLoad` / `onDestroy` was getting called for option changes, which doesn't really make semantic sense. Grouping these under a unified "effect" works better, where variables can be shared in the closure instead of two separate callback functions.
The previous `onDestroy` was also being called at the wrong location (should be called at the top). `State` can no longer be returned from these but I don't see how that was useful.

feat: effects

---

docs/src/pages/docs/modifiers/prevent-overflow.mdx
src/modifiers/preventOverflow.js
tests/visual/modifiers/flip/checkVariation-larger.html
tests/visual/modifiers/flip/checkVariation-shorter.html
tests/visual/modifiers/flip/checkVariation.html

This matches `flip`. 
Reasoning:
> If our goal is to keep the popper in view as best as possible, this makes sense I think. The reason is, the viewport is as valid as a clipping element as a scrolling container for example
Issue: https://github.com/popperjs/react-popper/issues/295
When using `flipVariations` this can make the popper not be aligned to the edge, which may be more desirable than preventing the overflow. In that case the user can choose `document` as the `rootBoundary`
This will also fix transition issues of the popper by default when its content changes near a boundary, e.g. Tippy's singleton which stretches the document.

fix(preventOverflow): make viewport default rootBoundary

---

src/popper-lite.js
src/popper.js

When using `popperGenerator`, this allows you to inherit or spread in the modifiers while also adding some more.
```js
import { popperGenerator, defaultModifiers } from '@popperjs/core/lib/popper-lite';
import flip from '@popperjs/core/lib/modifiers/flip';
const createPopper = popperGenerator({
defaultModifiers: [...defaultModifiers, flip],
});
```

feat: export default modifiers

---

src/index.js

Whenever options change, the modifiers need to re-run as well, not just the effects

fix: first update callsite

---

docs/src/pages/docs/modifiers/flip.mdx
docs/src/pages/docs/modifiers/prevent-overflow.mdx

I think, `area` was in the early implementation, but now, modificators don't have area option in the code

Fixed typo in docs

---

src/index.js
src/modifiers/flip.js

This isn't included in the IE11 polyfill list and this util makes more sense to use

refactor: remove String.prototype.includes usage

---

src/modifiers/arrow.js

This is a possible fix for issue #940

fix: allow arrow elements to be in shadow DOM

---

docs/src/pages/docs/v2/modifiers/compute-styles.mdx
src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js

Or more generally when `adaptive: false`.
And add a temp unreleased note for now, remove after final release

fix(computeStyles): ignore unsetSides for arrow

---

docs/src/components/Demos.js
docs/src/components/Landing.js
docs/src/components/Layout.js
docs/src/components/Navigation.js

The prod build is somehow different from the dev (completely messed up popcorn box position...) I hope this fixes it, the non-deterministic build bugs are bad
All the style attributes are suddenly not working in prod 🤦‍♂

docs: use css prop

---

docs/src/components/Landing.js

hi,
just a small "improvement": prevent landing page samples from scrolling the whole page when their inner scroll reach the sample boundaries.

docs: contain landing page samples scroll

---

docs/src/pages/docs/v2/faq.mdx
src/index.js
src/index.test.js
src/modifiers/applyStyles.js

When upgrading from Popper v1 to Popper v2, the consumer can leave `margin` on their popper and cause problems since we no longer consider it. 
I've seen a library do this when upgrading today when searching on GitHub and they don't realize the bug exists (their margin is somewhat small).

fix: add margin warning

---

src/dom-utils/getClippingRect.js
src/dom-utils/getDecorations.js
src/utils/__snapshots__/computeAutoPlacement.test.js.snap

Fixes #969
Is this approach sound? If the page is horizontally scrollable, `documentElement` doesn't seem to get affected, only `body`. So this should work.

fix: take into account document element scrollbar

---

src/dom-utils/contains.js

Pre-chromium Edge needs polyfills for web components. The ShadyDOM polyfill has a bug that prevents `isSameNode` from being called on `shadowRoot` nodes. This change works around that.
Fixes #979

fix: workaround Edge problem with web component polyfill

---

docs/src/components/Landing.js
docs/src/pages/docs/v2/browser-support.mdx
src/dom-utils/getClippingRect.js
src/dom-utils/getScrollParent.js
src/dom-utils/isTableElement.js
src/modifiers/applyStyles.js
src/modifiers/arrow.js
src/modifiers/flip.js
src/modifiers/offset.js
src/utils/computeAutoPlacement.js
src/utils/detectOverflow.js
src/utils/getMainAxisFromPlacement.js
src/utils/validateModifiers.js
typescript/ts.js

This should address the concerns expressed in https://github.com/mui-org/material-ui/issues/19358
The required polyfills for IE11 now are just `Promise` and `Object.assign`.
The brotli-compressed bundles ended up being lighter for some reason, while the gzip ones are ~0.01kB larger
cc @eps1lon and @oliviertassinari

fix: reduce polyfills needed on IE11

---

src/dom-utils/getClippingRect.js
src/dom-utils/getCompositeRect.js
src/dom-utils/getNodeName.js
src/dom-utils/getNodeScroll.js
src/dom-utils/getWindow.js
src/dom-utils/getWindowScroll.js
src/dom-utils/listScrollParents.js
src/modifiers/computeStyles.js
src/types.js

I define our own `Window` type so that we gain more type safety when we work with window objects.

fix(types): add Window type

---

src/index.js
src/modifiers/computeStyles.js

Also `computeStyles` had broken syntax highlighting due to `(win: Window)` so I split it out

fix: warning improvements

---

src/modifiers/applyStyles.js
src/modifiers/applyStyles.test.js

Inline styles specified in `initialStyles` are getting removed from the reference element upon destroy. Other line changes are small perf tweaks

fix(applyStyles): don't remove reference inline styles

---

src/modifiers/flip.js

🚨**I'm not 100% sure of this**
I think I added this due to `auto` but in v1 you could specify a placement again, but I think that was only because v1 didn't revert to the originally preferred placement:
```js
behavior: ['top', 'bottom', 'top']
```
This removes that ability since it only contains unique placements. Does it make sense to filter dupes out or not?
```js
// this expands to the four base placements, and contains another 
// "right" somewhere (where it has the most space)
fallbackPlacements: ['right', 'auto']
```
I think it will just get ignored in v2 so it doesn't affect anything — this change will remove the `uniqueBy` function completely with production DCE and improve bundle+runtime perf (except potentially in the worst case with lots of repeated/dupe placements).

fix(flip): remove uniqueBy

---

src/modifiers/applyStyles.js

With certain CSS styling this prevents the arrow from being positioned incorrectly on first load

fix(applyStyles): apply initial styles to arrow

---

src/index.js
src/utils/__snapshots__/mergeByName.test.js.snap
src/utils/mergeByName.js
src/utils/mergeByName.test.js

As mentioned on Spectrum, the new data structure allows for this and should be done by default I think. It's not too large and handles custom modifiers.
Modifiers later in the array override earlier modifiers in the array. It also deep-merges `data` and `options` objects, but not their values. Expected behavior? Will it break existing merge setups?

fix: merge modifiers by name

---

src/dom-utils/instanceOf.js

When using popper in an iframe, if the elements are created in the code's global context and added to the iframe, exceptions are thrown because prototypeOf does not accurately assess which nodes are Elements or HTMLElements.
This fixes https://github.com/popperjs/popper-core/issues/1018.

Fix error in some situations with iframes

---

docs/src/pages/docs/v2/faq.mdx

Just encountered this... I had accidentally left off the doctype on my demo playground.

docs: add standards mode faq answer and fix typos

---

src/modifiers/arrow.js
src/modifiers/preventOverflow.js

A tweak to #1023
The arrow's `offsetParent` may not always be the popper, for example with the following DOM:
```html
<div id="popper"> 
<div id="box"> 
<div id="arrow"></div>
</div>
</div>
```
This still handles the case where the popper is the `offsetParent` (the existing test)
What it doesn't handle is the case where the popper is not the `offsetParent`, but it has a border/scrollbar. (This also includes any arbitrary parentNodes of the `offsetParent` that have borders/scrollbars I think).
In the cases I am using it, the `offsetParent` is always the one with the border & styling. I'm not sure if handling all arbitrary parents' client offsets is common or worth it...

fix: arrow position using offsetParent client offset

---

.config/rollup.config.js
src/popper-base.js
src/popper-lite.js
src/popper.js

As discussed in #1031, this PR makes two changes:
- Updates the Rollup config to ensure Flow types are shipped with the CommonJS build, which is the `main` of `package.json`
- Ensures type definitions, which will be stripped by babel in the build, are exported from the three bundle entry points' source files, so that clients may import type definitions from them
- @FezVrasta I didn't get a answer back from you about whether or not this change was desired, so I went ahead and made the change
- Let me know if I need to revert it / replace it with something else
**Before**
```js
// @flow
import { createPopper } from '@popperjs/core'
// createPopper is typed any
import type { Instance } from '@popperjs/core'
// cannot find export Instance
```
**After**
```js
// @flow
import { createPopper } …
```

fix(types): Export Flow type definitions from entry points

---

src/modifiers/computeStyles.js

In testing environments, JSDOM, getComputedStyle is returning null. This causes [transitionProperty.indexOf(property)](https://github.com/popperjs/popper-core/blob/master/src/modifiers/computeStyles.js#L128) to throw an error.
I've set a default value to stop the error throwing.

Set default value for getComputedStyle transitionProperty.

---

src/index.js
src/modifiers/applyStyles.js
src/modifiers/arrow.js
src/modifiers/computeStyles.js
src/modifiers/eventListeners.js
src/modifiers/flip.js
src/modifiers/hide.js
src/modifiers/offset.js
src/modifiers/popperOffsets.js
src/modifiers/preventOverflow.js
src/types.js

- ~Need to test with TS as well~ (TS works, although the red squiggles in VSCode don't place themselves in useful locations...)
You can now do this for typechecking:
```js
// @flow
import type {Modifier, StrictModifiers} from '@popperjs/core';
type CustomModifier = $Shape<Modifier<any>> & {
name: 'custom',
options?: $Shape<{customOption: boolean}>,
};
type ExtendedModifiers = StrictModifiers | CustomModifier;
createPopper<ExtendedModifiers>(ref, pop, {
modifiers: [
{name: 'offset', options: {offset: [0, '']}}, // type error
{name: 'custom', options: {customOption: true}}, // no error
]
});
```

fix(types): options types

---

package.json
src/modifiers/arrow.js
src/modifiers/computeStyles.js
src/modifiers/eventListeners.js
src/modifiers/flip.js
src/modifiers/offset.js
src/modifiers/preventOverflow.js

Hello. Thanks for the great library.
I am switching to v2 and I have some problems with types from popperJS.
1. My eslint gives an export error and does not find types.
2. I wrapping popper and would like to get options types for default modifiers

Type enhancements

---

src/types.js

Without the clarifying parentheses it the return type of
the effect function is "function returning either void or void" 
instead of the intended "void or function returning void"

fix return type for effect function

---

src/dom-utils/getDocumentRect.js
src/dom-utils/getViewportRect.js

Problems I encountered:
1. `documentRect` width was inaccurate (area outside of `<html>` / `<body>` bounds if it was horizontally scrollable) and possibly the height. I'm not sure what effects this has exactly since it seemed to work before with `rootBoundary: "document"`
2. `viewportRect` in mobile emulation mode when pinch zooming broke the horizontal demo in #1097 - it looks like the feature detection doesn't work with when the browser has zoomed the viewport out. I cannot think of a way to fix it besides userAgent detection which can easily break in the future if Safari decides to start using "layout viewport"...

fix: root rects

---

src/dom-utils/getOffsetParent.js

@AlbertLucianto @rijkvanzanten does this fix the issue?
Closes #1128

fix(getContainingBlock): check html in while loop

---

src/modifiers/flip.js
src/utils/computeAutoPlacement.js

In the case that the placement is `"auto"`, but they only specify `"bottom-start" as an allowed placement, it doesn't make sense — this adds a helpful error message that lets them know.
Closes #1133

fix: add auto error

---

src/dom-utils/getClippingRect.js
src/modifiers/hide.js
src/utils/detectOverflow.js

Since the body might not extend the entire scrollable area of the document it shouldn't be included as a clippingParent.
Closes #1127 
@skvale can you confirm?
Also @FezVrasta we should apply Prettier 2 to the entire codebase since saving files adds those changes each time which are unrelated

fix: remove body as a clippingParent

---

src/dom-utils/getClippingRect.js

Closes #1146 
The element (`reference`) itself was considered a `clippingParent` due to `overflow` property, but it should be excluded.

fix: exclude self as scrollParent

---

src/dom-utils/getDocumentElement.js

After we introduced PopperJS into our project our Sentry started catching a lot of errors from the `getDocumentElement` function. It appears that it's possible for an element to be lacking both `ownerDocument` and `document` properties, so the line `isElement(element) ? element.ownerDocument : element.document).documentElement` would become `undefined.documentElement` and throw an error.
I made a fork of this repository and added some extra logging to verify it, and this is what I got:
```js
const { ownerDocument, document: baseDocument } = element;
const { document: windowDocument } = window;
console.log({
element,
isElement: isElement(element),
ownerDocument,
baseDocument,
ownerDocumentElement: ownerDocument && ownerDocument.documentElement,
baseDocumentElement: baseDocument && …
```

fix: add fallback to window.document for getDocumentElement

---

src/dom-utils/getWindow.js

Errors are thrown when an iframe is destroyed because the popper's reference node document no longer has a `defaultView`. The errors being thrown are:
> Cannot read property 'Element' of null
and
> Cannot read property 'HTMLElement' of null
from within `update`.
This fix will ensure the code runs and exits safely from calculations when the iframe `window` is no longer accessible.

Fix errors when iframes are destroyed

---

src/dom-utils/contains.js

This is an issue we are facing in Salesforce Lightning Locker where `getRootNode()` is returning `undefined` thus resulting in an error checking for `host`.

Additional check for rootNode

---

src/dom-utils/contains.js
src/dom-utils/contains.test.js
src/dom-utils/instanceOf.js
src/types.js

> The getRootNode() method of the Node interface returns the context object's root, which optionally includes the shadow root if it is available.
> https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode
> The root of an object is itself, if its parent is null, or else it is the root of its parent. The root of a tree is any object participating in that tree whose parent is null.
> https://dom.spec.whatwg.org/#concept-tree-root
When dealing with detached DOM - their `ParentNode` is null, thus `getRootNode()` returns the node itself. 
Popper uses **ducktyping** to determine whether returned object represents `ShadowRoot` or not. It does it by checking for presence of `{probablyShadowRoot}.host` property.
This has a possibility to clash with Location Interface via …

Properly check if we're inside Shadow DOM

---

src/dom-utils/contains.js

IE11 does not support `getRootNode`. 
When `parent.contains(child)` is `false`, IE11 raises `Unable to get property 'toString'` error.　
This PR adds a check that `rootNode` is not `undefined`.
https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode

Fix: IE11 does not support getRootNode

---

.flowconfig
package.json
src/createPopper.js
src/dom-utils/contains.js
src/dom-utils/getClippingRect.js
src/dom-utils/getDocumentElement.js
src/dom-utils/getParentNode.js
src/dom-utils/getScrollParent.js
src/dom-utils/listScrollParents.js
src/modifiers/applyStyles.js
src/modifiers/computeStyles.js
src/utils/computeAutoPlacement.js
tests/flowtype/modifiers.js
yarn.lock

0.139 is the latest flow release, it seems like not many changes are needed and 139 is a significant improvement in safety.
I also tacked on a configuration change that turns on flow warnings and a resolution for all extant warnings. Any project that depends on `popper-core` and has `include_warnings` set to `true` would see these warnings. Most of these warnings are from no error code being supplied for `$FlowFixMe`s but there was one unused suppression that I removed.

Upgrade flow to 0.139

---

src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js
src/utils/computeOffsets.js

As reported in #1169 rounding logic in some cases makes the popper not correctly aligned with reference element. This PR adds possibility to opt out from it via roundOffsets option.
```js
createPopper(reference, popper, {
modifiers: [
{
name: 'computeStyles',
options: {
roundOffsets: false,
},
},
],
});
```

feat: add `roundOffsets` option to computeStyles modifier

---

src/dom-utils/listScrollParents.js

I have been using popper inside my extension so I don't always control the page it is run on.
Some salesforce popup do not have a body but `element.ownerDocument.body` references an element `<frameset>`. 
It was causing an infinite loop trying to loop for all the scroll parents.
This PR is just to ensure we check for this body (whatever its tagName)

fix: check for body not based on tagName

---

src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js

> For decimal px value may cause transform and keyframe animation shake issues,
This PR will improve computeStyles option `roundOffsets` with customize implement ability.
also fix the builtin `roundOffsetsByDPR` with a real round returns. 
eg. 
```
JSON.stringify(state.styles.popper, null, 2)
"{
"position": "absolute",
"top": "auto",
"right": "auto",
"bottom": "217.6px", // <<<---
"left": "440.3px",  // <<<---
"transform": ""
}"
=> "{
"position": "absolute",
"top": "auto",
"right": "auto",
"bottom": "218px",  // <<<---
"left": "440px",  // <<<---
"transform": ""
}"
```

fix: improve computeStyles modifier with customize roundOffsets support

---

src/dom-utils/getOffsetParent.js

fix https://github.com/popperjs/popper-core/issues/1229
since only `will-change` value of `transform` or `perspective` I decided to put this in code
https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block
point 4.2

fix: will-change create containig block

---

src/dom-utils/instanceOf.js

Noticed during https://github.com/mui-org/material-ui/pull/25039.
Test plan:
If I can install a build from this PR I can test it against mui-org/material-ui. Otherwise I don't know how to test it.
Steps to reproduce: 
1. Goto https://deploy-preview-25039--material-ui.netlify.app/components/popper/#main-content
2. Click "toggle popper"
3. Click "toggle popper" again
Actual behavior:
Crashes with `TypeError: Invalid operand to 'instanceof': Function expected`
Expected behavior:
No crash like in https://next.material-ui.com/components/popper/#main-content
Alternate:
`return OwnElement !== undefined && node instanceof OwnElement || typeof ShadowRoot !== 'undefined' && node instanceof ShadowRoot;`
But it seems more robust to just return early if we know that the current window has now …

fix: Prevent crash in browsers without ShadowRoot support

---

src/dom-utils/getWindow.js

Make getWindow null/undefined safe again to fix some IE11 issues.
See #1159 for details.

Make getWindow null/undefined safe again

---

src/dom-utils/getOffsetParent.js

According to CSS 2.1 (https://www.w3.org/TR/CSS21/visudet.html#containing-block-details) which is used by Internet Explorer for containing block calculation (https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa768717(v=vs.85)) i prepared a fix which is obtaining correct containing block (same as IE will use for displaying content on page).
This fix will ensure that we use correct containing blocks for IE 9, 10 and 11.
I cannot paste codepen, cause it has some errors on IE.
However You can check new behavior using code below. I also added core-js to polyfill ES6 functions
```html
<!DOCTYPE html>
<title>Transform Visual Test</title>
<style>
#transform {
position: fixed;
transform: translate(200px, 200px);
}
#tooltip {
background-color: …
```

fix: fixing invalid containing block calculation on IE for fixed strategy

---

src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js

When we use the placement `left`, the coordinates used aren't `top:0; left:0` anymore but `top:0; right:0`.
Same thing with the placement `top`, the coordinates used become `bottom:0; left:0`.
But using `bottom-end` and `top-end` also also use the coordinate `right:0` was end specifies that the popup should be stuck at the end of the the X axis, aka on the right. (and same with `left-end` and `right-end`, they should be stuck at the bottom).
An effective benefits of flipping the axis is that if the popup grows, the sides that are stuck won't move. So if someone uses `left-end`, the popup will be stuck on the right and on the bottom.

fix: use other direction with end variation

---

src/utils/detectOverflow.js

Since modifiers can change state, `detectOverflow` should use state's rect instead of rect returned by `getBoundingClientRect`

Detect overflow should use state rect

---

package.json

The usage of `process.env.NODE_ENV` is causing issues in svelte-repl and Vite and has been a pain point for other users (https://github.com/popperjs/popper-core/issues/933). `main`, `main:umd`, and `module` do not specify all the various ways to use the library. Right now there's nothing that points at `dist/esm/popper.js`. With an `exports` map we can better specify which version of the distribution should be used. Some tools like Vite want to automatically import one version on the server and another version in the browser. If you make the user manually point and the specific distribution it won't work. Instead we need to specify it in `package.json`

Add an exports map

---

src/modifiers/computeStyles.js

There are some monitors with e.g. `devicePixelRatio` value of `1.25`.
I assume the intent with this code is to use `translate3d` whenever the device-pixel-ratio is above 1?
If that's the intent, I'd suggest a slight modification to handle screens with device-pixel-ratios in the `1.0...2.0` range.
In practice, this fixes an issue with blurry popper elements when the device pixel ratio is between 1.0 and 2.0.

Support monitors with 1.25 devicePixelRatio

---

package.json

Reverts popperjs/popper-core#1342

Revert "Add an exports map"

---

src/modifiers/computeStyles.js

@allex why was the extra round function added? For the rounding to be done by DPR, the outer one mustn't exist
Fixes #1300

fix(computeStyles): remove outer round function

---

package.json
src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js
tests/visual/mobile/fixed.html
yarn.lock

Fixes #1136 
`document.documentElement.clientHeight` returns the height of the viewport including the bottom address bar, but fixed elements do not get positioned using that strategy. Tested on iOS 15 + iPhone 13 Simulator with XCode.

fix(computeStyles): adaptive option with fixed strategy on mobile

---

src/modifiers/__snapshots__/computeStyles.test.js.snap
src/modifiers/computeStyles.js
src/modifiers/computeStyles.test.js

Fixes #1300
Fixes #1410
Refs #1400
Rounding was previously happening to _ONE_ of the measured inputs and then other inputs were not, so the output wouldn't actually be rounded. This moves the rounding to _only_ happen at the end of the style calculations so that it ensure the styles sent the the client are rounded.

fix: round after math

---

packages/core/src/middleware/autoPlacement.ts
packages/core/src/middleware/flip.ts
packages/core/src/middleware/shift.ts
packages/core/src/middleware/size.ts
packages/dom/src/index.ts
packages/dom/src/types.ts

This wraps some exported types with stricter types than the core, namely `boundary` in `DetectOverflowOptions`, `element` in the `arrow` middleware, and `contextElement` in a `VirtualElement`
- Adding type testing in a new PR

fix(types): strict DOM types

---

packages/dom/src/utils/contains.ts

The ` isSameNode()` method of the Node interface is a legacy, use `===` replace ` isSameNode()` method

use `===`  replace isSameNode

---

website/next.config.js
website/pages/docs/getting-started.mdx
website/pages/docs/tutorial.mdx

- Links both esm and umd ways of CDN consumption
- Locked versions linked by default
- Uses esm format by default in the tutorial

docs: improve CDN usage

---

packages/react-dom/index.test-d.ts
packages/react-dom/index.test-d.tsx
packages/react-dom/src/index.ts
packages/react-native/index.test-d.tsx

Arrow element has type HTMLElement | undefined. That cause a TS error with const `arrowRef = useRef(null)`.
If you use useRef without init value (`arrowRef = useRef()`) you got TS error on the target element.
**Solution**
Change arrow element type to `HTMLElement | null`.
reproduction: https://codesandbox.io/s/floating-ui-react-dom-visual-test-05xpu?file=/src/App.tsx
**Notes**
You can see in the example that there are other errors. It copy-pasted version of the https://github.com/floating-ui/floating-ui/blob/master/packages/react-dom/test/visual/index.js with annotated `arrowRef`. This pull request takes care only of the arrow element, not other errors.

fix: arrow element TS definition

---

packages/core/package.json
packages/dom/package.json
packages/react-dom/package.json

A library such as `rollup-plugin-svelte` relies on a module's exposure of its `package.json` file in order to interrogate it (for a [`svelte` field](https://github.com/sveltejs/rollup-plugin-svelte#pkgsvelte) in their case, permitting it to import an uncompiled version of the distribution). It is common practice to export this file; see '[Package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points)' section of the official docs for an example.
As a consequence, exporting `package.json` would remove the following warning presented to consumers needing to compile Svelte components, for example:
> [rollup-plugin-svelte] The following packages did not export their package.json file so we could not check the "svelte" field. If you had difficulties importing svelte …

export `package.json`

---

packages/core/src/middleware/shift.ts

Allows consumer to create a dynamic strategy between `fixed` and `absolute` if `shift.{x,y} !== 0`, e.g. for an implementation similar to CSS `position: sticky`

feat(shift): expose coords data

---

package-lock.json
website/next.config.js
website/package.json

As Rolling Versions doesn't add a commit to update the versions locally, we now need to fetch it from NPM

docs: fetch latest npm versions for CDN links

---

src/dom-utils/getClippingRect.js
tests/functional/clipping-parent.test.js

Fixes #1477 
It appears #1399 is hard to fix without breaking more common DOM layout cases. 
The problem is that the clipping parent contains a clipper element with an absolute position, which causes the clipping parent's size to collapse to nothing, but the popper can still fit within its offsetParent without being clipped. The current solution broke #1477 though... I tried working on a solution but none solved every case. 
I think reverting is the best option for now — that issue had no votes, so I don't think that type of layout is very common in comparison to the one this will now fix. This is also safer as it will always check overflow correctly, and the escape hatch for #1399 is setting a custom boundary.

Revert #1399

---

packages/dom/src/utils/getViewportRect.ts

This value when pinch zoomed on FF can be above 0.001

fix(dom/getViewportRect): Firefox pinch zooming

---

packages/react-dom/src/index.ts
packages/react-native/src/index.ts

Allows the options to be diffed by the `deepEqual` compare to update on hot reload

fix(react): return options on exported arrow middleware

---

.github/workflows/release-floating-ui.yml
.github/workflows/release-popper.yml

With these changes we should be able to manually trigger the new workflow to release Popper versions.

add workflow to release popper versions

---

packages/react-native/rollup.config.js
packages/react-native/src/floating-ui.core.d.ts
packages/react-native/src/index.ts
website/pages/docs/react-native.mdx

- chore: avoid bundling in `core` package by referring to the CJS build in the imports, remove minified bundles
- fix: stale `computePositions` by cleaning up animation frames
- fix: `isMountedRef` boolean 
- docs: use `?? 0` in the example

fix(react-native): bundle, async cleanup

---

packages/react-dom/src/index.ts
packages/react-native/src/index.ts

React DOM:
- Match isMountedRef behavior from https://github.com/floating-ui/floating-ui/pull/1499
React Native:
- Cleanup `animationFrames` array

fix: react issues

---

packages/core/package.json
packages/core/rollup.config.js
packages/dom/package.json
packages/dom/rollup.config.js

fixes #1497
Split the `import` fork in the export maps to include `node` and `default` subtrees.
Add `browser` and `default` subtree to initial `default`.
Add a "browser" build at `./dist/floating-ui.core.esm.browser.js` and `./dist/floating-ui.dom.esm.browser.js` the is not minified and does not include the debugging forks. It's possible that this _should_ be the inverse and include the debugging forks _always_, but let me know what you think here.
I've tested this locally in a browser with the `development` condition both on and off and it's working pretty nicely, however I'd definitely suggest a pre-/beta release with this as export maps continue to surprise me when actually consumed across a number of different contexts.

feat: expand export maps to support no/low build tooling

---

src/dom-utils/getOffsetParent.js
tests/visual/transform/shadow-dom-fixed-host-translated.html
tests/visual/transform/shadow-dom-fixed-parent-host-translated.html
tests/visual/transform/shadow-dom-fixed-parent-translated.html
tests/visual/transform/shadow-dom-host-translated.html
tests/visual/transform/shadow-dom-parent-host-translated.html
tests/visual/transform/shadow-dom-parent-translated.html

Related issue: #1488 
This fixes a placement issue that is caused when the starting offset parent element is inside shadow DOM. You can see this in the following repro cases based on the original issue:
**w/ shadow DOM ❌**
https://codepen.io/jcfranco/pen/podrpaR
**w/o shadow DOM ✅**
https://codepen.io/jcfranco/pen/BamdJEK
Basically, if the starting element's parent is a shadow root, it would skip the containing-block block (ba dum tss 🥁). 
**Notes**
* I only modified `getOffsetParent` to use the host if the starting element's parent is a shadow root, but this may also be needed for [subsequent parent node lookups](https://github.com/jcfranco/floating-ui/blob/1094088a128e88e9a36401f24225b8457d34eaeb/src/dom-utils/getOffsetParent.js#L60).
* Related to ☝️, as an alternative, …

fix: update getOffsetParent#getContainingBlock to use host if a starting element's parent is a shadow root

---

packages/core/src/types.ts

According to the [middleware documentation](https://floating-ui.com/docs/shift#data), the middleware should return the values that the floating element has been shifted by in middleware data. All other middleware data are already a part of the `MiddlewareData` type except for `shift`.

fix: `shift` middleware should be a part of `MiddlewareData` type

---

packages/core/src/detectOverflow.ts
packages/dom/index.test-d.ts
packages/dom/src/types.ts
packages/dom/src/utils/getClippingClientRect.ts

In line with `getOverflowAncestors` renaming.

refactor: rename `clippingParents` to `clippingAncestors`

---

packages/dom/test/visual/utils/useScroll.tsx
packages/react-dom/src/index.ts
packages/react-native/src/index.ts

Resolves (partially?) #1532
cc: @valtism
I'm wondering if/how `middlewareData` could be memo'd and why the loop occurs

fix(react): make refs stable + minor adjustments

---

packages/core/src/computePosition.ts
packages/core/src/middleware/hide.ts
packages/dom/src/types.ts
packages/dom/test/visual/spec/Hide.tsx

Closes #1252
Since there are two calls this changes the API of `hide` to only accept a `strategy` string so there's only one call. Now you can pass `...detectOverflowOptions` in.
To get both properties as before, just pass two of them in:
```js
middleware: [
hide({strategy: 'referenceHidden'}),
hide({strategy: 'escaped'})
],
```

feat(hide): pass options

---

packages/core/src/detectOverflow.ts
packages/core/src/middleware/arrow.ts
packages/core/src/middleware/inline.ts
packages/core/src/types.ts
packages/dom/src/platform.ts
packages/dom/src/utils/getClippingRect.ts
packages/react-native/src/createPlatform.ts

- `({element})` => `(element)` as it's unlikely more properties will be added to the argument
- `getClippingClientRect` => `getClippingRect` for consistency and simplicity

refactor: platform

---

packages/core/package.json
packages/dom/package.json
packages/react-dom/package.json

https://github.com/floating-ui/floating-ui/pull/1529
This breaks native CJS which tries to use the `main` field (but it should use the `require` conditional export); should fix various webpack build setups which try to use `.cjs` as a transitive dep

build: change .cjs to .js in main field

---

packages/dom/src/utils/getClippingRect.ts
packages/dom/src/utils/getNearestOverflowAncestor.ts

If the floating element is scrollable it gets considered as a scrollable ancestor but should be ignored.

fix(dom): getOverflowAncestors should ignore current node

---

packages/core/src/computePosition.ts
packages/dom/test/visual/spec/Inline.tsx

Closes #1570
Allows the middleware lifecycle `[inline(), size()]` to work like before:
- `inline`
- reset
- `inline` skipped
- `size`
- reset
- `inline`
- reset
- `inline` skipped
- `size` skipped
- done

fix: delete skipped middleware names

---

packages/core/src/computePosition.ts
packages/core/src/middleware/autoPlacement.ts
packages/core/src/middleware/flip.ts
packages/core/src/middleware/inline.ts
packages/core/src/middleware/size.ts
packages/core/src/types.ts
packages/dom/test/visual/spec/Inline.tsx

Skipping avoided doing unneeded work after a `reset`, but it's difficult to know when a middleware can be skipped when other middleware cause resets, resulting in either stale logic or an infinite loop, so this removes it entirely for now.
Each middleware now checks if it needs to cause a `reset` without relying on skipping.
- ✅  Always runs when it needs to
- ✅  No infinite loops possible
- ⚠️ Slightly reduced perf

refactor: remove skipping

---

.github/workflows/release.yml

Unfortunately GitHub doesn't let us specify a branch with a `repository_dispatch` event, so they can only be used to release from the default branch. If you need to release from a different branch, you can use a `workflow_dispatch` instead. This will let you manually trigger the workflow on your desired branch from the GitHub actions UI.
I plan on updating Rolling Versions to use `workflow_dispatch` in the future as well, this will likely be done by allowing custom configuration of the trigger with something like:
```toml
[release_trigger]
type = "github_workflow_trigger"
name = "release"
```
This likely will not be ready for at least a month or two though. For now, you can specify both `repository_dispatch` and `workflow_dispatch` in your workflow file, and then use the GitHub UI when …

Add workflow_dispatch for manual releases

---

packages/dom/index.test-d.ts
packages/dom/src/types.ts

fix(dom): type elements in MiddlewareArguments

---

src/modifiers/computeStyles.js

Fix issue #1577
I've only fixed the conditions that calculate offset X and Y because an element with the position fixed can be also relative to the parent containing block, not only to the viewport.

Bugfix: element positioning with strategy fixed and containig block in Popper v2

---

packages/dom/src/utils/getOverflowAncestors.ts

Hi! 
This PR fixes autoupdate for following case
```
<div id="scroll" style="overflow: auto">
<div id="container" style="overflow: hidden">
<div id="reference></div>
<div/>
</div>
```
In this case the popup position is not updated when user scrolls the div with id "scroll".  
That happens because getOverflowAncestors misses the parent element of the found overflow ancestor:  
`// take parent first time`  
https://github.com/floating-ui/floating-ui/blob/ffdaa13142fcc3ff300c3472c1fc773a8ba88452/packages/dom/src/utils/getOverflowAncestors.ts#L24  
https://github.com/floating-ui/floating-ui/blob/ffdaa13142fcc3ff300c3472c1fc773a8ba88452/packages/dom/src/utils/getOverflowAncestors.ts#L10
`// take parent second time`  
https://github.com/floating-ui/floating-ui/blob/ffdaa13142fcc3ff300c3472c1fc77 …

Autoupdate -> fix for ancestor scrolling

---

packages/dom/src/utils/getBoundingClientRect.ts

Supports Safari/iOS <=12 (old, but still has a bit of usage on legacy devices)

fix(dom): fallback to ?? 0 when visualViewport is not present

---

src/types.js

This targets 2.x.
Fixes issues with TypeScript 4.7 canary (https://github.com/microsoft/TypeScript/pull/48366 specifically) that are blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
Ran `yarn build:typescript` and made sure the same diff that fixed https://github.com/DefinitelyTyped/DefinitelyTyped/runs/5752176130?check_suite_focus=true#step:6:1271 was applied:
```diff
-export declare type Modifier<Name, Options> = {
+export declare type Modifier<Name, Options extends Obj> = {
name: Name;
enabled: boolean;
phase: ModifierPhases;
requires?: Array<string>;
requiresIfExists?: Array<string>;
fn: (arg0: ModifierArguments<Options>) => State | void;
effect?: (arg0: ModifierArguments<Options>) => (() => void) | void;
options?: Partial<Options>;
data?: Obj;
};

fix(types): Constrain `Modifier` `Options` to same type as `Options` in `ModifierArguments`

---

packages/react-dom-interactions/src/FloatingDelayGroup.tsx
packages/react-dom-interactions/src/FloatingPortal.tsx
packages/react-dom-interactions/src/FloatingTree.tsx

https://twitter.com/reactjs/status/1512453230504124420
Some of the context types seem to also not get their return types inferred correctly upon compiling, so this makes them explicit. 
Was going to update the playground but `react-router-dom` seems to have an issue with React 18 😕

fix(types): React 18 types

---

packages/react-dom-interactions/src/useInteractions.ts
packages/react-dom-interactions/test/unit/useInteractions.test.ts

Also allows `undefined` to be passed in the prop getter rather than needing to pass a no-op like `() => {}`:
```js
getFloatingProps({onKeyDown: cond ? func : undefined}),
```

refactor(useInteractions): simplify merging logic

---

packages/react-dom-interactions/src/hooks/useHover.ts

Fixes two issues:
- Using `restMs` as the hover type in a 2nd-depth level floating element would close it while the user tried to navigate to the 3rd depth level
- The default DX of `delay: 0` not making `restMs` work is poor. Further they need to specify a really high delay if they don't want the delay to ever occur (`Infinity` does not work). This is mainly useful for nested submenus when the submenu renders and the cursor happens to be resting on an item which has a nested submenu, it shouldn't open until the cursor moves.

fix(useHover): restMs

---

packages/react-dom-interactions/src/hooks/useListNavigation.ts

Hovering over nested submenu items then navigating back via arrow keys incorrectly reset the index.

fix(useListNavigation): reset index in pointer leave

---

packages/dom/src/types.ts

Closes https://github.com/floating-ui/floating-ui/issues/1622
This is a simple update to expose the `autoUpdate` options to the types.ts file in `@floating-ui/dom/types.ts` 
This allows for consumers to more easily compose `autoUpdate` into a custom react hook.

fix(types): add AutoUpdateOptions to @floating-ui/dom types.ts

---

packages/dom/src/utils/is.ts

ShadowRoot support was only implemented as of [Modern Edge](https://caniuse.com/mdn-api_shadowroot), so any Legacy Edge version (including the latest, v18) currently suffers a crash when invoking `isShadowRoot()`. I'm aware Legacy Edge support is probably not something that is actively being chased but @floating-ui seems to work just fine apart from this small hitch. Would be great if you'd consider just popping this fix in.
This is basically the same issue that also occurred and was fixed back in the day in popper by @eps1lon, see #1253.

fix(dom): Prevent crash in browsers without ShadowRoot support

---

packages/react-dom-interactions/src/hooks/useTypeahead.ts

If the transient string starts with a space, it's assumed the `Space` key should prefer opening/closing the floating element, not adding to the typeahead string

fix(useTypeahead): improve dataRef typing detection

---

packages/react-dom-interactions/src/FloatingDelayGroup.tsx

Open `delay: 0` is infinite
The `isGroupPhase` boolean in the example doesn't seem to work with `framer-motion` in React 18 😥

fix(FloatingDelayGroup): use 1ms open delay

---

website/pages/docs/motivation.mdx

The link to Tether was pointing to the crypto token by the same name. This fixes the link to point to Tether's latest homepage (per their GitHub repo[1] link).
1. https://github.com/shipshapecode/tether

Fix link to Tether in docs

---

packages/react-dom-interactions/src/hooks/useClick.ts
website/pages/docs/useClick.mdx

- There are cases where `<button>`s are not used e.g. for `role="menuitem"` or `role="option"` but should still have button-like semantics. This makes `useClick` add `Enter` + `Space` key press handling if the reference is not a button. 
- Add a new `ignoreMouse` prop as `click` behavior may not be wanted if `hover` is used for mouse input, e.g. a nested submenu item

feat(useClick): add keyboard handling for non-buttons

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/FloatingPortal.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useFocusTrap.ts
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/src/hooks/useTypeahead.ts
packages/react-dom-interactions/src/safePolygon.ts
packages/react-dom-interactions/src/utils/activeElement.ts
packages/react-dom-interactions/src/utils/isEventTargetWithin.ts
website/pages/docs/FloatingPortal.mdx

When using shadow DOM
- events of event listeners attached to the `document`/`window` object will have the first element with a shadow root as their `event.target`. This currently causes issues with a bunch of "contains" checks. To work around this, `event.composedPath()` should be used, as it will give the complete path of the event, including elements contained in an (open) shadow root.
- `document.activeElement` will not traverse into shadow roots, one has to manually traverse into (open) shadow roots to find the actually focused element within a shadow root.

Improve support for shadow dom / custom elements

---

packages/dom/src/utils/is.ts
packages/dom/src/utils/userAgent.ts

Avoids the blue icon in Chrome DevTools, doesn't actually change anything. 
Closes #1423
[MDN says "brands" is experimental](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/brands) so I hope it doesn't change 😒

fix: avoid navigator.userAgent

---

packages/core/babel.config.js
packages/core/jest.config.js
packages/core/package.json
packages/core/rollup.config.js
packages/dom/babel.config.js
packages/dom/jest.config.js
packages/dom/package.json
packages/dom/rollup.config.js
packages/react-dom-interactions/babel.config.js
packages/react-dom-interactions/jest.config.js
packages/react-dom-interactions/package.json
packages/react-dom-interactions/rollup.config.js
packages/react-dom/babel.config.js
packages/react-dom/jest.config.js
packages/react-dom/package.json
packages/react-dom/rollup.config.js

This copies `zustand`. The previous builds did not allow CJS to work in `create-react-app` because they don't handle `.cjs` correctly.
This PR:
- Removes `type: "module"`
- Removes `.cjs` file, replaces it with`.mjs` file
The magic line seems to be adding `import` with a `.mjs` file, which makes it work in native Node/Nuxt. `create-react-app@4` continues to work because the top-level `"module"` key points to a non-.mjs file.
Tested with:
- CRA 5
- CRA 4
- Nuxt 3
- webpack 5
- Parcel 2
Closes #1676

build: fix package entry points

---

packages/dom/src/autoUpdate.ts
website/pages/docs/autoUpdate.mdx

The `animationFrame` loop only watches the reference rect, but there's one more case that needs to be watched: if the floating element resized. 
There's two ways to fix this:
- Add another frame loop to watch the floating rect (not performant, especially since it only needs a `ResizeObserver`)
- Retain the `ResizeObserver` but only for the floating element (this PR)

fix(autoUpdate): retain floating ResizeObserver with animationFrame

---

packages/core/src/middleware/arrow.ts
packages/react-native/src/createPlatform.ts

Three distinct parts were making arrows not work in React Native
cc: @brycnguyen

fix(react-native): arrows

---

packages/core/src/middleware/offset.ts
packages/core/src/middleware/size.ts
packages/dom/test/visual/spec/Offset.tsx
packages/dom/test/visual/spec/Size.tsx
packages/react-dom/test/index.test.tsx
website/pages/docs/offset.mdx
website/pages/docs/size.mdx

This changes the callback signatures of `size` and `offset` to be more ergonomic. They previously used APIs similar to Popper 2's but this causes usage problems in the context of React.
Before:
```js
const {x, y, reference, floating, strategy, refs} = useFloating({
middleware: [
size({
apply({width, height, reference}) {
Object.assign(refs.floating.current?.style ?? {}, {
width: `${reference.width}px`,
maxWidth: `${width}px`,
maxHeight: `${height}px`,
});
},
}),
],
});
```
After:
- `width` and `height` become `availableWidth` and `availableHeight`, respectively. This better describes what the actual values are.
- `reference` and `floating` top-level keys are gone. Instead the whole `MiddlewareArguments` object gets spread in, so you get access to `rects` + `elements`, no need for the …

refactor: improve callback signatures

---

packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/test/unit/useListNavigation.test.tsx
website/pages/docs/useListNavigation.mdx

Adds two new props to `useListNavigation`
On Windows, select menus navigate through the items rather than opening the floating element when pressing the arrow keys without it being open. This adds some flexibility for different components that should only be opened via `Enter` / `Space` with the keyboard
Currently the disabled check requires the items to be rendered so it can check the attributes on the nodes (`disabled` or `aria-disabled`). But, with Windows-like select menus, the menu doesn't get rendered and so we can't check these attributes, which breaks the `find` logic. This allows the user to pass an array of disabled indices as a replacement to be able to skip items while navigating when the menu is not open. It defaults to an `array` when `openOnArrowKeyDown` is null to prevent …

feat(useListNavigation): `openOnArrowKeyDown` and `disabledIndices` props

---

packages/react-dom-interactions/src/FloatingOverlay.tsx

- Use `overflow: hidden` is possible, has less side effects (so, only iOS needs the `position: fixed` hack).
- Account for `visualViewport` pinch-zoom in iOS

fix(FloatingOverlay): Safari pinch-zoom lockScroll

---

website/pages/docs/FloatingPortal.mdx

Fix typo closing `<div>` tag

---

packages/dom/src/autoUpdate.ts
packages/react-dom-interactions/src/index.ts
packages/react-dom/src/index.ts

On first mount/render, there were unnecessary re-renders occurring due to the update function over-firing. This reduces it to the minimum necessary

perf(react-dom): reduce initial re-renders

---

packages/dom/src/autoUpdate.ts
packages/react-dom-interactions/src/types.ts
packages/react-dom/src/types.ts
packages/react-dom/src/useFloating.ts

This is better as a default and prevents the need to know if it will immediately fire or not (due to the `ResizeObserver`).

fix: normalize `autoUpdate` to always call update fn immediately

---

README.md

The README.md top banner ratio is broken on narrow devices (or narrow window tab).
| before | after |
| ------ | ----- |
| <img width="409" alt="image" src="https://user-images.githubusercontent.com/32478597/168583023-9e77b5b2-ffae-4e1f-aa58-aa15491e2b89.png"> | <img width="407" alt="image" src="https://user-images.githubusercontent.com/32478597/168583087-de01a743-1a58-42d9-8715-ba571ce2de9b.png"> |

fix: Fix README.md top banner size

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/test/unit/FloatingFocusManager.test.tsx

For touch-based screen readers, combobox popups can't be portalled unless every other node between the input and popup have `aria-hidden` — this change allows the popup to be portalled while remaining accessible to touch-based screen readers

fix(FloatingFocusManager): add combobox `aria-hidden` handling

---

packages/react-dom-interactions/src/FloatingPortal.tsx

I ran into an issue with the current implementation. Essentially, when the portal node ref is passed into another component, it is `null` initially. Since it is saved into a ref, it won't trigger a re-render when it changes from `null` to `HTMLElement`, which causes the component not to render at all or render into a wrong node until it rerenders for some other reason.
An example, maybe it is helpful - in this case, ModalInner will never be rendered:
```
export const Modal: React.FunctionComponent<Props> = (props) => {
const portalNode = useFloatingPortalNode();
if (!portalNode) {
return null;
}
// portalNode is required
return <ModalInner {...props} portalNode={portalNode} />;
};
```
Happy to discuss other ways as well how this could be improved - it was easier to file this simple PR to …

fix: save portal node to state instead of ref

---

package-lock.json
packages/react-dom-interactions/package.json

Yarn requires peer dependencies to be specified at each level of nesting if you have deeply nested packages with peer deps.  This adds the missing peer deps to react-dom-interactions since it depends on `@floating-ui/react-dom` which has peer deps.
This is what the error currently looks like that this will fix.

Add missing peer dependencies

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/test/unit/FloatingFocusManager.test.tsx

Brought up in https://github.com/floating-ui/floating-ui/discussions/1717. In non-modal mode, `shift+tab` outside of the reference element should close the floating element if it is open.

fix(FloatingFocusManager): `shift+tab` outside reference element closes floating element

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useClick.ts
packages/react-dom-interactions/src/hooks/useFocus.ts
packages/react-dom-interactions/src/utils/isTypeableElement.ts
packages/react-dom-interactions/test/unit/useClick.test.tsx

Addresses some small edge cases:
- fix(useFocus): `pointerDown` on reference, then `shift+tab` outside the reference when it was first in the focus order (window blurred) would not run the focus handler when tabbing back into it.
- fix(useClick): enabling `pointerDown` should not respond to right click or other mouse buttons, only the "main" button.
- fix(FloatingFocusManager/useClick): improve `isInputCombobox()` check by checking for typeability (incl. `textarea` and `contenteditable` elements). In addition, don't add a Space keyboard handler for `useClick()` when the reference is typeable.

fix(react-dom-interactions): some edge cases

---

packages/dom/index.test-d.ts
packages/dom/src/types.ts
packages/react-dom/index.test-d.tsx

`elements` was typed as `any` but should have strict DOM types

fix(types): missing DOM types

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/safePolygon.ts
packages/react-dom-interactions/src/utils/getAncestors.ts
packages/react-dom-interactions/src/utils/getChildren.ts
packages/react-dom-interactions/test/unit/getAncestors.test.ts
packages/react-dom-interactions/test/unit/getChildren.test.ts
packages/react-dom-interactions/test/visual/components/Menu.tsx

As a benefit, nested dropdown menus now no longer need to block sibling list items' `pointer-events`. This assumes something else is not controlling document.body's `pointer-events` style
Closes #1722

fix(useHover): block `pointer-events` when using safePolygon

---

packages/react-dom-interactions/src/hooks/useHover.ts

#1694 seemed to break the logic in React 17. Couldn't tell as the playgrounds are on React 18, and it works even without StrictMode. Seems like `mouseleave` instead of `pointerleave` works in both versions 🤷‍♂️

fix(safePolygon): failing in React <18

---

.config/tsconfig.json

Without the explicit return type, the built TS definitions say that the return is always HTMLElement, which is not correct:
```ts
export declare const useFloatingPortalNode: ({ id, enabled, }?: {
id?: string;
enabled?: boolean;
}) => HTMLElement;
```
After this, the return type also includes `null`, as is correct.
An alternative solution would be to set `"strict": true` in tsconfig, then the null is added by TS - that might be the better solution overall, as it would add the missing nulls to other potential places as well, but it might also create more churn for users who haven't dealt with nulls..

fix: correct return type for useFloatingPortalNode

---

packages/core/src/computePosition.ts

Instead of defaulting to an infinite loop in prod, it's better to just use whatever's ready after 50 iterations, even if a `reset` is being requested. It appears in some scenarios, `size` and `flip` together can cause a loop depending on the styles. I have not yet figured out why but it was brought up in https://github.com/shoelace-style/shoelace/issues/777
This is also the case in Popper 2, where in DEV, it threw an error, but it's possible not to even discover it while developing because it requires a specific configuration. Plus, it's hard for non-dev users to debug.  
Therefore, it should just use whatever is ready after 50 iterations

fix(core): add a safeguard return after 50 iterations

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useClick.ts
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useFocus.ts
packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/src/safePolygon.ts
packages/react-dom-interactions/src/types.ts
packages/react-dom-interactions/src/useFloating.ts

Closes #1659 
Now the user can call `reference()` and pass a virtual element, which changes `refs.reference.current`, but the DOM node will still be available under `refs.domReference.current`. This allows a "split" between a virtual element (positioning) and a real DOM reference element (events)

fix: use DOM reference in place of refs.reference

---

packages/dom/src/autoUpdate.ts

Avoids putting the initial update in a microtask as this causes a timing problem with focus calls

fix(autoUpdate): avoid initial update in microtask

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useClick.ts
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/test/unit/useListNavigation.test.tsx

Working on #1758 trying to create the select that worked well on touch + mouse, these issues arose
- All return focus to reference calls are now exclusively handled by `FloatingFocusManager` to bypass isuses with unmounting animations tested with `framer-motion`. Previously pressing `esc` meant the user could open the floating element while it was still transitioning out and this caused the focus trap to fail. Now it waits for the animation to finish so the bug is gone.
- `lockScroll` on iOS and touch in general is poor for non fullscreen modal/dialogs, and the `mousedown` event used in `useDismiss` is now `pointerdown` to instantly dismiss the floating element while attempting to scroll.
- Conversely, the `pointerdown` event in `useClick` is now `mousedown` because it was 1) too easy to …

fix(react-dom-interactions): various tweaks

---

packages/react-dom-interactions/src/FloatingOverlay.tsx
packages/react-dom-interactions/src/index.ts
packages/react-dom-interactions/src/inner.ts
packages/react-dom-interactions/src/utils/getPlatform.ts
packages/react-dom-interactions/test/visual/components/MacSelect.css
packages/react-dom-interactions/test/visual/components/MacSelect.tsx
packages/react-dom-interactions/test/visual/index.tsx

Closes #1580
This adds a generic abstraction required to create a macOS-style `<select>` where an item inside of the floating element is anchored to the reference element (upon opening, the item sits on top of it). 
It's not as simple as using the `offset` middleware and calculating the `.offsetTop` of the inner item. This is because if the select menu is moderately large, it will overflow the boundary. It needs to limit its height on the top and bottom but also expand the maxHeight when scrolling in case the reference element is near the boundary, the small "viewport" caused by the initial alignment results in suboptimal UX otherwise. 
All of this requires pretty complex logic and an interaction hook. It's also not really possible to make it agnostic to the DOM, so for this it's only …

feat: `inner` + `useInnerOffset`

---

packages/react-dom-interactions/src/hooks/useHover.ts

Closes #1789 
`pointer-events` logic was being incorrectly skipped in this case

fix(useHover): SVG reference element

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/test/unit/FloatingFocusManager.test.tsx

Closes #1795 
The scrolling after focus problem isn't an issue for nested floating elements

fix(useDismiss): return focus to reference on outside pointerdown for nested elements

---

website/pages/docs/getting-started.mdx
website/pages/index.js

unpkg is unmaintained and [full of issues](https://github.com/mjackson/unpkg/issues). I switched the documentation over to [jsDelivr](https://www.jsdelivr.com/) since it's actively maintained and is much more reliable due to its [fallback system](https://www.jsdelivr.com/network/infographic) using multiple CDNs.
Likewise, Skypack is also [unmaintained](https://github.com/skypackjs/skypack-cdn/issues), so that was switched over to [esm.run](https://www.jsdelivr.com/esm), which is still part of the jsDelivr network.
Let me know if there are any concerns!

docs: switch cdns to jsdelivr

---

packages/core/src/middleware/arrow.ts
packages/core/src/middleware/shift.ts
packages/core/src/middleware/size.ts
packages/dom/test/visual/spec/Shift.tsx
packages/react-dom-interactions/package.json
packages/react-dom-interactions/rollup.config.js
packages/react-dom/package.json
packages/react-dom/rollup.config.js
packages/react-dom/src/useFloating.ts
packages/react-native/src/index.ts

Closes #1538
This will bump the following packages to v1:
- `core`
- `dom`
- `react-dom`
Following will remain v0 (but will use these packages):
- `react-native`
- `react-dom-interactions`
- [Core] `arrow.ts` file just didn't have Prettier applied properly
- [Core] `size()` `apply` has `await` before it (closes #1766)
- [React DOM] allow unstable inline ref callbacks (found a solution to this)
- [React] Add `name` check for middleware comparisons
- [React] Remove `use-isomorphic-layout-effect` from installed deps (as it's bundled in and tiny, anyway)
- [Core] `limitShift()` `offset` option gets passed `MiddlewareArguments` signature to be consistent with other APIs
- [React] Add `.umd` to UMD package files

Floating UI v1

---

packages/react-dom-interactions/src/hooks/useHover.ts

`pointer-events` should be cleared:
- When the cursor leaves the polygon (and floating element)
- When the `enabled` state changes
Closes #1807, #1806 
@mihkeleidast

fix(useHover): `pointer-events` clearing

---

packages/react-dom-interactions/src/hooks/useHover.ts

In most cases, you want a `mousemove` to work on hover, for example `useListNavigation` uses `onMouseMove` to synchronize focus on hover. There are possibly some components where this is not desirable (found on Radix PR).

feat(useHover): `move` prop

---

packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/test/unit/useListNavigation.test.tsx
packages/react-dom-interactions/test/visual/components/EmojiPicker.css
packages/react-dom-interactions/test/visual/components/EmojiPicker.tsx
packages/react-dom-interactions/test/visual/components/Grid.tsx
packages/react-dom-interactions/test/visual/index.tsx

Closes #1695 
By specifying `cols` the navigation enters grid mode. Most common use is `horizontal` orientation, but with `both` orientation, it can lock itself to a row or column without moving to the next one.

feat(useListNavigation): Grid navigation

---

packages/react-dom-interactions/src/hooks/useRole.ts

`aria-haspopup` doesn't include this in the types, but can be replaced by `dialog` as the popup, and the role will still be `alertdialog` on the floating element.

feat(useRole): allow `alertdialog`

---

packages/react-dom-interactions/src/hooks/useHover.ts

Prevent continually clearing `delay`s.

fix(useHover): add `once` back to mousemove listener

---

packages/react-dom-interactions/src/hooks/useHover.ts

When `move: false`, Firefox seems to have an issue on the first open for whatever reason

fix(useHover): remove open check

---

packages/react-dom-interactions/src/FloatingDelayGroup.tsx
packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/src/useFloating.ts
packages/react-dom-interactions/src/utils/useEvent.ts

Internal polyfill for proposed `useEvent` hook, adapted from Ariakit. Far nicer for functions compared to `useLatestRef`
Plus, now users can pass an unstable `onOpenChange` callback without breaking the memoization of the returned object from `useFloating()`.

refactor: `useEvent` hook

---

package-lock.json
packages/react-dom-interactions/package.json
packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useTypeahead.ts
packages/react-dom-interactions/src/utils/getTarget.ts
packages/react-dom-interactions/test/unit/useTypeahead.test.tsx

- If the capslock key is on, the default `findMatch` did not match correctly.
- If a nested floating element is not portalled, but focus is inside the nested floating element, it can still match parent items. This uses the `role` in order to scope, maybe there is a better way

fix(useTypeahead): scoping and capslock

---

packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/types.ts
packages/react-dom-interactions/src/useFloating.ts
packages/react-dom-interactions/test/unit/useHover.test.tsx

Closes #1833. Unfortunately causes 1 more re-render due to the state change, but this effect needs to have it as a dependency. Other hooks are not affected as they use regular event handlers. It is just placed under a private `_` variable in the context

fix(useHover): allow conditionally rendered reference element

---

packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/test/unit/useDismiss.test.tsx

Closes #1828 
Context on how the fix works: https://github.com/adazzle/react-data-grid/pull/1417/files#diff-fdcbe490b776c1eed24c88d4b5f27d66R4

fix(useDismiss): `outsidePointerDown` with portaled children

---

packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/safePolygon.ts

Since #1811 is stalled, and maybe doesn't have a good fix, this option is much cleaner for disabling the `pointer-events` blocking behavior without needing the useLayoutEffect workaround.

feat(safePolygon): add `blockPointerEvents` option

---

packages/react-dom-interactions/src/useInteractions.ts
packages/react-dom-interactions/test/unit/useInteractions.test.ts

TS forbids passing custom props through `get{X}Props` but plain JS doesn't know this
Closes #1860

fix(useInteractions): props starting with `on`

---

packages/react-dom-interactions/src/hooks/useClick.ts

The current implementation of `useClick` bails on keyDown/Up handlers on button targets to avoid redundant handling of float state because pressing ENTER/SPACE on buttons trigger a click event. However, checking if the reference element is a button causes it to incorrectly bail on the wrong element type when an event is triggered by an element that is not the reference element. 
Instead, one possible solution is to check if the target that triggered the event is a button regardless of the type of the wrapping reference.
[Here](https://codesandbox.io/s/serene-noether-bqk39m?file=/src/App.tsx)'s a reproduction of the issue.

fix(useClick) ensure correct handling of events for wrapped buttons

---

packages/react-dom-interactions/package.json
packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/hooks/useClick.ts
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/test/unit/useClick.test.tsx
packages/react-dom-interactions/test/unit/useDismiss.test.tsx
packages/react-dom-interactions/test/unit/useFocus.test.tsx
packages/react-dom-interactions/test/visual/components/MacSelect.tsx
packages/react-dom-interactions/test/visual/components/Menu.tsx

This allows the user to configure the events for `useClick` and `useDismiss` and avoids the `pointerDown` terminology
Closes #1879 
- `outsidePointerDown` => `outsidePress`
- `outsidePressEvent: string`
- `referencePointerDown` => `referencePress`
- `referencePressEvent: string`
`pointerdown` (default)
When you want to dismiss on both mouse/touch **eagerly**
`mousedown`
When you want to dismiss eagerly with mouse but lazily with touch
`click`
When you want to dismiss on both mouse/touch **lazily**
After discovering it's poor UX to use `pointerdown` instead of `mousedown` on touch devices this was changed. So now the option doesn't match what it is doing.
`pointerDown` => `event: 'click' | 'mousedown'`

feat: configure events

---

packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/test/unit/FloatingFocusManager.test.tsx
packages/react-dom-interactions/test/visual/components/MacSelect.tsx
packages/react-dom-interactions/test/visual/components/Menu.tsx

This prop has confused users and is better replaced with the following technique:
- Use `tabIndex={-1}` on all focusable/tabbable items when using a modal FocusManager. `useListNavigation()` will handle the focus management, instead of the `Tab` key.
- For nested menus, set `returnFocus={!nested}`, so focus only returns to the root reference, preventing unwanted focus when using mouse input.

refactor: remove `preventTabbing` prop

---

packages/dom/index.test-d.ts
packages/dom/src/index.ts
packages/dom/src/types.ts
packages/dom/src/utils/getOffsetParent.ts

Kinda felt this was going to happen, this is causing poor performance as noted in here: https://github.com/shoelace-style/shoelace/discussions/902#discussioncomment-3607642
Going to revert this for now, unfortunately there's no fast native `composedOffsetParent()` to use and this polyfill is slow.
Users will have to:
- Simply avoid using the DOM layout that causes issues, or;
- This PR exports `platform` from the `dom` package, so they can spread in the other methods and only rewrite `getOffsetParent` to include this polyfill themselves without needing `patch-package`. If this is necessary for React DOM it can also be added

perf: revert offsetParent polyfill

---

packages/dom/src/utils/is.ts
packages/dom/test/unit/getOverflowAncestors.test.ts

[dom] Do not treat elements with display: inline or display: contents as overflow ancestors

---

packages/dom/src/autoUpdate.ts
packages/dom/src/utils/is.ts

When using a [Virtual Elements](https://floating-ui.com/docs/virtual-elements) and `contextElement` property, event listeners are not added to its ansectors.

fix: virtual contextElement ancestors overflow

---

website/pages/index.js

The mobile layout for the cards had a border-radius large when in mobile view, which makes it looks odd.

update: border radius when in mobile layout

---

package-lock.json
packages/react-dom-interactions/package.json
packages/react-dom-interactions/src/FloatingFocusManager.tsx
packages/react-dom-interactions/src/FloatingPortal.tsx
packages/react-dom-interactions/src/hooks/useListNavigation.ts
packages/react-dom-interactions/src/utils/FocusGuard.tsx
packages/react-dom-interactions/test/unit/FloatingFocusManager.test.tsx

WIP
Currently when using `modal={false}` in the `FloatingFocusManager`, you cannot also use `<FloatingPortal>` - this PR changes this to ensure DOM focus doesn't lose context despite the portal
Also changes:
- If `relatedTarget` is null, don't close the floating element (e.g. focusing DevTools or outside)
- Remove `endGuard` in favor of `guards` which allows the user to escape at the end or start like a native dialog, and it doesn't need to be at the end of the document
- `tabbable` library supports shadow DOM now and is more robust, switching to it

feat: allow non-modal portalling

---

src/utils/userAgent.js

We have thousands of errors a day caused by `navigator.userAgentData.brands` not being an array. This PR aims to fix that.

Fix error with user-agent brand not being an array

---

packages/dom/src/platform.ts

Forgot about how useful `this` keyword could be...
Closes #1962

fix(platform): `getElementRects` decoupling

---

website/pages/index.js

Fix link color of "open collective" on website index page 

---

packages/react-dom-interactions/src/FloatingTree.tsx
packages/react-dom-interactions/src/hooks/useDismiss.ts
packages/react-dom-interactions/test/unit/useDismiss.test.tsx

Closes #1982  @hornta
This provides two mechanisms for allowing "outside press" to be ignored with certain floating tree structures, the most common being toasts that are rendered on top of a floating element, outside of its React tree.
When the toast is rendered over the top of the modal and it is pressed, we don't want the modal to close:
```jsx
<Modal />
<Toast />
```
Option 1 is adding an attribute, or any selector/identifier to the toast:
```js
<div className="toast" />
```
Then in `useDismiss`, enable the option, but with a guard that cancels the outsidePress dismissal when pressing a toast:
```js
useDismiss(context, {
outsidePress: (event) => !event.target.closest('.toast'),
});
```
Second option is the ability to specify a custom parentId when registering a nodeId, bypassing the …

feat: support non-React tree hierarchy for outside presses

---

packages/react-dom-interactions/src/hooks/useHover.ts
packages/react-dom-interactions/src/safePolygon.ts

Firefox seemed a bit flakey in certain cases with this event while `mousemove` works flawlessly.

fix(useHover): switch to mousemove event

---

packages/react-dom-interactions/src/types.ts

I'm attempting to create a hook similarly to [the official Popover example](https://codesandbox.io/s/distracted-swirles-jo1pvu?file=/src/Popover.tsx:1684-1933) and passing the return type of that to be the context type. Building such a lib with TS (through rollup in my case) fails with an error:
> [!] (plugin typescript) Error: @rollup/plugin-typescript TS4023: Exported variable 'useDrawer' has or is using name 'ExtendedRefs' from external module "node_modules/@floating-ui/react-dom-interactions/src/types" but cannot be named.
I think it needs to translate that `typeof useDrawer` type to something real, since consuming applications don't have that information, so it needs to access the actual type. Hacking in node_modules and adding the export helped my build, I guess this is fairly safe …

fix: export ExtendedRefs type

---

packages/react-dom-interactions/src/FloatingPortal.tsx

Right now changing `guards={false}` breaks if using a FloatingPortal unless setting `preserveTabOrder={false}` on it (which shouldn't be necessary)

fix(FloatingPortal): guards prop

---

packages/react-dom-interactions/src/hooks/useDismiss.ts

Closes #2008 
- Small change in behavior: this makes `outsidePress` non-reactive, so if they change the value while the floating element is open it won't re-register the listeners. Doubt this matters.

fix(useDismiss): ensure `outsidePress` referential stability

---

packages/react-native/src/index.ts

This PR avoids some cases where using `useFloating` causing `Please report: Excessive number of pending callbacks: 501.` in some cases.

fix(react-native): avoid queuing update if already queued

---

packages/react-dom-interactions/src/hooks/useDismiss.ts

Follow-up to #2010 that fixes #2021. If I understand what useEvent does and how it's used in other places, it's to make such function props more stable. Using that, we can conditionally use either the reactive boolean directly, or the stabilized function prop via useEvent.

fix(useDismiss): make outsidePress reactive again

---

packages/dom/src/index.ts
packages/dom/src/types.ts
packages/dom/src/utils/cache.ts
packages/dom/src/utils/getClippingRect.ts

Using a global cache is problematic due to the async function if you call `computePosition()` one after the other.
```js
computePosition(a, b).then(() => ...);
// Uses `a` / `b`'s cache, because it hasn't evicted
// the cache yet
computePosition(c, d).then(() => ...);
```

fix(dom): use local cache

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/hooks/useDismiss.ts
packages/react/src/hooks/useHover.ts
packages/react/test/unit/FloatingFocusManager.test.tsx
packages/react/test/visual/components/Navigation.tsx

Another fix for hover-openable, but focus managed floating elements. The test is a bit weird perhaps, but the real problem we ran into was that when clicking the subnavigation links, then unhovering the floating element, it did not close, as would be expected. This happened because `FloatingFocusManager ` was not aware that in that scenario it should not return focus to the reference (which re-opened the floating element again).

fix: close when unhovering focus managed floating element

---

packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx

Given a nested Popover pattern ([example](https://codesandbox.io/s/goofy-sunset-pplzyj?file=/src/Popover.tsx)), it is generally preferred to disable escape key close bubbling, as that is considered an explicit request to close the immediate open dialog (you say as much in the docs, I believe). However, the current `bubbles` flag also disabled bubbling of the outside press event. This seems counterintuitive for mouse users - if I intentionally click outside both of the open Popovers, I'd expect both of them to close as well. Currently, when disabling bubbling, it also necessitates multiple outside clicks, one for each level of open Popovers.
~~It seems like a good idea to allow configuring this for both events separately. I currently added a `outsidePressBubbles` option that inherits from …

feat(useDismiss): allow specifying different value for outside press bubbling and escape key bubbling

---

packages/react/src/components/FloatingDelayGroup.tsx

Sets the default delay in the delay group context to 0, which is the same default delay used by `useHover`.
I was a bit surprised today that all my Tooltips got a delay after implementing the opt-in support for the delay group functionality. That is - I added the `useDelayGroupContext` and `useDelayGroup` hooks to my component, and I expect the delay group provider itself to be added as some outer wrapper, which I think is the expected implementation.
I think these should be 0, as in no delay, otherwise I don't understand how to default to 0. If one needs a different default delay, that's easier to implement in the custom Tooltip component that uses the hooks.

fix(FloatingDelayGroup): default delay in context

---

packages/core/src/middleware/hide.ts

This middleware is missing `options` returned on the object, so it can't be updated either conditionally with state, or via Fast Refresh.

fix(hide): return options on object

---

packages/react/index.test-d.tsx
packages/react/src/hooks/useMergeRefs.ts
packages/react/src/index.ts
packages/react/test/unit/useMergeRefs.test.tsx

The reusable component examples currently require an external lib, and by default it doesn't memo the value - a dedicated hook should be exported from the package to use.

feat(react): `useMergeRefs` hook

---

packages/react/src/hooks/useListNavigation.ts

By default this hook should handle overflowing containers with a good default (`nearest`). This only applies when using a keyboard, and ignored if a pointer is being used, and can be disabled entirely when set to `false`

feat(useListNavigation): `scrollIntoView` option

---

packages/react/src/types.ts
packages/react/src/useFloating.ts
packages/react/test/unit/useFloating.test.tsx

Closes #1991
Right now to use a custom position reference, you call `reference()` _after_  it has set the DOM reference (e.g. in an effect), but if the `ref` prop is not stable, such as with an external library, this means it can overwrite the virtual element and is generally not reliable.
This returns a new callback ref, `positionReference` for this purpose. It can accept either a real element or a virtual element. Under the hood it normalizes it into a virtual element.
If `positionReference` isn't used, then `reference` is used as both the position and events reference as expected.
```js
const {reference, positionReference} = useFloating();
return <>
<div ref={reference} />
<div ref={positionReference} />
</>;
```
When both are used:
- `refs.reference.current === positionReference`
- …

feat: `positionReference` callback ref

---

packages/react/src/components/FloatingDelayGroup.tsx
packages/react/test/unit/FloatingDelayGroup.test.tsx

I saw this pattern in the wild yesterday. If there's no close delay, you might still want the delays to end up grouped even if none of the tooltips are currently open within a certain period of time. Instead of relying on the close delay, you can instead rely on the `timeoutMs` prop. This also helps with unmounting animations if you want to allow it to be interruptible and continue grouping even if there is a close delay, e.g. `timeoutMs = closeDelayMs + animationDurationMs`

feat(FloatingDelayGroup): `timeoutMs` prop

---

packages/react/src/components/FloatingFocusManager.tsx

Fixes #2039
I'm not sure if focus hitting a guard shouldn't ever be considered "unrelated" @mihkeleidast

fix(FloatingFocusManager): always consider focus guards as related targets

---

packages/react/src/hooks/useHover.ts
packages/react/src/safePolygon.ts
packages/react/test/unit/useInteractions.test.tsx

Supersedes #1814 
Fixes #1811
Bypassing React's DOM rendering fixes the issue in Firefox

fix(safePolygon): use real polygon to block pointer events

---

packages/dom/src/utils/is.ts

Relatively new CSS value for `overflow`. Also, remove the `overflow` check because it's `{x} {y}` and is redundant to check.

fix(isOverflowElement): check for `clip` value

---

packages/react-dom/index.test-d.tsx
packages/react-dom/src/types.ts
packages/react-dom/src/useFloating.ts
packages/react/src/types.ts
packages/react/src/useFloating.ts

Right now, the only fully reliable way to ensure the position is ready during an effect is to use `requestAnimationFrame` to prevent unwanted scrolling to the top/left of the document (due to the floating element's initial layout):
```js
useLayoutEffect(() => {
open && requestAnimationFrame(() => el.focus());
}, [open]);
```
(I know `preventScroll` exists, but it's not very widely supported).
This feels kind of like a hack and can cause some issues, so I am proposing the following:
```js
const [open, setOpen] = useState(false);
const {isPositioned} = useFloating({
// if false, resets the state
open,
});
useLayoutEffect(() => {
isPositioned && el.focus();
}, [isPositioned]);
```
The `open` option allows you to subscribe to resets, where `false` will cause a reset. This plays nicely with …

feat(react-dom): `open` option & `isPositioned` return value

---

packages/core/src/middleware/autoPlacement.ts

Fixes #2072
If the user doesn't explicitly specify `alignment`, then we should always respect the `allowedPlacements` that get passed in. If they do, then it should filter out unsupported placements as before.

fix(autoPlacement): preserve explicit `allowedPlacements`

---

packages/core/src/middleware/arrow.ts
packages/core/src/middleware/autoPlacement.ts
packages/core/src/middleware/flip.ts
packages/core/src/middleware/inline.ts
packages/core/src/middleware/shift.ts
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingOverlay.tsx
packages/react/src/components/FloatingTree.tsx
packages/react/src/hooks/useDismiss.ts
packages/react/src/hooks/useFocus.ts
packages/react/src/hooks/useId.ts
packages/react/src/hooks/useTypeahead.ts
packages/react/src/inner.ts
packages/react/src/utils/getChildren.ts
packages/react/src/utils/getDocument.ts
packages/react/src/utils/is.ts
packages/react/src/utils/tabbable.ts

In each of these places it has no benefit over `||` but transpiles to something much larger, so this just reduces the bundle size cost of the operator.

refactor: replace nullish coalescing where possible

---

packages/react-dom/src/useFloating.ts
packages/react-dom/test/index.test.tsx

Fixes #2086 
The `deepEqual` check no longer worked because of the new `isPositioned` value

fix(react-dom): re-allow unstable ref callbacks

---

packages/react/src/useFloating.ts

Fixes #2091 - only the first update worked following the change, this allows it to update at any time

fix(react): backwards-compat for virtual element separation

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

The focus guard in FloatingPortal still tries to close the floating element on focus out, even if `closeOnFocusOut={false}` is set on FloatingFocusManager. I think the context was meant for passing the values from FloatingFocusManager to FloatingPortal for scenarios like this, so reused it.
LMK if a test is necessary for this.

fix: account for closeOnFocusOut in FloatingPortal

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/hooks/useClick.ts

Found two edge cases with sync return focus:
1. Click-toggling the reference element caused the focus ring to now appear for pointer usage (happens with `mousedown` click event, and if nothing else was focused prior)
2. Calling `setOpen(false)` in an `onKeyDown` listener now requires `event.preventDefault()` in the listener, but used to not.
Neither seem testable in JSDOM

fix(FloatingFocusManager): handle sync return focus edge cases

---

packages/react-dom/src/index.ts
packages/react-dom/src/types.ts
packages/react/src/index.ts
packages/react/src/types.ts

Fixes #2110 @hpaul
This avoids the `useFloating` collision in `@floating-ui/react` and the `arrow` collision in both `react-dom` and `react`

fix: avoid export collisions

---

packages/react/src/safePolygon.ts

In some scenarios the polygon can overlap the floating element, so the contains check fails. By checking the rects we can destroy the polygon despite the pointer events being blocked

fix(safePolygon): destroy polygon if over floating rect

---

packages/react/src/components/FloatingDelayGroup.tsx
packages/react/test/unit/FloatingDelayGroup.test.tsx

This was such a weird oversight, I have no idea how I missed this simplification.
As for internalizing it into `useHover` per your suggestion, we can try to work out API simplifications for the v1 release later to require less importing. For now it'd be good to prevent breaking too many things
@mihkeleidast
Also the tests pass with and without changing the test, so it's backwards-compatible.

fix(FloatingDelayGroup): simplify usage by syncing current id internally

---

packages/react/src/components/FloatingDelayGroup.tsx
packages/react/src/hooks/useTransition.ts
packages/react/test/visual/components/Tooltip.tsx

This allows you to make a transition/animation faster while the open delay is in the instant phase. 
The technique that works for `framer-motion` in the existing CodeSandbox doesn't work with the `useTransition<X>` hooks, but this boolean works with both.
Usage:
```js
const {isInstantPhase} = useDelayGroupContext();
const instantDuration = 0;
const openDuration = 500;
const closeDuration = 200;
const {isMounted, styles} = useTransitionStyles(context, {
duration: isInstantPhase
? {
open: instantDuration,
close: currentId === label ? closeDuration : instantDuration,
}
: {
open: openDuration,
close: closeDuration,
},
});
```

feat(useDelayGroupContext): `isInstantPhase` bool

---

packages/react/src/hooks/useClick.ts
packages/react/src/hooks/useFocus.ts
packages/react/src/hooks/useListNavigation.ts
packages/react/src/hooks/useTransition.ts
packages/react/test/unit/useFloating.test.tsx

Prevents `setState` loops when placing `getFloatingProps` as a dependency of a hook and the `ref` setter is inside. 
Fixes #2129

fix(react): avoid adding `floating` element to interaction props dependency array

---

packages/react/src/hooks/useListNavigation.ts
packages/react/src/useInteractions.ts

The `reference` and `floating` keys can't be memoized like the `item` one due to `onNavigate(null)` in `onPointerLeave`, so only the `item` deps are granularly checked as it doesn't depend on `activeIndex`. 
Only the item getter is usually the one that needs memo'ing because it can affect a large number of components, and this reduces re-renders of the items in the Select example when hovering fast by 90%.
Fixes #2144 by allowing this to work by default:
```js
const ListItem = React.memo(function ListItem({active, getItemProps}) {
// This component will NOT be-rendered unless the `active` prop changes 
// (i.e. matches the activeIndex)
return <div {...getItemProps()} />;
});
```

perf: make `getItemProps` change less frequently

---

packages/dom/src/types.ts
packages/dom/src/utils/getDimensions.ts
packages/react-dom/src/arrow.ts

SVG arrows were working prior to `dom@1.1.0`, but the types didn't allow it - this adds explicit support for it in the types and makes it work again
Closes #2137

refactor: allow SVG elements as the arrow

---

packages/react/src/hooks/useHover.ts
packages/react/src/safePolygon.ts
packages/react/test/unit/useInteractions.test.tsx

Fixes #2124
This reverts the polygon technique and goes back to the old `pointer-events` blocking technique. This does have side-effects, so I'm going to prominently display a warning about how to disable it and how to work around these side-effects. 
This PR adds an attribute to the `<body>` called `data-floating-ui-safe-polygon` which allows the user to target it in their CSS.
Both these two issues for scrolling containers (not the main `window`):
- Not being able to scroll while the cursor rests over the reference element while the floating element is open
- macOS' auto-hiding scrollbars forcefully appearing in Chrome
Can be solved like this:
```js
function ScrollContainer({children}) {
return (
<div data-scroll>
<div>
{children}
</div>
</div>
);
}
```
```css …
```

fix(safePolygon): use `pointer-events` blocking

---

packages/react/src/index.ts
packages/react/src/types.ts

Move imports and exports from `@floating-ui/dom` to `@floating-ui/react-dom` in package `@floating-ui/react` to resolve dependency issue.

---

packages/dom/src/types.ts
packages/dom/src/utils/getOffsetParent.ts

This enables the ability to add a `composedOffsetParent` polyfill, which can also be used conditionally when perf problems arise.
```js
function getWindow(node) {
return node.ownerDocument?.defaultView || window;
}
function isShadowRoot(node) {
return node instanceof getWindow(node).ShadowRoot;
}
/**
* Polyfills the old offsetParent behavior from before the spec was changed:
* https://github.com/w3c/csswg-drafts/issues/159
*/
function composedOffsetParent(element) {
let {offsetParent} = element;
let ancestor = element;
let foundInsideSlot = false;
while (ancestor && ancestor !== offsetParent) {
const {assignedSlot} = ancestor;
if (assignedSlot) {
let newOffsetParent = assignedSlot.offsetParent;
if (getComputedStyle(assignedSlot).display === 'contents') {
const hadStyleAttribute = …
```

feat(dom): add ability to polyfill `offsetParent` access

---

packages/core/src/middleware/flip.ts
packages/core/src/middleware/size.ts

The `crossAxis` of `size()`, i.e. the y-axis for left/right placements, or x-axis for top/bottom placements poses some problems.
For center aligned placements, this PR considers whole viewport space when `shift()` appears before `size()`, which fixes #1897.
For edge aligned placements (`start` / `end`), I found the following:
- It's not desirable to use `shift()` **before** `size()`, because then the placement loses its alignment. Placing it after works fine with desirable behavior. Perhaps should be documented.
- When using `flip()`, which is much more useful, it "resets" at a point when it overflows on both sides, which looks like it was caused by https://github.com/floating-ui/floating-ui/pull/2151. Will try to include a fix for that in this PR also.

fix(size): take into account `shift()` for center aligned placements

---

packages/core/src/detectOverflow.ts
packages/core/src/types.ts
packages/dom/src/types.ts
packages/dom/src/utils/getBoundingClientRect.ts
packages/dom/src/utils/getClippingRect.ts
packages/dom/src/utils/getViewportRect.ts
packages/dom/src/utils/is.ts

Closes #2084
This enables "virtual" boundaries, and applies to both `boundary` and `rootBoundary` options.  Useful for more than just the linked issue though.
So if you wanted to use the layout viewport rather than the visual viewport, you could do:
```js
detectOverflow(args, {
rootBoundary: {
x: 0,
y: 0,
width: document.documentElement.clientWidth,
height: document.documentElement.clientHeight,
}
});
```
I think it's best to keep the default `viewport` `rootBoundary` if the visual viewport and layout viewport dimensions aren't the same upon first render of a floating element.  This heuristic isn't perfect, but this way it will correctly re-adjust its position when pinch-zooming out if it was flipped or shifted initially when opening, while preventing it from changing position while …

feat(detectOverflow): accept virtual `Rect` boundaries

---

packages/dom/src/utils/getClippingRect.ts

fixes #2167
Previously ancestors with `transform` values and interceding decendents with `position: fixed` would errantly count as clipping ancestors. This releases the styles of a `position: fixed` ancestor so that it doesn't allow the `transform` ancestor to join the clipping ancestors array.
Repro in previous context: https://codesandbox.io/s/youthful-wiles-dc6oy4?file=/index.html

Prevent fixed ancestors from being a clipping ancestor

---

packages/core/src/detectOverflow.ts
packages/core/src/middleware/arrow.ts
packages/core/src/middleware/autoPlacement.ts
packages/core/src/middleware/flip.ts
packages/core/src/middleware/hide.ts
packages/core/src/middleware/inline.ts
packages/core/src/middleware/offset.ts
packages/core/src/middleware/shift.ts
packages/core/src/middleware/size.ts
packages/core/src/types.ts
packages/dom/src/autoUpdate.ts
packages/dom/src/types.ts
packages/react-dom/src/arrow.ts
packages/react-dom/src/types.ts
packages/react-native/src/types.ts
packages/react/src/inner.ts
packages/react/src/types.ts
packages/vue/src/types.ts

Several issues:
- Middleware option types weren't being re-exported from dependent packages (fixes #2169)
- Some of the comments were outdated, not descriptive, or not matching the wrapped types correctly
- Some of the wrapped DOM types look bad when hovering over types, I used the [`Prettify` util found here](https://twitter.com/mattpocockuk/status/1622730173446557697)
- `MiddlewareArguments` has been deprecated in favor of `MiddlewareState` as it's shorter, cleaner, and is more descriptive
- Added `@deprecated` comment to `reference`, `floating`, and `positionReference` values returned from `useFloating`

fix: type exports and comments

---

packages/react/src/hooks/useTransition.ts

Allows `transition-delay` to work on first render

fix(useTransitionStyles): apply initial styles in `unmounted` status

---

packages/core/src/middleware/arrow.ts
packages/react-dom/src/arrow.ts
packages/react/index.test-d.tsx
packages/react/src/components/Arrow.tsx
packages/react/src/components/FloatingArrow.tsx
packages/react/src/index.ts
packages/react/src/types.ts
packages/react/test/visual/components/Arrow.tsx
packages/react/test/visual/index.tsx

Partially solves #2078
This component is designed to be flexible and support the vast majority of use cases.
- **Simple to setup**: it renders out a 14x7px black-filled SVG arrow by default. 
Placing this inside your tooltip will position everything without any styling required:
```js
<FloatingArrow ref={arrowRef} context={context} />
```
- **Customizable width and height (and therefore `angle`)** via `width` and `height` attributes.
- **Rounded tip**: the `tipRadius` prop accepts a number similar to `border-radius`.
- **Borders**: the `stroke`/`strokeWidth` props can add a border to the arrow.
- **Custom shapes**: the `d` prop accepts a custom path string to create more fancy rounding - the docs will have an example that can be edited via Figma or similar
- **Static offsets**: the …

feat(react): `FloatingArrow` component

---

packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx

- https://github.com/floating-ui/floating-ui/discussions/2206
- https://github.com/floating-ui/floating-ui/discussions/2138
The escape key listener is attached to the `document` which prevents propagation from being able to be stopped and requires setting up a `FloatingTree`, which may be impractical for "agnostic" components that compose together like a Dialog and Select.
With this PR, if the reference and floating element have focus inside them, it now uses a keydown listener on the elements and can stop propagation for `esc` dismissal. If focus isn't inside either element, it falls back to the document listener, but in most cases this will fix the issue of agnostic components wanting to stop propagation.
This changes the default for `escapeKey` bubbling to `false`.

refactor(useDismiss): allow preventing bubbling without `FloatingTree`

---

packages/react/src/hooks/useRole.ts
packages/react/src/types.ts
packages/react/src/useFloating.ts
packages/react/test/unit/useRole.test.tsx

Relates to this: https://github.com/floating-ui/floating-ui/issues/2128#issuecomment-1452077329
When an external reference is using its own set of interactions hooks because it needs to configure them differently per reference, they should still use the same floating element ID reference throughout.

fix: share root id via context

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/visual/components/Popover.tsx

We ran into a problem with a Popover that uses the transition hook, the main structure was like this:
```
<Popover id="a">
<Popover id="b">
</Popover>
</Popover>
<Popover id="c">
</Popover>
```
The bug occurred when:
1. open Popover a
2. open nested Popover b
3. open Popover c, which should close both a and b with an outside press
4. but Popover c also closed
Since a and b closed with transition timeouts, the layout effect cleanup function also run with a timeout. This surfaced an issue where in the cleanup function, `returnFocusRef.current` was not `false` anymore, even though it was set to false in the `onDismiss` function. I assume this is because `returnFocusRef` depends on the prop value, and with the transitions, it gets rerendered and reset at some point. I think this is a bug, …

fix(FloatingFocusManager): mutate internal preventReturnFocusRef instead of returnFocusRef

---

packages/dom/src/autoUpdate.ts

fix(dom): don't skip initial RO callback in autoUpdate

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/hooks/useListNavigation.ts
packages/react/test/unit/useListNavigation.test.tsx

Partially solves https://github.com/floating-ui/floating-ui/issues/2235 /cc @Marsony
[`use-descendants@beta`](https://www.npmjs.com/package/use-descendants) (unfortunately unmaintained, but works) allows you to do this:
```js
<Select>
<OptionGroup>
<Option />
<Option />
</OptionGroup>
<OptionGroup>
<Option />
</OptionGroup>
</Select>
```
Where `Option` can read its `index` in the `Select` tree despite the `OptionGroup` wrapper. 
```js
function Option() {
const {listRef} = useSelectContext();
const index = useDescendant();
return (
<div
ref={node => (listRef.current[index] = node)}
/>
);
}
```
However, it causes a state update in a layout effect, and `ArrowDown`/`ArrowUp` on the reference element expects the list to be populated in the same render cycle as the open state changing. This …

fix(useListNavigation): allow scheduled list population

---

packages/react/src/hooks/useDismiss.ts

Fixes #2237 - could also check if the element is scrollable but this seems to fix the issue.

fix(useDismiss): press outside on inline elements in Firefox

---

packages/react/src/useInteractions.ts
packages/react/test/unit/useInteractions.test.tsx

Our usecase for this is that our buttons accept Promise-returning onClick handlers, which put the button to a loading state while the promise resolves. This behavior broke when a button was wrapped with a Tooltip, as the prop merging here did not forward the returned promise.

fix(useInteractions): merging function props that return values

---

packages/core/src/computePosition.ts
packages/core/src/detectOverflow.ts
packages/core/src/middleware/arrow.ts

These worked well in the "webpack era" but now they're annoying and require clarification on the docs. They're also not _that_ useful, and TypeScript and the documentation are good enough for this library imo.
Kept them in React though as the build setup expectation is fine there. I'll do this in Popper as well.
@benmccann

chore: remove dev warnings (process.env) from core/dom packages

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

I suppose this could be configured with initialFocus, but this would seem like an unnecessary configuration to me. I think users would expect autoFocus inside a dialog to just work.

fix(FloatingFocusManager): respect child with autoFocus

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

This might be a weird one. I'm not exactly sure if this sort of usage is supported or not, but it seemed like a bug. The test resembles this a little bit, but not too much. I'll add a bigger backstory in a details panel.
Anyway, I found that the `getChildren` function call in `movedToUnrelatedNode` does not return any children, because it does not think the child is open yet, even though opening the child is what triggered the focusout in the first place. Seems like it is necessary to wait for [this layout effect](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/useFloating.ts#L111-L116) to have run before actually running the check. I'm not sure if the timeout is the best way to do this, however, I'm always reluctant to add such timeouts. Maybe the getChildren …

fix(FloatingFocusManager): wait for tree nodes context to be updated

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

Wraps tabbable query in `queueMicrotask`, found to make #2269 work correctly, moving it into a separate PR

fix(FloatingFocusManager): wait to select tabbable initially focusable items

---

packages/react/src/components/FloatingList.tsx
packages/react/src/index.ts
packages/react/test/unit/FloatingList.test.tsx
packages/react/test/visual/components/Select.tsx

@pierreburel @Marsony
The `sortByDocumentPosition` technique is found in other libs to enable this feature, and this one doesn't write or read any refs during render, so hopefully good for concurrent features.
Usage:
`FloatingList` is a context provider for children
- `elementsRef` is `useListNavigation`'s `listRef`
- `labelsRef` is `useTypeahead`'s `listRef` which uses the `label` passed into `useListItem` or falls back to the node's `textContent`
```js
<FloatingList elementsRef={elementsRef} labelsRef={labelsRef}>
...
</FloatingList>
```
- `useListItem` reads that context and returns an `index` and a `ref`:
```js
const {activeIndex} = useSelectContext();
const {ref, index} = useListItem();
const isActive = activeIndex === index;
// No need to manually assign an index:
<div ref={ref} …
```

feat: `FloatingList`

---

packages/react/src/safePolygon.ts
packages/react/test/visual/components/Menu.tsx

When multiple reference elements lie next to each other and they have hoverable floating elements, the cursor speed is much better at determining if the polygon logic should be active compared to `restMs`.

feat(safePolygon): replace `restMs` with `requireIntent` boolean

---

packages/react/rollup.config.js

[Re #2324] [Fix #2324]
The incorrect bundle name was causing an infinite recursion bug when trying to use the 'useFloating' React hook.

Fix FloatingUIReact UMD build

---

packages/dom/src/utils/getBoundingClientRect.ts
packages/dom/src/utils/getClippingRect.ts
packages/dom/src/utils/getRectRelativeToOffsetParent.ts
packages/dom/src/utils/getVisualOffsets.ts
packages/dom/src/utils/is.ts

Continues #2334
For some reason Safari (since at least 16.1, don't have any older versions) creates a containing block if `will-change: filter` is specified, but not if using `filter: (...)` itself...

fix(isContainingBlock): Safari `will-change` filter

---

package-lock.json
packages/vue/package.json

Due to the `@vue/composition-api` peer dependency, Nuxt 3 users cannot install `@floating-ui/vue` without the `--force` flag. The installation fails with the error:
```sh
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from @floating-ui/vue@1.0.0
npm ERR!     node_modules/@floating-ui/vue
npm ERR!       @floating-ui/vue@"*" from the root project
```
Context: https://github.com/floating-ui/floating-ui/discussions/2339
This configuration of `peerDependencies` is recommended by [`vue-demi`](https://github.com/vueuse/vue-demi#usage). But …

Change `vue-demi` version range and remove `peerDependencies` and `peerDependenciesMeta`

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/hooks/useClick.ts
packages/react/src/hooks/useDismiss.ts
packages/react/src/hooks/useFloating.ts
packages/react/src/hooks/useFocus.ts
packages/react/src/hooks/useHover.ts
packages/react/src/hooks/useListNavigation.ts
packages/react/src/types.ts
packages/react/src/utils/is.ts
packages/react/src/utils/isEventTargetWithin.ts
packages/react/test/unit/useFloating.test.tsx

There have been requests to access the event (https://github.com/floating-ui/floating-ui/issues/2047) inside `onOpenChange`. `dataRef.current.openEvent` does not currently get written before `onOpenChange` is called in all cases, and there's no `close` equivalent.
- `onOpenChange` is called without an event in `FloatingDelayGroup`, so it's optionally passed
-  `onOpenChange` isn't called if the user externally changes state, like `setIsOpen(false)`. In this case I think it makes sense to just react to whatever's needed inside the event where they did that anyway

feat(react): `onOpenChange` event param

---

packages/core/src/middleware/arrow.ts
packages/vue/test/index.test.ts

Fixes #2349 (part 2)
@domidomi does this work well for your case?
Note: a large padding value can cause the floating element's own offset to adjust if needed, as per this PR: https://github.com/floating-ui/floating-ui/pull/1496 - this stops `shift()` from taking action in certain scenarios

fix(arrow): ensure padding total is smaller than floating element dimension

---

packages/dom/src/autoUpdate.ts
packages/dom/test/functional/autoUpdate.test.ts
packages/dom/test/visual/spec/AutoUpdate.tsx

Tests passed for https://github.com/floating-ui/floating-ui/pull/2373 since the useEffect was causing an update when the options changed, but the last refactor prevented the option from actually having an effect.
I couldn't work out a way to prevent the loop without the check breaking afterwards in various ways, so I throttled it to 100ms while the reference is clipped/hidden from view to prevent the CPU from spiking

fix(autoUpdate): `layoutShift` check

---

packages/react/src/hooks/useMergeRefs.ts

The ref can also be undefined, and in this case. And it is equivalent to null. Therefore, the double equals (==) can also filter it.

fix(useMergeRefs): refs could be undefined

---

packages/dom/src/autoUpdate.ts

Might as well add this check now to support testing envs by default

fix(autoUpdate): guard for ResizeObserver existence

---

packages/react/src/hooks/useListNavigation.ts
packages/react/src/utils/is.ts
packages/react/test/setupTests.ts

Skips hidden elements from list navigation. Not sure if checking `offsetParent` is the best solution, feel free to suggest some alternative.
I am building this combobox with a tree popup. When a group is collapsed, the items inside are still rendered in react (because we need to get the label/id data back to the parent component), but hidden via CSS. When they are hidden, they should be skipped by list navigation.

fix(useListNavigation): skip hidden items

---

packages/react/src/hooks/useClick.ts
packages/react/test/unit/useClick.test.tsx

Fixes #2443 
This makes `onOpenChange` fire with `true` onClick even if the `open` state is already `true`, to allow the `dataRef.current.openEvent` to be assigned and allow the mouseleave logic to check for it.

fix: useClick + useHover combo

---

packages/dom/src/utils/getRectRelativeToOffsetParent.ts

Remove duplicate code.
The return value of isHTMLElement(offsetParent) has already been retrieved, so there is no need to compute it again

[core] optimize getRectRelativeToOffsetParent function

---

packages/vue/src/types.ts

arrow middleware in the core package allows `element` to be type `any` and all other methods that operate with it specify type `Element` as well
- [getDimensions](https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/platform/getDimensions.ts#L5)
- [getOffsetParent](https://github.com/floating-ui/floating-ui/blob/eb6c042e42faae7567e717fe10afdd1953375e14/packages/dom/src/platform/getOffsetParent.ts#L48)
changing this type simplifies assigning an arrow ref through [function template refs](https://vuejs.org/guide/essentials/template-refs.html#function-refs) from within a slot
addresses #2451

allows ArrowOptions.element to be MaybeElement<Element>

---

packages/react/src/components/FloatingPortal.tsx

Fixes an issue where the generated .d.ts files have an inline import even though JSX is global.
Without this change, I had to either turn on `skipLibCheck` in my tsconfig or otherwise I get this error:
```
node_modules/@floating-ui/react/src/components/FloatingPortal.d.ts:22:133 - error TS2694: Namespace '"node_modules/@types/react/jsx-runtime"' has no exported member 'JSX'.
22 export declare function FloatingPortal({ children, id, root, preserveTabOrder, }: FloatingPortalProps): import("react/jsx-runtime").JSX.Element;
~~~
Found 1 error in node_modules/@floating-ui/react/src/components/FloatingPortal.d.ts:22
```

Update FloatingPortal.tsx to specify return type

---

packages/react/src/hooks/useHover.ts
packages/react/test/unit/useHover.test.tsx

fix(useHover): cleanup when `domReference` changes

---

packages/react/index.test-d.tsx
packages/react/src/components/FloatingArrow.tsx

Fixes #2483
@mattbrazza I tried a few things with generics but it seems hard with `forwardRef` :\  omitting the refs from the type fixes the problem and the component doesn't need that part of the context anyway

fix(FloatingArrow): allow generic reference type context

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

If `initialFocus={-1}` is not specified on `FloatingFocusManager` while the reference is a `combobox`, then the focus management is considered trappable.
Fixes #2505

fix(FloatingFocusManager): allow trapped comboboxes

---

.changeset/late-falcons-sell.md
packages/utils/dom/src/index.ts
packages/utils/test/getOverflowAncestors.test.ts

Fixes #2518.
When `getOverflowAncestors` reaches the `window` object, it checks whether there is `window.frameElement` and continues traversing up into the iframe's parent.
TODO before this is shippable:
- add tests
- verify usage in `getClippingElementAncestors`. Do we also want to traverse into iframe's parent there?

getOverflowAncestors: traverse into iframe parent

---

.changeset/strong-mayflies-raise.md

The changeset for https://github.com/floating-ui/floating-ui/pull/2535 was meant to be pointed to the `utils` not `dom` package.

chore: changeset for @floating-ui/utils@0.1.2

---

.changeset/blue-seahorses-attend.md
packages/dom/src/platform/getClippingRect.ts
packages/dom/test/visual/spec/IFrame.tsx
packages/utils/dom/src/index.ts

Fixes https://github.com/floating-ui/floating-ui/issues/2552

fix(getOverflowAncestors): avoid traversing iframes for clipping detection

---

.changeset/proud-swans-type.md
packages/core/src/middleware/flip.ts

Fixes https://github.com/floating-ui/floating-ui/issues/2549

fix(flip): skip work if arrow data exists

---

.changeset/clever-seals-carry.md
packages/core/src/middleware/arrow.ts
packages/core/src/middleware/flip.ts
packages/core/src/types.ts

- Adds `alignmentOffset` data if the arrow caused shifting of the floating element. Reduces potential for a breaking change if `arrow()` is placed before `flip()` in middleware arrays (should not be done, but technically worked.)

feat(arrow): `alignmentOffset` data

---

.changeset/dirty-phones-pay.md
packages/react/src/hooks/useFocus.ts
packages/react/test/unit/useDismiss.test.tsx
packages/react/test/unit/useFocus.test.tsx
packages/react/test/visual/components/Omnibox.tsx

This replaces `keyboardOnly` since it better does what should be intended (matching `:focus-visible` selector).
Closes #2574

feat(useFocus): `visibleOnly` option

---

.changeset/six-boxes-decide.md
packages/react/src/hooks/useFocus.ts
packages/utils/react/src/index.ts

Fixes #2575 
This amends `activeElement` function to traverse (allowed) iframe parent documents to find the active element. If it's `null` or the `body`, then it's assumed focus left the page into the chrome/elsewhere, so the blur should be ignored. This should fix local iframe issues while ensuring the floating element doesn't close on blur in other situations unwantedly

fix(useFocus): avoid blur close only on browser page blur

---

.changeset/strong-geckos-shave.md
packages/utils/package.json
packages/utils/react/package.json
packages/utils/react/src/index.ts
packages/utils/react/src/types.ts
packages/utils/rollup.config.mjs

New installs of old versions of `@floating-ui/react` install `^v0.1.x`, so the `/react` path has to be kept in the `utils` package for those versions for now. A separate release will be made to bump utils to `v0.2.x` to prevent this issue later on.
Fixes https://github.com/floating-ui/floating-ui/discussions/2588

fix(utils): restore react path for v0.1.x

---

.changeset/seven-elephants-lay.md
packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx

fixes
- #2345 
- #2594 
In the document capture phase, a main handler is added to `event.target`, and during the "AT_TARGET" phase, the handler is executed to operate the logic that determines `insideReactTree`.

fix(useDismiss): add capture phase option for useDismiss

---

.changeset/twelve-jeans-hope.md
packages/react/src/components/FloatingFocusManager.tsx

fix(FloatingFocusManager): avoid returnFocus if focus moved elsewhere

---

website/pages/docs/getting-started.mdx

Hello Federico and atomiks! 👋🏼😊
Thank you very much for having made popper.js/floating-ui and maintaining them all these years 🙌🏼
I wanted to integrate floating-ui for positioning only (as I use other libraries for interactions) and started reading the documentation on the "Getting Started" page. I thought it'd be better if the Getting Started page already had the positioning-only-package install command, as their difference isn't clear until the user goes to the /docs/react page.
I used the same language found on /docs/react page for consistency.

Clarify the purpose of react-dom and react in getting-started.mdx

---

.changeset/four-lions-rhyme.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

Fixes https://github.com/floating-ui/floating-ui/issues/2607#issuecomment-1805222878
I'm not really sure about this solution, which keeps a rolling window of the last 10 elements that focus can return to.

fix(FloatingFocusManager): return focus to last connected node

---

.changeset/shy-cars-mate.md
.changeset/small-chairs-invite.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/hooks/useInteractions.ts
packages/react/src/hooks/useRole.ts
packages/react/src/types.ts
packages/react/test/unit/FloatingFocusManager.test.tsx
packages/react/test/unit/useRole.test.tsx
packages/react/test/visual/components/Autocomplete.tsx
packages/react/test/visual/components/MacSelect.tsx
packages/react/test/visual/components/Menu.tsx
packages/react/test/visual/components/Select.tsx

`role` gets extended with "component" roles, which are a step above base `aria` roles that also add item roles. Additional props based on these "component roles" are also added to the reference/floating element, if required.
```js
useRole(context, {
role: 'select', // ariaRole === 'listbox'
});
```
The above generates `item` props: `role="option"`,  `aria-selected={boolean}`. These props get generated automatically as long as the call site of `getItemProps()` receives the `active` and `selected` props: `getItemProps({active, selected})`, since these are dependencies of the prop derivation.
Alternative to #2633
Closes #2099

feat(useRole): allow item props

---

package-lock.json
packages/devtools/package.json

Follow up on https://github.com/floating-ui/floating-ui/pull/2667
1. bumps version of `@floating-ui/devtools` from `0.0.1` to `0.0.2`

chore(devtools): bump version to 0.0.2

---

extension/src/types.ts
packages/devtools/package.json
packages/devtools/src/extension/types.ts
packages/devtools/src/utils/references.ts

Fixes https://github.com/floating-ui/floating-ui/issues/2672
1. Stops using `crypto.randomUUID` as it requires a secure `https://` domain to work, instead simply create id's using a counter

bugfix(devtools): stop using crypto.randomUUID

---

.github/actions/typescript/action.yml
extension/package.json
package.json
packages/core/package.json
packages/devtools/package.json
packages/dom/package.json
packages/dom/src/index.ts
packages/dom/src/middleware.ts
packages/dom/test/index.test-d.ts
packages/react-dom/package.json
packages/react-dom/test/index.test-d.tsx
packages/react-native/index.test-d.tsx
packages/react-native/package.json
packages/react-native/tsconfig.json
packages/react-native/tsconfig.lib.json
packages/react-native/tsconfig.test.json
packages/react/package.json
packages/react/test/index.test-d.tsx
packages/utils/package.json
packages/utils/tsconfig.test.json
packages/vue/package.json
pnpm-lock.yaml
turbo.json

Follow up on https://github.com/floating-ui/floating-ui/pull/2677#issuecomment-1874861287
1. adds `typecheck` command to run `tsc -b` for every single package
2. move `*-d.ts{,x}` files to `test` folders to be included in types verification
3. modifies CI gh action to use `pnpm run typecheck` instead of `pnpm run build:api`
4. redeclares middlewares from `core` at `dom` [with more specific types](https://github.com/floating-ui/floating-ui/pull/2687/files#diff-df833d72712902a450cc9e36309797cbe2109bd425ada294461da6229cce1882) (this was mistakenly removed by https://github.com/floating-ui/floating-ui/pull/2677/files#diff-b5f898db2c0f33da655f0da10d2aa08eb272bd34c63b177adb3a2b38157de73f)
Seems like types for the `extension` package stories are having some conflict problems between multiple …

chore: adds typecheck command to verify types of every package

---

packages/react/src/utils/composite.ts
packages/react/test/unit/useListNavigation.test.tsx
packages/react/test/visual/components/Grid.tsx

As @atomiks pointed out [here](https://github.com/floating-ui/floating-ui/pull/2676#issuecomment-1877993338), initial focus with arrow keys was broken on grid navigations after the variable sizes PR.
Turns out `getCellIndexOfCorner` was called with `index` `-1` and it wasn't prepared for that case. Easy fix.
---
However, when I tried to add a test so this doesn't happen again, I found some inconsistent behavior (possibly a bug). 
I added `<style>*:focus { border: 1px solid red !important }</style>` to the page before recording this video of the `Grid` component on commit `359e5e15` (before the variable sizes were introduced).
https://github.com/floating-ui/floating-ui/assets/32175149/2cd066c7-df33-45c0-80f2-7de965a4d1b1
You can see that when spam-clicking button, initial focus usually …

Fix initial keyboard focus on Grid navigation

---

.changeset/olive-carpets-drive.md
packages/react/src/utils.ts

Fix recent Chrome issue brought up in https://github.com/floating-ui/floating-ui/pull/2696
Don't have a solution for https://github.com/floating-ui/floating-ui/issues/2666 yet.

fix(react/utils): cross-browser `isVirtualPointerEvent`

---

config/src/defineRollupConfig.mts
config/src/utils/outputFormat.mts
packages/react-native/rollup.config.mjs

1. instead of adding an [exception for `react-native`](https://github.com/floating-ui/floating-ui/pull/2709/files#diff-c31fa8a50f1125b6d26f4823c1a48ccd99f9b0c0156f3a858dc60d4ac242e5c8L78) package on the config definition, this PR introduces the option of each configuration to [override file output](https://github.com/floating-ui/floating-ui/pull/2709/files#diff-d59b424bf8f159c419e926490be41945ae635cddcdebbe039d62a1fb5bd2358eR21-R23)
Follow up on https://github.com/floating-ui/floating-ui/commit/b340e41139ca7be956bec89576443ab68558f3a1#diff-c31fa8a50f1125b6d26f4823c1a48ccd99f9b0c0156f3a858dc60d4ac242e5c8

chore: modifies `defineRollupConfig` to support custom output file format

---

biome.json
packages/react/biome.json
packages/utils/biome.json

Running the command `pnpm run lint` after `pnpm run prepack` will fail as biome is not properly filtering the distribution folders from `packages/utils` and `packages/react`
1. adds biome configuration file to those packages (react, and utils) including their own specific ignore patterns adn extending the main configuration file

chore: add biome configuration file to react and utils workspace

---

.changeset/thin-mayflies-deliver.md
extension/src/contexts/devtools.tsx
packages/devtools/src/controller.ts

1. communicates to extension once the current selected element is removed from the DOM
2. ensures all errors will be resolved once the current document is inspected
Fixes https://github.com/floating-ui/floating-ui/issues/2726

bugfix: resolve errors once document is inspected

---

extension/public/manifest.json

Manually bumps extension version from 1.2.0 to 1.2.1, this PR should follow after https://github.com/floating-ui/floating-ui/pull/2728

chore(extension): manually bump version

---

biome.json
package.json
packages/react-dom/src/useFloating.ts
packages/react-dom/src/utils/useLatestRef.ts
packages/react/src/components/FloatingDelayGroup.tsx
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingList.tsx
packages/react/src/components/FloatingOverlay.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/components/FloatingTree.tsx
packages/react/src/components/FocusGuard.tsx
packages/react/src/hooks/useClientPoint.ts
packages/react/src/hooks/useFloating.ts
packages/react/src/hooks/useHover.ts
packages/react/src/hooks/useId.ts
packages/react/src/hooks/useListNavigation.ts
packages/react/src/hooks/useTransition.ts
packages/react/src/hooks/useTypeahead.ts
packages/react/src/hooks/utils/useLatestRef.ts
pnpm-lock.yaml
website/package.json

Biome doesn't lint `useLayoutEffect` dependencies when it's from a custom package, but works when it's a different name.
React recently removed the SSR warning with the built-in hook (although this is not relevant for libraries until React 19 is released AND has high usage 🫠 ), hence `modern` (preferable over the traditional `isomorphic` name since effects can't be isomorphic).

refactor: rename to useModernLayoutEffect

---

extension/package.json
pnpm-lock.yaml
website/package.json

Fixes https://github.com/floating-ui/floating-ui/issues/2753
1. renames `build` command from `/website` and `/extension` to `build:website`

chore(meta): renames website build command to avoid conflict

---

.changeset/four-windows-work.md
packages/react/src/hooks/useFocus.ts
packages/react/test/unit/useFocus.test.tsx

This fixes a bug where floating elements are closed when the focus is moved from the reference element to any other element inside the reference or tooltip while the whole thing is rendered inside a shadow root. The issue is that the `relatedTarget` property of the focusOut event points to the shadow root instead of the actually focused element.

Do not close the floating element when focus moves inside shadow roots

---

website/pages/docs/useFloating.mdx

Fix a typo in the `useFloating` docs based on the information in [this ResizeObserver issue](https://github.com/floating-ui/floating-ui/issues/1740#issuecomment-1151773854).
The docs say `width: max-width` instead of the `width: max-content` that the issue recommends.

docs: Fix typo in useFloating width: max-content

---

.changeset/cyan-insects-know.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx
packages/react/test/unit/setupTests.ts

Updates `<FloatingFocusManager />` to support returning focus to the first focusable descendant of the reference node, when the reference node itself is not focusable. 
This would be beneficial for utilizing patterns like [Popover](https://github.com/floating-ui/floating-ui/blob/master/packages/react/test/visual/components/Popover.tsx) with reference components like a wrapped input (`<div><input /></div>`). 
Related discussion: https://github.com/floating-ui/floating-ui/discussions/2825

feat(FloatingFocusManager): support returning focus to the first focusable descendent of the reference

---

.changeset/short-penguins-appear.md
packages/react/src/components/FloatingOverlay.tsx
packages/react/src/types.ts

`FloatingOverlayProps` is not currently exported.
This causes conflicts that require workarounds with libraries like `styled-components`.
Exporting `FloatingOverlayProps`:
- should not introduce backwards compatibility issues (correct me if I'm wrong)
- will not meaningfully impact bundle size or performance
- will not expose any kind of application information that isn't already available to consumers of the tool
Exporting `FloatingOverlayProps` will benefit consumers of Floating-UI in the following ways:
- Reducing the burden on adapting alternative `tsconfig.json` settings
- Workarounds like casting-`any`
- Creating a `d.ts` file that extends exported types from Floating-UI
I don't see any philosophical reasons to avoid an export of this interface. It seems to be common place that …

feat: FloatingOverlayProps

---

.changeset/mighty-donuts-remain.md
config/scripts/build-api.mjs
package.json
pnpm-lock.yaml
turbo.json

Fixes https://github.com/floating-ui/floating-ui/issues/2863
1. manually replace `React_2` for `React` from type generation at `build-api` script
2. adds `build-api` script as global dependency on turbo configuration
3. bumps `api-extractor` to latest version
4. adds changeset for patching:
* `@floating-ui/react`
* `@floating-ui/react-dom`
* `@floating-ui/react-native`

bugfix: replaces React_2 for React from type generation

---

.changeset/olive-bananas-run.md
packages/react/src/components/Composite.tsx
packages/react/src/components/FloatingArrow.tsx
packages/react/src/components/FloatingDelayGroup.tsx
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingList.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/components/FloatingTree.tsx

fix(types): revert `React.JSX.Element` back to `JSX.Element`

---

.changeset/popular-rats-repair.md
packages/dom/src/autoUpdate.ts

A couple of issues have brought up this loop; increasing the throttle from 0.1s to 1s to reduce strain if the reference is clipped while the floating element is open for extended periods. It's not critical for this to be quick, since a layout shift is unlikely to matter while the reference is clipped, and unlikely to occur <1s after it gets unclipped.

perf(autoUpdate): throttle clipped updates to 1s

---

.changeset/few-news-pay.md
packages/dom/src/platform/getClippingRect.ts

fix: ignore `clippingAncestors` for top layer elements

---

.changeset/strange-rules-listen.md
packages/react/src/hooks/useTransition.ts

https://github.com/floating-ui/floating-ui/pull/2889

fix(useTransitionStatus): guard `isMounted` check and remove unneeded initiated state

---

.changeset/plenty-chefs-thank.md
packages/core/src/middleware/size.ts

fix(size): clip floating width/height to avoid overflowing outside viewport

---

.changeset/proud-suits-kiss.md
packages/react/src/hooks/useListNavigation.ts

fix(useListNavigation): correct `scrollIntoView` and `focus` behavior with virtual focus and inner focused element

---

.changeset/unlucky-geese-switch.md
packages/react/src/hooks/useHover.ts

fix(useHover): `restMs` option for `useHover` causes SyntheticEvent warning on React < 17

---

.changeset/selfish-lizards-grow.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx
packages/react/test/visual/components/Omnibox.tsx

Closes #2903
Currently you need to manually restore focus to the nearest element if the focused element was removed (as done in the `Omnibox` local demo), or focus the floating element itself. 
This does it automatically via a boolean prop. I'm not sure if it should be configurable, with the option to focus the entire floating element itself instead; for example, if the whole dialog's content gets replaced with a new screen, that may be preferrable?
@haagmm-ef

feat(FloatingFocusManager): `restoreFocus` prop

---

.changeset/nine-flies-accept.md
packages/react/src/components/Composite.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/types.ts

This is an amazing project, thank you! 
I just noted that `FloatingFocusManagerProps`, `UseFloatingOptions` etc are all exported except for FloatingPortalProps. This PR proposes that.
Please let me know if this doesn't make sense!

Export FloatingPortalProps

---

.changeset/chatty-pens-cough.md
packages/react/src/components/FloatingOverlay.tsx
packages/utils/src/dom.ts

The `pageXOffset` and `pageYOffset` properties have been deprecated. In this PR, I have replaced `element.pageXOffset` with `element.scrollX` and `element.pageYOffset` with `element.scrollY`.
The `scrollX` and `scrollY` properties are supported by most modern browsers, with the only exception being Internet Explorer. However, according to the [Floating UI support list](https://floating-ui.com/docs/misc), our project no longer requires support for IE. This allows us to utilize these modern properties.

refactor: use `scrollX`/`scrollY` instead of deprecated `pageXOffset`/`pageYOffset`

---

.changeset/green-apricots-eat.md
packages/vue/src/arrow.ts
packages/vue/src/types.ts
packages/vue/src/useFloating.ts
packages/vue/test/index.test.ts

When we encapsulate `useFloating` into a Vue component, we hope to allow users to pass in settings such as `offset` and `arrow` from outside the component. Currently, we need to pass in `Ref` to keep `useFloating` responsive with the component.
```ts
useFloating(refrenceRef, popoverRef, {
// or use `toRef(() => [offset(props.offset)])`
middleware: computed(() => [offset(props.offset)])
})
```
`MaybeRefOrGetter` is already widely used by developers. It would be wonderful if Floating UI could also adopt it!
By adopting `MaybeRefOrGetter`, we can simplify the usage slightly:
```ts
useFloating(refrenceRef, popoverRef, {
middleware: () => [offset(props.offset)]
})
```
This PR introduces `MaybeReadonlyRefOrGetter` and retains `MaybeReadonlyRef` to ensure complete backward compatibility.
Please …

feat(vue): support `MaybeReadonlyRefOrGetter` in `useFloating`

---

.changeset/funny-parrots-cheer.md
packages/vue/src/arrow.ts
packages/vue/src/useFloating.ts
packages/vue/src/utils/toValue.ts

Resolve #2959 
In Vue 2 or earlier versions of Vue 3, the `toValue` API is not supported. Therefore, this PR implements `toValue` internally to ensure proper functionality in older versions.

fix(vue): ensure getter available work in vue of earlier versions

---

.changeset/early-emus-destroy.md
packages/utils/src/dom.ts

This helps avoid recomputing styles when integrating `isContainingBlock` into logic that already has them ([example](https://github.com/jcfranco/composed-offset-position/blob/main/src/index.ts#L71)).

feat(utils): allow reuse of existing computed style in `isContainingBlock`

---

packages/utils/src/dom.ts

Drops `isContainingBlock`'s function overload in favor of union type params to align with [TypeScript best practices](https://www.typescriptlang.org/docs/handbook/2/functions.html#:~:text=Always%20prefer%20parameters%20with%20union%20types%20instead%20of%20overloads%20when%20possible).

refactor(utils): use union type parameter instead of function overload

---

.changeset/grumpy-poets-appear.md
packages/react/test/unit/useFocus.test.tsx

Running the tests throws a warning: 
```
@floating-ui/react:test: stderr | useFocus.test.tsx > stays open when focus moves to element inside reference that is rendered inside a shadow root
@floating-ui/react:test: Warning: An update to App inside a test was not wrapped in act(...).
@floating-ui/react:test:
@floating-ui/react:test: When testing, code that causes React state updates should be wrapped into act(...):
@floating-ui/react:test:
@floating-ui/react:test: act(() => {
@floating-ui/react:test:   /* fire events that update state */
@floating-ui/react:test: });
@floating-ui/react:test: /* assert on the output */
@floating-ui/react:test:
@floating-ui/react:test: This ensures that you're testing the behavior the user would see in the browser. Learn more at …
```

fix: wrap `focus` call in `act` in useFocus tests

---

.changeset/lazy-paws-cry.md
packages/react/src/hooks/useListNavigation.ts
packages/react/test/unit/useListNavigation.test.tsx
packages/react/test/visual/components/Menu.tsx

When building a nested menu that's always mounted in the DOM (and hidden with CSS / `aria-hidden`), `useListNavigation` doesn't focus the first item when a submenu is open. See https://codesandbox.io/p/sandbox/focused-silence-m63rxt for an example.
This is because useListNavigation sets the initial focus only if the list hasn't been mounted on the previous render.
In this PR, I added the `previousOpenRef`, so the focusing logic also works for always mounted lists.
I modified the Menu visual test to include always-mounted branches. Let me know if you'd like to keep it the way it was, and I can create a test component directly in the unit test file.

fix: focus always mounted nested lists with listNavigation

---

.changeset/sharp-cheetahs-whisper.md
packages/react/src/hooks/useHover.ts

Fixes #3013.
As suggested by @atomiks in https://github.com/floating-ui/floating-ui/issues/3013#issuecomment-2299935268, I moved the code in `useHover` that adds `pointer-events: none` to the body inside the if-statement that verifies that `elements.floating` is set.
That way, `pointer-events: none` is always set on `ownerDocument` instead of `document`. This prevents `pointer-events: none` from being applied to incorrect `<body>` elements and thus making them unclickable until the page is refreshed.
I also removed the `pointer-events` in the effect's cleanup function.
I confirmed that this PR fixes the issue (#3013) in our app (by making this change in the node_modules).

fix(useHover): `blockPointerEvents` on `ownerDocument` instead of `document`

---

packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/types.ts

fyi  @oleksandr-danylchenko I'm changing this because it can close if the reference element lost focus instead (when tabbing backwards to the trigger, then back)

refactor: `floating-focus-out` -> `focus-out` reason

---

.changeset/rude-pugs-peel.md
packages/react/src/components/FloatingArrow.tsx
packages/react/test/visual/components/Arrow.tsx
website/pages/docs/FloatingArrow.mdx
website/pages/docs/arrow.mdx

Add test components and documentation regarding arrow() middleware when used with the shift() or autoPlacement() middleware.

Arrow: Add test components & documentation

---

.changeset/silver-foxes-return.md
packages/core/src/middleware/offset.ts

The coords become NaN when we use `offset` middleware and pass undefined to `option.mainAxis` or `option.crossAxis`. This behavior can cause problem when the option was optional value, like `offset({ mainAxis: offsetOrUndefined })`.

fix(offset): avoid NaN when mainAxis or crossAxis is undefined

---

.changeset/nasty-moles-sneeze.md
packages/vue/src/useFloating.ts
packages/vue/test/index.test.ts

Closes https://github.com/floating-ui/floating-ui/issues/3017
Sync with https://github.com/floating-ui/floating-ui/pull/3042

fix(useFloating): avoid setting `isPositioned` to true when `open` is false

---

.changeset/pretty-carrots-repair.md
packages/react/src/components/Composite.tsx
packages/react/src/components/FloatingArrow.tsx
packages/react/src/components/FloatingDelayGroup.tsx
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/components/FloatingList.tsx
packages/react/src/components/FloatingPortal.tsx
packages/react/src/components/FloatingTree.tsx
packages/react/test/unit/FloatingDelayGroup.test.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx
packages/react/test/unit/useFocus.test.tsx

React 19 requires this. React 16 + 17 already support this type in their latest `@types/react` patch versions.
In React 16, the `JSX` namespace has been added under the `React` namespace since `@types/react@16.14.41` in May 2023

refactor: `JSX.Element` -> `React.JSX.Element`

---

.changeset/red-dolls-provide.md
packages/utils/src/dom.ts

Since these allow `any`/`unknown` values, they don't need to have passed an actual element or perform the check for existence themselves at the callsite. This could cause an unexpected error at runtime in server environments.

fix(utils/dom): make element utils ssr-friendly

---

.changeset/hip-turkeys-film.md
packages/react/src/hooks/useHover.ts
packages/react/test/unit/useHover.test.tsx

https://github.com/mui/base-ui/issues/654

fix(useHover): ignore insignificant movement when resetting `restMs`

---

.changeset/olive-dogs-look.md
packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx

https://github.com/mui/material-ui/pull/39713
- `event.isComposing` can't be used in Safari due to the order of events.
- `event.which === 229` can't be used since event listeners are added on the floating element AND document and fires it twice, the second with `event.which === 0` and thus doesn't end up preventing the keypress.
A ref using `compositionstart`/`compositionend` events solves the above issues

fix(useDismiss): handle IME keydown events on `Escape`

---

.changeset/large-crabs-cheat.md
packages/react/src/hooks/useListNavigation.ts

Fixes #3077
From testing, Safari/Firefox don't have this issue, just Chrome/ium

fix(useListNavigation): ignore duplicate arrow navigation when composing

---

.changeset/strong-coins-wink.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx
website/pages/docs/FloatingFocusManager.mdx

Made it possible to explicitly specify the element that will be focused after FloatingFocusManager closes. This reuses the same logic that's already in place to determine when to focus an element and simply adds an ability to focus the provided item.

feat(FloatingFocusManager): Specify element to return focus to

---

README.md

The instructions to run the dev server are incorrect (tested with pnpm 8.15.8 and 9.12.1). Executing the provided script makes pnpm complain: 
```
 ERR_PNPM_NO_SCRIPT  Missing script: dev
Command "dev" not found.
```
The command to run should be the last argument.

docs: update run instructions

---

.changeset/ten-bears-protect.md
packages/dom/src/platform/getClippingRect.ts

This pr allows passing `DOMRect` objects a the [boundary](https://floating-ui.com/docs/detectOverflow#boundary)/[rootBoundary](https://floating-ui.com/docs/detectOverflow#rootboundary) option in `detectOverflow`.
While `DOMRect` is compatible with the expected `Rect` interface, its properties are not enumerable and can't be used with the spread operator.
In other words, this code will work without NaNs:
```ts
computePosition(referenceEl, floatingEl, {
middleware: [
shift({
boundary: myContainer.getBoundingClientRect()
})
]
})
```

fix(getClippingRect): allow passing DOMRect as boundary

---

.changeset/late-humans-decide.md
packages/dom/src/platform/convertOffsetParentRelativeRectToViewportRelativeRect.ts
packages/dom/src/utils/getHTMLOffset.ts
packages/dom/src/utils/getRectRelativeToOffsetParent.ts

Continue #3045, the rect conversion needs to be handled in both functions for clipping rect detection to work.

fix: handle relative html offset clipping rect

---

.changeset/young-oranges-behave.md
packages/react/src/components/FloatingPortal.tsx
packages/react/test/unit/FloatingPortal.test.tsx
website/pages/docs/FloatingPortal.mdx

fix(FloatingPortal): allow `root` to be reactive from `null` to an element

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.github/workflows/release-floating-ui.yml
.github/workflows/update-snapshots.yml
package.json

* github actions is now using node version 20 but actions/checkout@v3, pnpm/action-setup@v2, actions/setup-nodes@v3 are using node verion 16 which is deprecated in github actions, so i update it all v4, you can see [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

chore(.github): update github actions 'uses' to latest version

---

.changeset/brave-rabbits-pretend.md
packages/react/src/components/Composite.tsx
packages/react/test/unit/Composite.test.tsx

Since `FloatingFocusManager` changed its `returnFocus` asynchronicity, it is no longer needed

fix(Composite): change focus to be sync

---

.changeset/hungry-rats-push.md
.changeset/tricky-coins-relax.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx
website/pages/docs/FloatingFocusManager.mdx

Re-add configurability to #3131 to prevent unwanted side effects by default, namely with combobox modality and other unforeseen components

feat(FloatingFocusManager): `outsideElementsInert` prop

---

.changeset/selfish-worms-study.md
packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx
website/pages/docs/useDismiss.mdx

Mostly addresses https://github.com/mui/base-ui/issues/891

fix(useDismiss): allow native clicks to work with `referencePress`

---

website/pages/docs/FloatingArrow.mdx

I believe the stroke width requirement was falsely under the stroke color?

docs(FloatingArrow): fix strokeWidth description

---

.changeset/proud-socks-look.md
packages/react/src/components/FloatingFocusManager.tsx

After #3131, the reference may not be tabbable but focusable, which becomes tabbable after the return

fix(FloatingFocusManager): fallback to container

---

.changeset/stale-lemons-doubt.md
packages/react/src/components/FloatingFocusManager.tsx

ref: https://github.com/mui/base-ui/issues/1078

fix(FloatingFocusManager): use `contains` for tree ancestors on focus out

---

.changeset/stale-lemons-doubt.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/utils/getFloatingFocusElement.ts

Change to #3157. You want focused items inside the ancestor to still trigger a close
ref: https://github.com/mui/base-ui/issues/1078

fix(FloatingFocusManager): check for floating focus root element

---

eslint.config.mjs

* `globals.node` has `globals.commonjs` already, it's duplecated so i remove it
* https://github.com/sindresorhus/globals/blob/main/data/node.mjs#L7
* `tseslint.parser` already exists in `tseslint.configs.recommended`

chore(eslint): remove the duplicate config

---

eslint.config.mjs

* Add `**/dist/` to `ignores` in `eslint.config.mjs` to prevent checking all `dist` files

chore(eslint): add 'dist' to 'ignores' in config

---

.github/workflows/release-floating-ui.yml

Since I pinned functional tests runner to `ubuntu-22.04` in #3210, this started failing in master.
Using the ci workflow directly means it should use the same runners that are defined there.
Could also just pin the test job here to 22.04, but it's likely better to use the same setup that's used for running tests on PRs.
Hoping to get #3210 released soon :)

ci: fix release workflow

---

.changeset/purple-monkeys-remain.md
packages/react/src/hooks/useFocus.ts
packages/react/src/hooks/useHover.ts
packages/react/src/hooks/useTypeahead.ts
packages/react/src/utils.ts
packages/react/src/utils/clearTimeoutIfSet.ts
packages/react/test/visual/components/MacSelect.tsx

We are using floating-ui in a large react SPA with a lot of tooltips and popovers. On every page transition, we experience a big lag due to clearing timeouts from floating-ui called in the useEffect cleanup method, as you can see in the screenshot.
This PR mitigates this performance issue by only calling clearTimeout for timeouts that are actually set before and their ref value is not equal to -1.
We tested it locally with a patch and it works as expected.
Please let me know if you have any suggestions, how to improve or refactor it to meet your requirements.

Improve performance by only clearing used timeouts

---

.changeset/empty-fireants-teach.md
packages/react/src/hooks/useFloating.ts
packages/react/test/unit/useFloating.test.tsx

fix(useFloating): elements passed to `setPositionReference` should add `getClientRects` property

---

.github/actions/setup/action.yml

* Add caching in pnpm and nodejs setup action
* https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
* pnpm caching is not woring now, if we set, our action time will reduce
Now we can see our first cache

ci(.github/actions/setup): add caching in pnpm and nodejs setup action

---

.changeset/lucky-deers-laugh.md
packages/react/src/utils/markOthers.ts
packages/react/test/unit/FloatingFocusManager.test.tsx

It's not a bug per say, but it would be more correct to use empty string for inert value:
- inert is a boolean property, meaning that the value does not generally matter
- for boolean properties, it's recommended to set them to either empty string or the attribute value (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#value) or [HTML spec](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes))
- since this is in the context of React, which itself sets boolean properties to empty string, it would be best to align with that
Context for this change: we use [html-validate](https://html-validate.org/) to validate the rendered HTML of our components. The tool has both [attribute-allowed-values](https://html-validate.org/rules/attribu …

fix(FloatingFocusManager): set inert attribute value to empty string instead of "true"

---

.changeset/serious-dryers-juggle.md
packages/react/src/hooks/useClick.ts
packages/react/test/unit/useClick.test.tsx

Fixes #3190.
Enter keypress on an anchor triggers onClick by default, so it is not needed then.

fix(useClick): fix toggle behavior with Enter key when reference element is anchor

---

.changeset/spotty-tips-kneel.md
package.json
packages/react/src/hooks/useFocus.ts
packages/react/src/utils/matchesFocusVisible.ts
packages/react/test/unit/setupTests.ts
packages/react/test/unit/useFocus.test.tsx
packages/react/test/unit/useHover.test.tsx
pnpm-lock.yaml

Closes #2791
Closes #3026
Closes #3212
Fixes https://github.com/mui/base-ui/issues/1217
I'm not going to make the matches behavior default as it's not always desirable, e.g. for inputs, so it'd need configuration which would add complexity. Since the workaround shared by  @Geksanit works fine, it seems ok to be added externally (and can be inlined directly in `onOpenChange`):
```tsx
const hoverStateRef = React.useRef(false);
const focusStateRef = React.useRef(false);
const {context} = useFloating({
open,
onOpenChange(open, event, reason) {
if (reason === 'focus') {
focusStateRef.current = open;
}
if (reason === 'hover') {
hoverStateRef.current = open;
}
const blurHovered = hoverStateRef.current && !open && reason === 'focus';
const unhoverFocused = focusStateRef.current && !open && reason …
```

fix(useFocus): improve `:focus-visible` checks

---

.github/actions/canary-publish/action.yml
.github/workflows/ci.yml
packages/devtools/package.json

Set up publishing PR and master packages to pkg.pr.new.
I excluded the @floating-ui/devtools package as it is published to npm without the repository field in its package.json and because of this, it can't be published with the `--compact` flag. Once the version with the repository field is published, we should be able to publish all packages (`./packages/*`).

chore: publish canary packages with pkg.pr.new

---

eslint.config.mjs
package.json
pnpm-lock.yaml

* In `eslint-plugin-react-hooks`'s latest version `5.2.0`, we can use flat config, so i reflect it
* https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks#flat-config-eslintconfigjsts

chore(eslint): update 'eslint-plugin-react-hooks' config to use 'recommended-latest'

---

.changeset/small-seals-lie.md
packages/react/src/hooks/useHover.ts

Fixes #3257
The problem arises when mixing native DOM listeners and React's event props. React's run first, and so the `mouseenter` of the floating element fires _before_ the `mouseleave` of the reference element, causing the close timer not to be cleared.
https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-q7gq8l

fix(useHover): prevent floating element from closing when close to reference

---

packages/react/src/hooks/useListNavigation.ts
packages/react/test/unit/useListNavigation.test.tsx
packages/react/test/visual/components/MenuOrientation.tsx

Keyboard navigation for nested lists with different orientation (like a horizontal menubar with vertical menus) works somewhat inconsistently. When a submenu item is focused, pressing <kbd>RightArrow</kbd> closes the submenu and focuses the next item from the parent. Pressing the <kbd>LeftArrow</kbd>, however, closes the submenu and focuses its trigger instead of the previous item.
In this PR, I detect whether the close key of a nested list is also a navigation key of the parent list. If so, the keyboard event isn't stopped, and the parent has a chance to focus on another item.
~~I'm not sure what should happen when the open submenu's trigger is the first item within the parent and `loop = false`. This solution makes the submenu stay open, as the parent won't change focus. Alternatively, …

fix(useListNavigation): Fix list navigation for nested lists with mixed orientation

---

.changeset/clean-beans-hug.md
packages/react/src/hooks/useHover.ts
packages/react/test/unit/useHover.test.tsx
packages/react/test/visual/components/Popover.tsx

Hope the test kind of explains itself, but putting it here as well: if a floating element has both hover and click hooks, pointer events are blocked on reference hover. If the user then clicks the reference element, it switches off the mouseleave handlers, instead waiting for a outside click or some other dismiss event. But, as currently the pointer events remain blocked, this breaks when such floating components are nested - clicking on the parent floating element when pointer events are blocked also closes the parent, as it considers it an outside press then.
Fairly easy to reproduce in the playground Popover component:
1. Open the Popover playground
2. Turn off modal focus management
3. Enable hover on the second level Popover in source
4. Open the first level Popover
5. Open the …

fix(useHover): clean up blockPointerEvents when opened with click after hover

---

.changeset/beige-scissors-work.md
packages/react/src/hooks/useListNavigation.ts
packages/react/test/unit/useListNavigation.test.tsx

As titled, this PR fixes a bug `useListNavigation` does not scroll to the selected index on open.
It is because `forceScrollIntoViewRef.current` is set to false right after `focusItem` is called while scroll [can run asynchronously](https://github.com/floating-ui/floating-ui/blob/46f6464cc38b30aa63209ea4eb9f5f413fe6f777/packages/react/src/hooks/useListNavigation.ts#L460).
Related: https://github.com/floating-ui/floating-ui/pull/3141

Fix a bug `useListNavigation` no longer correctly scroll to the selected index

---

.changeset/stupid-bulldogs-laugh.md
packages/react/src/components/FloatingFocusManager.tsx

This was already the case in the documentation, and it prevents unwanted scrolling when the previously focused element was something out of the viewport and the floating element is opened on hover but focus management remains enabled (so long as we aren't using `preventScroll: true`)

fix(FloatingFocusManager): prioritize returning focus to reference if available

---

.github/ISSUE_TEMPLATE/bug_report.md

`react-dom` versions it to `^2.0.0`, adds `react` and `vue` templates

chore: add more templates

---

.changeset/angry-baboons-run.md
packages/react/package.json
packages/react/src/hooks/useListNavigation.ts
packages/react/test/unit/useListNavigation.test.tsx
packages/react/test/visual/components/Menu.tsx
packages/react/test/visual/components/Menubar.tsx
pnpm-lock.yaml

`focusOnOpenRef` wasn't reset after the popup was closed. If the popup is opened the first time by pressing <kbd>Enter</kbd>, the focusOnOpen strategy set in `useListNavigation` parameters will be overridden for the subsequent open state changes (causing the highlight bug described in https://github.com/mui/base-ui/pull/1684#issuecomment-2827555892).
This PR fixes it by resetting the ref when the popup closes.

fix(useListNavigation): reset focusOnOpen when popup is closed

---

.changeset/kind-rings-sing.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/src/hooks/useDismiss.ts
packages/react/test/unit/useDismiss.test.tsx

Fixes #3060
When the nested floating element isn't nested inside the parent's portal element (changing the `root` on `FloatingPortal` to escape this behavior), it closes unexpectedly because `focusout` is triggered and the handler doesn't have knowledge of the React tree, only the DOM tree.
This PR changes this by using the same capture phase technique to let the handler know it's inside the React tree, to avoid needing to setup `FloatingTree`. This is how outside press is handled already. 
One caveat is that it requires `useDismiss` to be used in conjunction with `FloatingFocusManager` to work because `FloatingFocusManager` can't assign React props. (It seems the `closeOnFocusOut` logic in `FloatingFocusManager` could better live inside `useDismiss` instead - a possible refinement for …

fix(FloatingFocusManager): check for blurring to nested elements inside the React tree without `FloatingTree`

---

.changeset/early-frogs-dress.md
.changeset/strong-plants-taste.md
packages/react/src/components/FloatingOverlay.tsx

Fixes #3264. The Base UI technique has some issues with how `FloatingOverlay` is used, so exporting the CSS var technique for now

fix(FloatingOverlay): add lockScroll scrollbar width CSS var

---

.changeset/mighty-chairs-invite.md
packages/react/src/hooks/useDismiss.ts

There are scenarios where the floating element should close if focus moved outside of it even if it's part of the same React tree. 
e.g. a Menu with submenus that don't close on mouseleave after hovering them, but do if focus is placed on the parent's menu item with the pointer. In this case, since a proper `FloatingTree` has been set up, this is being managed already and this auto blur logic should be ignored

fix(useDismiss): bail out of blur to mark inside React tree if floating tree exists

---

packages/react-dom/package.json
packages/react/package.json
pnpm-lock.yaml
website/package.json

Upgrade to the version that contains https://github.com/Andarist/use-isomorphic-layout-effect/pull/7, just in case [it fixes this preact issue](https://github.com/mui/base-ui/issues/1995#issuecomment-2920539347).

deps: use-isomorphic-layout-effect@1.2.1

---

.changeset/olive-ears-reply.md
packages/react/src/components/FloatingFocusManager.tsx
packages/react/test/unit/FloatingFocusManager.test.tsx

Fixes https://github.com/mui/base-ui/issues/2013
Fixes https://github.com/mui/base-ui/issues/1997

fix(FloatingFocusManager): check if target is connected for `restoreFocus` prop

---

.changeset/slow-walls-invite.md
packages/react/src/safePolygon.ts

#3332 doesn't handle gaps between elements. Using a rectangular area of the entire tree might be better, but it's still not perfect. There should be different/better solution to handle a close delay

fix(safePolygon): revert to checking if any nested child is open
