src/popper.js
Changes to the assign polyfill to convert the target and the nextSource to object.
I can determine the original source of this version of the polyfill to compare it to.
=> Changes to the assign polyfill

CHANGELOG.md, README.md, src/popper.js, tests/test-popper.js
- moved the DOM manipulating logic inside the `applyStyle` modifier
- the callback is now called using `.onCreate` method
- added `.onUpdate` callback
- improved README examples
ping @schickling @eek and @mgcrea for feedbacks
=> React.js support and improvements

src/popper.js
=> Deep Object.assign to fix #29

src/popper.js
Without it, it fails silently on a jquery element.
=> add jquery convenience check to config.parent

src/popper.js
=> fixed scroll detection on IE

README.md
Just a super quick update because it's caught a couple of people now
=> Fixes #95: Updates readme with correct example

README.md
Thanks for your interest in contributing to Popper.js!  
Please, make sure to fulfill the following conditions before submitting your Pull Request.  
1. Don't include the result of `npm run build` inside your commits;
2. Make sure the tests are passing, you can check it running `npm test` with Google Chrome installed;
3. Add any relevant test to cover the code you have changed and/or added;
=> docs(readme): middlewars -> middlewares

src/popper/utils/getBoundaries.js, tests/functional/core.js
fixes #143, please @ocombe may you test this as well and confirm that everything is working fine?
=> fixed #143

.travis.yml
run coverage on IE10 as well to cover the polyfills
=> run coverage on IE10

src/popper/utils/find.js, tests/unit/find.js, tests/unit/findIndex.js, tests/unit/getOppositePlacement.js, tests/unit/getOppositeVariation.js
=> Add more unit tests

src/popper/index.js
Thanks for your interest in contributing to Popper.js!  
Please, make sure to fulfill the following conditions before submitting your Pull Request.  
1. Make sure the tests are passing, you can check it running `npm test` with Google Chrome installed;
2. Add any relevant test to cover the code you have changed and/or added;
=> Fix typo in method param

src/popper/utils/getBoundaries.js, src/popper/utils/getOffsetRectRelativeToViewport.js, tests/functional/core.js
=> [fix] Calculate position to documentRoot instead of offsetParent (fixes #177)

package.json, src/popper/index.js, src/popper/utils/removeEventListeners.js, src/popper/utils/setupEventListeners.js, tests/functional/core.js
Added a test to make sure we don't have regressions in future and bumped version.
=> [fix]: Fixed scroll event listeners (#151)

tests/functional/flips.js
This PR adds an x'd out failing test for issue https://github.com/FezVrasta/popper.js/issues/188.
=> Adds an x’d out failing test for issue #188

tests/functional/core.js
This test is not accurate, the `expect` part requires revision. Is an attempt to help as asked in #191.
=> add a test for html with margins

src/popper/utils/getBoundingClientRect.js, tests/functional/core.js
=> [fix] Properly compute positions when HTML has margin (fix #191)

tests/functional/flips.js
I was able to fix this test modifying `getBoundaries` and adding `scrollTop` and `scrollLeft` to `top` and `left`.
But then, other two tests break.
=> Added test for #171

.travis.yml, scripts/karma.conf.js, tests/functional/core.js, tests/functional/flips.js
=> [tests] Add tests on mobile Safari and ~Chrome~

src/popper/utils/getBoundingClientRect.js, src/popper/utils/getOffsetRectRelativeToArbitraryNode.js, src/popper/utils/isIE10.js
=> fix: lazily check for IE10

docs/_includes/popper-documentation.md, src/popper/index.js, src/popper/methods/defaults.js, src/popper/methods/destroy.js, src/popper/methods/disableEventListeners.js, src/popper/methods/enableEventListeners.js, src/popper/methods/placements.js, src/popper/methods/update.js, src/popper/utils/clockwise.js
=> [refactor] Moved methods to separated folder

src/popper/index.js
Please @joscha verify that this fixes your problem with Sinon.
=> [fix] #256

package.json, src/popper/utils/getWindowSizes.js
Please @atomiks may you test this version and confirm it fixes #251?
=> [fix] Don't attempt to use scrollSize to detect window sizes

package.json, src/popper/modifiers/arrow.js
=> [fix] Fix rounding of arrow offset

src/popper/methods/update.js, src/popper/utils/computeAutoPlacement.js, tests/functional/flips.js
=> [fix] Auto placement computation

package.json, src/popper/index.js, src/popper/modifiers/applyStyle.js
Fixes #288
cc @Johann-S for review
=> [fix] Fixed #288

MENTIONS.md
Thanks for your interest in contributing to Popper.js!  
Please, make sure to fulfill the following conditions before submitting your Pull Request.  
1. Make sure the tests are passing, you can check it running `npm test` with Google Chrome installed;
2. Add any relevant test to cover the code you have changed and/or added;
=> Change MENTIONS. add vue-popperjs component

MENTIONS.md, README.md
Hey,
Iv'e created an Angular wrapper for popper.js.
Still in progress but it works.
=> add ngx-popper reference to README.md and MENTIONS.md

src/tooltip/index.js
Fixes #290. Trying to figure out how to write a proper test for this.
=> Fix tooltip trigger events

scripts/nugetPublish.js
@FezVrasta a quick fix to your nugetPublish script which build nuget package as expected 👍
=> Fix nugetPublish script to package all dist files

package.json, yarn.lock
Signed-off-by: CDAGaming <cstack2011@yahoo.com>
Missed An Update in both Yarn in Package.json
Verify is also currently failing with this error:
`Chrome 58.0.3029 (Windows 10 0.0.0) [core] init a popper near the right side of a custom container and make sure it stays between boundaries FAILED
Expected 742 to be 741.
at Object.onUpdate (E:/Forked%20Repos/popper.js/tests/functional/core.js:3482:55)
at Popper.update (E:/Forked%20Repos/popper.js/tests/functional/core.js:895:18)
at Popper.update$$1 (E:/Forked%20Repos/popper.js/tests/functional/core.js:2197:21)
at MutationObserver.<anonymous> (E:/Forked%20Repos/popper.js/tests/functional/core.js:41:5)`
=> Updated Dependencies (Latest as of 6/3/2017)

packages/popper/package.json, packages/popper/src/modifiers/arrow.js, packages/popper/src/modifiers/computeStyle.js
cc @atomiks, please make sure it solves your problem once for all.
=> [fix] #277

packages/popper/package.json, packages/popper/src/utils/getOffsetRectRelativeToArbitraryNode.js, packages/popper/tests/functional/core.js, packages/popper/tests/visual/test.html
Please @netylia let me know if this fixes your problem.
=> [fix] #305

packages/popper/package.json, packages/popper/src/modifiers/computeStyle.js
=> [fix] #338

MENTIONS.md
=> Remove ngx-popper from Alpha

lerna.json, package.json
PS 2 Dependencies, Async and Wide-Align were missing, so thats fixed too
PS Also sorry for my latest downtime, i hope to not have as long of a downtime in the future ;)
Signed-off-by: CDAGaming <cstack2011@yahoo.com>
=> Updated Dependencies

packages/popper/tests/functional/core.js
Added test to check regressions of #302. Fix is still needed.
=> [test] Added test for #302

docs/tooltip-examples.html
It's = it is
Its = possessive pronoun
=> Fix typo in tooltip-examples page

README.md
Link was previously being mistaken for a page relative to this project's root.
=> Corrected TravisCI link

packages/popper/src/methods/update.js, packages/popper/src/modifiers/applyStyle.js, packages/popper/src/modifiers/computeStyle.js, packages/popper/src/modifiers/index.js, packages/popper/tests/functional/arrow.js
=> feat(popper): Add data.arrowStyles property

packages/popper/src/utils/getBoundaries.js, packages/popper/src/utils/getWindowSizes.js
This reverts commit 1b3a82d77a11ce84d767da0f1ac4982774a64979.
It's going to break https://github.com/FezVrasta/popper.js/issues/251
=> Revert "fix(popper): Fixed regression #401 (#402)"

MENTIONS.md
=> Add v-tooltip

packages/popper/index.d.ts, packages/popper/src/methods/defaults.js, packages/popper/src/methods/update.js, packages/popper/src/modifiers/applyStyle.js, packages/popper/src/modifiers/flip.js, packages/popper/src/modifiers/preventOverflow.js, packages/popper/src/utils/computeAutoPlacement.js, packages/popper/src/utils/getBoundaries.js, packages/popper/src/utils/getBoundingClientRect.js, packages/popper/src/utils/getReferenceOffsets.js, packages/popper/tests/functional/arrow.js, packages/popper/tests/functional/core.js, packages/popper/tests/functional/flips.js, packages/popper/tests/functional/lifecycle.js, packages/popper/tests/functional/offset.js, packages/popper/tests/functional/rendering.js
=> add positionFixed property, making popper with position: 'Fixed' as an option

README.md
=> Added missing Oxford (serial) commas in README.md

packages/popper/src/utils/getOffsetParent.js, packages/popper/tests/unit/getOffsetParent.js
=> Fix offset parent calculation for hidden elements

packages/popper/src/modifiers/applyStyle.js
There seems to be an obviously extra period-sign in the comments of the code of this repository.
As you can see, this suggestion is very detail-oriented. But I cannot stop thinking about it.
I apologize you if there's any deficiency in this suggestion.
=> Deleted an extra period

packages/popper/src/utils/isIE.js
Noticed a semi-substantial increase in file size due to the new util...
A closure can be also used instead of the external "cache" object
Old: 472 bytes
New: 132 bytes
=> Make isIE minifier-friendly

packages/popper/src/utils/debounce.js, packages/popper/src/utils/isBrowser.js, packages/popper/src/utils/isIE.js
Patches pull #594 so errors won't be thrown in Node envs.
=> Patch pull #594

packages/popper/src/methods/update.js, packages/popper/src/modifiers/preventOverflow.js
@atomiks does this PR still keeps the fix introduced in #596? If so I'd like to merge this because it seems to fix [react-popper/#122](https://github.com/souporserious/react-popper/issues/122) as well.
=> fix: Regression introduced by #596

packages/tooltip/package.json
=> add license to tooltip.js package.json file

packages/tooltip/.npmignore
=> add typecript types to npm build

packages/popper/src/utils/getOffsetRectRelativeToArbitraryNode.js, packages/popper/tests/unit/getBoundaries.js
=> Refactor tiny redundancy

packages/popper/index.js.flow
=> flowtype: add event listener methods to Instance

MENTIONS.md
=> angular-popper is a angular (2 <=) library, not a AngularJS library

packages/tooltip/src/index.js, packages/tooltip/tests/functional/tooltip.js
I hope I've added a good enough test and everything is in the right place.
This PR addresses issue #717.
If anything needs any changes just give me a shout.
=> #717 delayed tooltip flashing

README.md
=> Update README.md  err translated into Portuguese would be perfect for reading!

docs/_includes/tooltip-documentation.md, packages/tooltip/src/index.js
=> Fix the documentation for tooltip options

CONTRIBUTING.md
=> HTTPS codepen link

docs/_includes/header.html, docs/css/main.scss, docs/index.html, docs/popper-documentation.html, docs/themes.html
=> Add UI Tools section and page

packages/tooltip/src/index.js, packages/tooltip/tests/functional/tooltip.js
=> dont ignore offset on offset modifiert on tooltip.js. Fixes #376

src/modifiers/detectOverflow.js
Didn't do much but I think you wanted a PR, merging into the feature branch you have
I think this is the behavior you want as it matches v1 as far as I can tell regarding body/boundary margins
=> fix(detectOverflow): remove boundary margin calc

src/index.js, src/modifiers/applyStyles.js, src/modifiers/arrow.js, src/modifiers/computeStyles.js, src/modifiers/index.js, src/types.js, tests/visual/modifiers/arrow/index.html
I hope this approach is good, need some help with the types
=> feat: arrow modifier

src/dom-utils/getBoundingClientRect.js, src/dom-utils/getCommonTotalScroll.js, src/dom-utils/getElementClientRect.js, src/dom-utils/getNodeName.js, src/dom-utils/getScrollParent.js, src/dom-utils/getScrollSum.js, src/dom-utils/listScrollParents.js, src/index.js, src/modifiers/applyStyles.js, src/modifiers/arrow.js, src/modifiers/popperOffsets.js, src/types.js, src/utils/unwrapVirtualElement.js, tests/visual/virtual.html
```js
const virtualElement = {
// positioning context, real DOM element
contextElement: reference,
// custom position
getBoundingClientRect: () => ({
width: 200,
height: 150,
top: 100,
right: 300,
bottom: 250,
left: 100,
}),
};
```
=> feat: virtual elements

README.md, docs/src/pages/modifiers/detect-overflow.mdx, docs/src/pages/modifiers/flip.mdx, docs/src/pages/modifiers/index.mdx, docs/src/pages/modifiers/offset.mdx, docs/src/pages/modifiers/prevent-overflow.mdx, package.json, src/index.js, src/popper-base.js, src/popper-lite.js, src/popper.js, tests/flowtype/modifiers.js, tests/visual/basic.html, tests/visual/borders-and-margins.html, tests/visual/modifiers/arrow/index.html, tests/visual/modifiers/flip/index.html, tests/visual/modifiers/offset/index.html, tests/visual/modifiers/preventOverflow/index.html, tests/visual/resize.html, tests/visual/rounding.html, tests/visual/scrolling/nested-alt.html, tests/visual/scrolling/nested-same.html, tests/visual/scrolling/nested.html, tests/visual/scrolling/offset-parent.html, tests/visual/scrolling/scroll.html, tests/visual/svg.html, tests/visual/transform.html, tests/visual/virtual.html, yarn.lock
=> feat: use closure instead of class

package.json, src/index.js, src/utils/__snapshots__/orderModifiers.test.js.snap, src/utils/orderModifiers.js, src/utils/orderModifiers.test.js, tests/setupTests.js
I used the second algorithm in the link (the one with most upvotes) instead and adapted it - it seems to work.
I have no idea how it works, so I think we should add some unit tests to make sure it works appropriately?
=> fix: modifier ordering

src/utils/orderModifiers.js, src/utils/orderModifiers.test.js
This is already done in `validateModifiers`
=> fix: remove requires validation in orderModifiers

src/modifiers/offset.js
=> feat: allow non-function for offset

src/modifiers/__snapshots__/computeStyles.test.js.snap, src/modifiers/computeStyles.js
- fix stale style properties
- use `gpuAcceleration`
=> fix: arrow styles

src/dom-utils/getBoundingClientRect.js
=> fix: getBoundingClientRect normalization

docs/package.json, docs/src/components/Demos.js, docs/src/components/Framework.js, docs/src/components/Header.js, docs/src/components/Highlight.js, docs/src/components/InstallBar.js, docs/src/components/Landing.js, docs/src/components/Layout.js, docs/src/components/Navigation.js, docs/src/components/Popper.js, docs/src/components/carbonAds.css, docs/src/components/layout.css, docs/src/components/prism-base2tone-pool-dark.css, docs/yarn.lock
- Mostly finishes the landing page
- Docs theme coherent with landing page
- Improvements for small viewports
- Use `react-feather` icons
=> docs: additional work

src/utils/computeOffsets.js, src/utils/getMainAxisFromPlacement.js
=> refactor: function names (continue #913)

src/dom-utils/getClippingRect.js, src/dom-utils/getDecorations.js
This works for `dir="rtl"` as well
=> fix(getClippingRect): account for scrollbars

src/modifiers/flip.js, src/modifiers/hide.js, src/modifiers/preventOverflow.js, src/utils/validateModifiers.js
When specifying `requiresIfExists`, it made `requires` required
=> fix: requiresIfExists optionality

docs/src/components/CarbonAds.js, docs/src/components/Demos.js, docs/src/components/Framework.js, docs/src/components/InstallBar.js, docs/src/components/Landing.js, docs/src/components/Layout.js, docs/src/components/carbonAds.css, docs/src/pages/docs/browser-support.mdx, docs/src/pages/docs/constructors.mdx, docs/src/pages/docs/faq.mdx, docs/src/pages/docs/modifiers/index.mdx, docs/src/pages/docs/tippy.mdx, docs/src/pages/docs/tree-shaking.mdx, docs/src/utils/processRoutes.js
Fixes issues and adds these pages:
- `Constructors`
- `Tree-shaking`
- `FAQ`
=> docs: tweaks and add pages

src/dom-utils/getWindow.js
There is no `Window` type in Flow(?)
Does this fix the issue @JoelKang?
=> fix: getWindow logic

src/index.js, src/index.test.js, src/utils/orderModifiers.js, tests/setupTests.js
#930 caused this problem, I moved filtering after the validation
=> fix: validation error for disabled modifiers

docs/src/components/CarbonAds.js, docs/src/components/Framework.js, docs/src/components/Landing.js, docs/src/components/Layout.js, docs/src/components/Navigation.js, docs/src/components/layout.css, docs/src/components/prism-base2tone-pool-dark.css, docs/src/pages/docs/index.mdx
=> docs: fixes

docs/src/pages/docs/browser-support.mdx
=> docs: add notes on Safari support

docs/src/components/Popper.js, docs/src/components/Tutorial.js, docs/src/components/prism-base2tone-pool-dark.css, docs/src/pages/docs/tutorial.mdx, docs/src/utils/processRoutes.js
This should help people getting started
=> docs: add tutorial

src/modifiers/flip.js
- Optimizes checks for the best cases (skips unnecessary calculations)
- Prevents the modifier from running again unnecessarily after resetting the modifier cycle (using `skip` data)
Total scripting time for the `modifiers/flip/checkVariation.html` test with 6x CPU slowdown while scrolling (which has multiple fallback checks to make) was reduced from 19.8% to 9.8%
=> perf: optimize flip modifier

src/modifiers/flip.js
This is unstable and might be removed or changed when refactoring, and will stay undocumented. Doesn't seem useful either.
=> fix(flip): make skip data private

src/index.js, src/index.test.js, src/modifiers/applyStyles.js
=> fix: sync destroy cleanup

docs/src/components/Navigation.js, docs/src/components/Popper.js, docs/src/pages/docs/v2/constructors.mdx, docs/src/pages/docs/v2/index.mdx, docs/src/pages/docs/v2/modifiers/flip.mdx, docs/src/pages/docs/v2/modifiers/prevent-overflow.mdx
Appending `v2/` broke these :\
=> docs: fix links

README.md, docs/gatsby-config.js, docs/src/components/Demos.js, docs/src/components/Header.js, docs/src/components/InstallBar.js, docs/src/components/Landing.js, docs/src/components/Layout.js, docs/src/components/Tutorial.js, docs/src/components/carbonAds.css, docs/src/components/layout.css, docs/src/components/prism-base2tone-pool-dark.css, docs/src/pages/docs/v2/tippy.mdx, docs/src/pages/docs/v2/tutorial.mdx, docs/src/pages/docs/v2/utils/index.mdx
=> docs: various

docs/src/pages/docs/v2/typings.mdx, src/types.js
=> fix(types): modifier state type, remove isCreated state prop

README.md, docs/src/pages/docs/v2/index.mdx, docs/variables.js
iirc `@^2.0.0` is the same as `@2`
=> docs: add dev version for umd

README.md, docs/src/pages/docs/v2/faq.mdx, docs/src/pages/docs/v2/migration-guide.mdx
=> docs: add migration guide

.github/workflows/main.yml
=> chore: add size report to PRs

src/dom-utils/getCompositeRect.js, src/dom-utils/getDecorations.js, tests/visual/rtl.html
=> fix: rtl scrollbar

src/modifiers/computeStyles.js
=> fix: add transition warning

package.json
=> chore: add keywords to package.json

docs/src/components/Header.js, package.json, src/dom-utils/getOffsetParent.js
=> chore: update links

docs/src/components/Popper.js, docs/src/pages/docs/v2/faq.mdx, docs/src/pages/docs/v2/modifiers/offset.mdx
& made the offset modifier examples a bit more obvious (20px vs 10px)
=> docs: add faq entries and fix hook

src/popper-base.js, src/popper-lite.js, src/popper.js
Resolves #1034 
This makes it accessible to UMD and CJS consumers
=> feat: export detectOverflow

docs/src/pages/docs/v1/index.mdx
documenntation -> documentation
=> Fix small typo from documentation

src/dom-utils/getOffsetParent.js
Resolves #1043 (and fixed incorrect behavior for #837)
=> fix: firefox offsetParent check

docs/src/pages/docs/v2/modifiers/arrow.mdx, docs/src/pages/docs/v2/utils/detect-overflow.mdx, docs/src/pages/docs/v2/virtual-elements.mdx
=> docs: v2.2 release

docs/src/components/Demos.js, docs/src/pages/docs/v2/modifiers/arrow.mdx
=> docs(arrow): add centerOffset to demo

src/modifiers/computeStyles.js
https://github.com/popperjs/popper-core/pull/1053#issuecomment-610740982 (assuming it does return `null` and not `undefined`?)
=> fix: transitionProperty dev check

src/dom-utils/getViewportRect.js, src/types.js
=> fix: properly compute iOS visual viewport

.config/rollup.config.js, package.json
Fix for https://github.com/popperjs/popper-core/issues/1064
=> fix(flow): remove src folder from npm bundle

src/dom-utils/listScrollParents.js
=> fix: visual viewport types and body check

src/dom-utils/getViewportRect.js
fix #1074
Maybe there is a better hack 🤦
=> fix: ios visual viewport

src/modifiers/arrow.js, src/modifiers/computeStyles.js, src/modifiers/offset.js, src/modifiers/preventOverflow.js, src/types.js, src/utils/computeAutoPlacement.js, typescript/ts.js
Same as https://github.com/popperjs/popper-core/pull/1071, but with TS fixes
=> Atomiks fix/modifiers data types

src/types.js
=> fix(types): modifiersData.offset placement is not optional [ts]

src/modifiers/arrow.js, src/modifiers/arrow.test.js
(and reused  `arrowElement` variable)
=> fix: add warning for SVGElement as arrow

src/utils/detectOverflow.js
=> feat(types): export detectOverflow Options type

src/modifiers/arrow.js, src/modifiers/arrow.test.js
Never know when to use `a` or `an` but stay consistent at least 😅
=> fix: warning typo

.github/workflows/functional-tests.yml
By using a top-level container for the job you can pass a Docker option
to increase the shared memory used by the container. I set it to 1
gigabyte since that was suggested but it can be increased if that is
not sufficient for whatever reason.
=> Fixing functional test OOM issue

src/dom-utils/getOffsetParent.js, src/dom-utils/listScrollParents.js
Adding a few comments based on questions and discussion with @FezVrasta
=> add some documentation on getOffsetParent and listScrollParents

src/index.js, src/popper-base.js, src/popper-lite.js, src/popper.js
@lainermeister does this fix the issue?
Closes #1130
=> fix: detectOverflow export

src/popper-base.js, src/popper-lite.js, src/popper.js
=> fix: paths for ts generation

package.json, patches/@khanacademy+flow-to-ts+0.1.6.patch, yarn.lock
follow upstream Khan/flow-to-ts/pull/179
Fixes #1149
=> fix: incorrect type

package.json
=> fix: npm/yarn installation issue due to postinstall script

package.json, yarn.lock
Upgrade @khanacademy/flow-to-ts and remove patch-package. #1150
Upstream PR Khan/flow-to-ts/pull/179 has published
=> chore: upgrade @khanacademy/flow-to-ts

.flowconfig, src/dom-utils/getParentNode.js
=> fix: shadow DOM detection and anchor tags

src/dom-utils/getDocumentRect.js, src/dom-utils/listScrollParents.js
=> fix: handle null ownerDocument

src/modifiers/arrow.js, src/modifiers/arrow.test.js
=> feat: add support for padding callback

src/modifiers/applyStyles.js
=> fix: remove initial styles from elements (fixes #1182)

src/modifiers/preventOverflow.js
=> fix: altAxis + tether

src/dom-utils/getLayoutRect.js
Fix #1223 
@mkrds, haven't checked if this actually solves the issue, can you confirm it?
=> fix: #1223 pixel positioning

src/dom-utils/getLayoutRect.js
https://github.com/popperjs/popper-core/issues/1223 
@mkrds
=> fix: use 1px check for layout rect

src/dom-utils/getOffsetParent.js
=> fix: replace includes with indexOf to support IE11 again

.github/workflows/tests.yml, src/dom-utils/getBoundingClientRect.js
=> fix: incorrect position when offsetWidth/height is 0

README.md
Edits the copy for why users should use the library.
=> refactor: README benefits copy

src/modifiers/offset.js
I would like to import this type so I can annotate my function.
=> Export `OffsetsFunction`

package-lock.json, packages/core/package.json, packages/core/rollup.config.js, packages/core/src/enums.ts, packages/dom/package.json, packages/dom/rollup.config.js, packages/react-dom/package.json, packages/react-dom/rollup.config.js, packages/react-native/package.json, packages/react-native/rollup.config.js
I just discovered the library is not fully tree-shakeable for some reason, so I added a `/* #__PURE__ */` comment.
=> perf(core): add pure annotation for allPlacements const

packages/core/src/computePosition.ts
=> fix: more helpful platform error

packages/core/src/middleware/shift.ts
=> fix(limitShift): crossAxis offset

packages/react-native/rollup.config.js
=> chore(react-native): bundle in core package

packages/core/src/types.ts, packages/dom/src/types.ts, packages/react-dom/src/types.ts, packages/react-native/src/types.ts
- Made some improvements in `core/src/types.ts`
- Re-exported `Platform`, `Placement`, `Strategy` and `Middleware` types (the ones used as arguments of `computePosition`) in every package for easier access
=> TypeScript improvements

.github/workflows/release-popper.yml
=> add workflow to release popper versions

packages/react-dom/src/index.ts, packages/react-native/src/index.ts
@mkomensu
Let me know if this fixes your issue
Closes #1494
=> fix(react): unmounted component warning

website/pages/docs/react-dom.mdx
Closes #1520.
How's this? Too verbose?
=> Document how to solve `act` warnings

packages/core/src/detectOverflow.ts, packages/core/src/middleware/arrow.ts, packages/core/src/middleware/inline.ts, packages/core/src/types.ts, packages/dom/src/platform.ts
Canvas is not concerned with these and React Native a couple.
=> feat: make DOM-like platform properties optional

packages/core/src/detectOverflow.ts, packages/core/src/types.ts, packages/dom/src/types.ts, packages/dom/src/utils/getBoundingClientRect.ts, packages/dom/src/utils/getClippingRect.ts, packages/dom/src/utils/getRectRelativeToOffsetParent.ts, packages/dom/src/utils/getViewportRect.ts, packages/dom/src/utils/is.ts
=> fix: safari pinch zooming for `fixed` strategy

packages/dom/src/utils/getNodeScroll.ts, packages/dom/src/utils/window.ts
=> fix: window check for Electron

packages/core/src/middleware/flip.ts
A small optimization
- calculate before sorting, reducing duplicate calculations
- reduce duplicate code
=> improve sort compareFunction

packages/react-dom/src/types.ts
Fixes https://github.com/floating-ui/floating-ui/issues/1600
=> Export VirtualElement

package-lock.json, packages/react-dom-interactions/package.json, packages/react-dom-interactions/rollup.config.js, packages/react-dom-interactions/src/FloatingOverlay.tsx, packages/react-dom-interactions/src/FloatingPortal.tsx, packages/react-dom-interactions/src/hooks/useClick.ts, packages/react-dom-interactions/src/hooks/useDismiss.ts, packages/react-dom-interactions/src/hooks/useFocusTrap.ts, packages/react-dom-interactions/src/hooks/useHover.ts, packages/react-dom-interactions/src/hooks/useListNavigation.ts, packages/react-dom-interactions/src/types.ts, packages/react-dom-interactions/src/useInteractions.ts, packages/react-dom-interactions/src/utils/useLatestRef.ts, website/pages/docs/react-dom-interactions.mdx, website/pages/docs/useClick.mdx, website/pages/docs/useDismiss.mdx, website/pages/docs/useFocusTrap.mdx, website/pages/docs/useListNavigation.mdx
This is the first release where changelogs will start being generated. Individual PRs will follow for new features/fixes
=> [React DOM Interactions] v0.1

packages/react-dom-interactions/src/hooks/useFocusTrap.ts
Do not close floating element on blur when focus goes to nested floating elements within a portal
=> Do not close floating element on blur when focus goes to nested floating elements within a portal

packages/react-dom-interactions/src/hooks/useHover.ts, packages/react-dom-interactions/src/safePolygon.ts, website/pages/docs/useHover.mdx
- `timeout` => `restMs`
- `buffer` exposed
=> feat(safePolygon): expose/document options

packages/core/LICENSE, packages/dom/LICENSE, packages/react-dom-interactions/LICENSE, packages/react-dom/LICENSE, packages/react-native/LICENSE
=> Add LICENSE files to individual packages

packages/react-dom-interactions/src/hooks/useListNavigation.ts
Allows virtualization etc.
/cc @ChiaJune does it fix? Closes #1629
=> fix(useListNavigation): allow nullish items

packages/react-dom-interactions/src/hooks/useClick.ts, website/pages/docs/useClick.mdx
Toggling sometimes isn't desired
=> feat(useClick): `toggle` prop

packages/react-dom-interactions/src/FloatingFocusManager.tsx
=> fix(FloatingFocusManager): import React

packages/react-dom-interactions/src/FloatingPortal.tsx, packages/react-dom-interactions/src/index.ts, website/pages/docs/FloatingPortal.mdx
=> feat: add useFloatingPortalNode hook

packages/react-dom-interactions/src/hooks/useHover.ts, packages/react-dom-interactions/src/safePolygon.ts
https://github.com/floating-ui/floating-ui/discussions/1692
I also noticed some minor floating point errors where it would close unexpectedly which this tries to address
=> fix(useHover): close on scroll mouseleave when using safePolygon

packages/react-dom-interactions/src/hooks/useHover.ts
=> fix(useHover): clear timeouts on unmount

packages/core/src/types.ts, packages/dom/src/types.ts, packages/dom/test/visual/spec/Flip.tsx, packages/dom/test/visual/spec/Offset.tsx, packages/dom/test/visual/spec/Shift.tsx
=> Fix importing non-exported types from core.

packages/react-dom-interactions/src/hooks/useClick.ts, packages/react-dom-interactions/test/unit/useClick.test.tsx
=> fix(useClick): initially open toggling

packages/react-dom-interactions/src/FloatingFocusManager.tsx, packages/react-dom-interactions/src/hooks/useDismiss.ts
=> fix: prevent unwanted scrolling when dismissing via outside pointerdown

website/pages/docs/hide.mdx, website/pages/docs/react-dom.mdx, website/pages/docs/shift.mdx
=> docs: update for v1

packages/react-dom-interactions/src/hooks/useDismiss.ts
Closes #1779, appears to work for horizontal scrolling also
=> fix(useDismiss): don't close when clicking scrollbar

src/dom-utils/getBoundingClientRect.js, src/dom-utils/getClippingRect.js, src/dom-utils/getCompositeRect.js, src/dom-utils/getOffsetParent.js, src/dom-utils/getViewportRect.js, src/dom-utils/isLayoutViewport.js, src/utils/detectOverflow.js, src/utils/userAgent.js
This is an amendment from @floating-ui adapted to @popperjs and flow
fix: #1121
original fix: #1576
also discussion: #1839
=> fix(DOM): iOS safari pinch zooming fix

packages/react-dom-interactions/src/safePolygon.ts
=> fix(safePolygon): `useHover` open-close loop with overlapping

packages/dom/src/autoUpdate.ts
=> fix(autoUpdate): retain `ancestorResize` with animationFrame: true

packages/react-dom-interactions/src/utils/useEvent.ts
=> fix(useEvent): work around minifier bug

website/pages/docs/FloatingFocusManager.mdx
=> docs: closeOnFocusOut on FloatingFocusManager

packages/dom/src/utils/getScale.ts
Unfortunately 🥲, it seems like #2036 has an issue if the element being checked for scale has scrollbars. While this could be checked for, there may be even other side effects that may need to be accounted for, so it's likely just safest to fallback to the old technique. If there are abberations with the scale, it's not hard for the user to set `box-sizing: border-box` (usually set anyway) on the scaled element and use the new technique
=> fix: use fallback scale

package-lock.json, packages/core/package.json, packages/dom/package.json, packages/react-dom/package.json, packages/react-native/package.json, packages/react/package.json, packages/vue/package.json
=> chore: upgrade Rollup/Babel build deps

website/pages/docs/useDismiss.mdx
=> docs: useDismiss bubbles object

packages/react/src/types.ts
=> fix(types): export React interaction hook prop types

packages/core/src/middleware/flip.ts, packages/core/src/utils/getOppositeAxisPlacements.ts, packages/core/test/utils/getOppositeAxisPlacements.test.ts
Closes #2051  
@mihkeleidast 
See changelog below
=> feat(flip): `fallbackAxisDimension` option

packages/vue/src/types.ts, packages/vue/src/useFloating.ts, packages/vue/test/index.test.ts, website/pages/docs/vue.mdx
Sync with https://github.com/floating-ui/floating-ui/pull/2001
=> `open` option and `isPositioned` return value for Vue

packages/react/src/hooks/useHover.ts
`cleanupMouseMoveHandler` can change reference during transitions since the `floating` dep is added, which can clear a delay timeout unexpectedly if requesting an open while an unmount is in transition.
=> refactor(useHover): use unbind ref to cleanup mousemove

packages/react/src/safePolygon.ts
Part of https://github.com/floating-ui/floating-ui/pull/2133, but with improvements - however, that PR has other changes that need more work, for now only this change will go out in the next patch release.
=> fix(safePolygon): cursor landing logic

packages/react/src/components/FloatingPortal.tsx, packages/react/test/unit/FloatingPortal.test.tsx
=> fix(FloatingPortal): allow empty id string

packages/react/src/hooks/useTypeahead.ts, packages/react/test/unit/useTypeahead.test.tsx
=> fix(useTypeahead): allow type ahead when currentTarget contains target

packages/react/src/hooks/useClientPoint.ts, packages/react/src/index.ts, packages/react/src/types.ts, packages/react/src/utils/is.ts, packages/react/test/unit/useClientPoint.test.tsx
=> feat(react): `useClientPoint` hook

packages/core/src/middleware/inline.ts, packages/core/test/middleware/inline.test.ts
=> fix(inline): group rects by line with fuzzy height and y coord

packages/react/src/components/FloatingPortal.tsx, packages/react/test/unit/FloatingPortal.test.tsx
=> refactor(FloatingPortal): use subroot structure

packages/react/src/hooks/useClientPoint.ts
Fixes https://github.com/floating-ui/floating-ui/issues/2245 / https://github.com/floating-ui/floating-ui/discussions/2246
=> fix(useClientPoint): keep anchored to reference on `autoUpdate` in applicable scenarios

packages/react/src/hooks/useClick.ts, packages/react/src/hooks/useTypeahead.ts, packages/react/test/unit/useTypeahead.test.tsx
=> fix(useTypeahead): space opening with useClick, typing change

packages/react/src/components/FloatingArrow.tsx
Add possibility to override arrow styles for FloatingArrow
=> fix(react):  override arrow styles

packages/dom/src/utils/getCssDimensions.ts, packages/react/src/components/FloatingArrow.tsx
=> fix: SVG dimensions measuring in test env

packages/react/src/safePolygon.ts
=> fix(safePolygon): measure bridge from smaller element

packages/react/src/components/FloatingPortal.tsx, packages/react/test/unit/FloatingPortal.test.tsx
=> fix(FloatingPortal): give `root` prop priority and allow refs

packages/dom/src/utils/getNearestOverflowAncestor.ts, packages/dom/src/utils/node.ts
Fixes https://github.com/floating-ui/floating-ui/issues/2317
=> fix(dom): loop when `Node` is mocked

website/pages/docs/dialog.mdx
=> Update broken dialog link

packages/dom/src/autoUpdate.ts
@npearson72 can you let me know if this change also fixes the issue, it's less hackish
Fixes #1740
=> fix(autoUpdate): prevent ResizeObserver loop with size

packages/dom/src/platform/isElement.ts, packages/dom/src/utils/is.ts, packages/react/src/utils/is.ts
=> fix: add check for own instance in `is*` guard functions

packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/types.ts, packages/react/test/unit/FloatingFocusManager.test.tsx
=> feat(FloatingFocusManager): `disabled` prop

packages/react/index.test-d.tsx, packages/react/src/hooks/useFloating.ts, packages/react/src/types.ts
=> fix(react): type/runtime error for virtual element passed to `elements.reference`

package-lock.json, packages/react/package.json, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/hooks/useDismiss.ts, packages/react/src/utils/markOthers.ts, packages/react/test/unit/FloatingFocusManager.test.tsx, packages/react/test/unit/useDismiss.test.tsx
=> fix(useDismiss): check for third-party elements on outside press

.config/rename.sh, package.json, packages/core/package.json, packages/dom/package.json, packages/react-dom/package.json, packages/react/package.json, packages/utils/package.json, packages/vue/package.json
=> fix(build): resolve non-module ts types

packages/react/src/components/FloatingOverlay.tsx
=> fix(FloatingOverlay): multiple lockScrolls with delayed unmount

package-lock.json, package.json, packages/core/package.json, packages/dom/package.json, packages/react-dom/package.json, packages/react-native/package.json, packages/react/package.json, packages/utils/package.json, packages/vue/package.json, website/package.json
Will add the CI step after manually trying it out first.
=> chore: use changesets

packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/hooks/useListNavigation.ts, packages/react/src/utils/getChildren.ts, packages/react/test/visual/components/MenuVirtual.tsx, packages/react/test/visual/index.tsx
=> feat(useListNavigation): nested virtual navigation

.changeset/chilly-lies-eat.md, packages/core/src/middleware/arrow.ts, packages/core/src/types.ts
Fixes https://github.com/floating-ui/floating-ui/issues/2549
=> fix(arrow): perform a reset if internal shifting is performed

package-lock.json, package.json, playwright.config.ts
Functional tests have been more flaky lately, hoping this helps
=> chore: upgrade Vite and Playwright

.changeset/neat-bees-tan.md, packages/react/src/components/Composite.tsx, packages/react/test/unit/Composite.test.tsx
=> feat(Composite): controlled mode

.changeset/smooth-hornets-end.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/components/FloatingPortal.tsx, packages/react/src/hooks/useClick.ts, packages/react/src/hooks/useDismiss.ts, packages/react/src/hooks/useFloating.ts, packages/react/src/hooks/useFocus.ts, packages/react/src/hooks/useHover.ts, packages/react/src/hooks/useListNavigation.ts, packages/react/src/types.ts, packages/react/test/unit/useClick.test.tsx, packages/react/test/unit/useDismiss.test.tsx, packages/react/test/unit/useFocus.test.tsx, packages/react/test/unit/useHover.test.tsx
=> feat(react): reason strings for `onOpenChange`

packages/react/src/components/FloatingFocusManager.tsx
https://github.com/floating-ui/floating-ui/pull/2613
=> fix(FloatingFocusManager): guard against body focus

.changeset/clean-ducks-tickle.md, packages/react-dom/src/arrow.ts
=> fix(react-dom): package type import

.changeset/fuzzy-swans-doubt.md, packages/core/src/detectOverflow.ts, packages/core/src/middleware/autoPlacement.ts, packages/core/src/middleware/hide.ts, packages/core/src/middleware/shift.ts, packages/core/src/middleware/size.ts, packages/core/src/types.ts
=> fix(types): avoid ts 4.2+ syntax

package.json
To ensure consistent formatting, explicitly specify options that change frequently based on preference.
=> chore: configure some prettier options

packages/react/test/unit/useDismiss.test.tsx
Add test cases to the following changes.
- #2597
=> test(useDismiss): add test cases for capture option

.changeset/wise-trainers-walk.md, packages/vue/package.json, packages/vue/src/utils/unwrapElement.ts, packages/vue/test/index.test.ts, pnpm-lock.yaml
=> Does not throw when component type reference or floating renders nothing

.changeset/few-horses-arrive.md, packages/utils/package.json, pnpm-lock.yaml
=> fix(utils): remove `react` peer dependency

.changeset/short-apes-stare.md, packages/devtools/package.json
=> chore(devtools): add license to package.json

.changeset/tasty-islands-sing.md, packages/react/src/utils.ts, packages/react/test/unit/useFocus.test.tsx
=> fix(react/utils): check if env is jsdom

.changeset/large-donuts-beam.md, packages/vue/src/utils/unwrapElement.ts
https://github.com/floating-ui/floating-ui/issues/2691#issuecomment-1893590794
=> fix(vue): change `isComponentPublicInstance` implementation

.changeset/slimy-comics-explain.md, packages/react-native/src/createPlatform.ts
=> fix(react-native): check for virtual elements

.changeset/stupid-scissors-wash.md, packages/react/src/components/FloatingPortal.tsx
=> fix(FloatingPortal): unconditional rendering with Suspense

.changeset/silent-lies-shop.md, packages/react/src/hooks/useId.ts
https://github.com/mui/material-ui/issues/41190#issuecomment-2036887985
=> fix(useId): make import impossible to statically analyze

.changeset/friendly-boxes-refuse.md, packages/core/src/detectOverflow.ts, packages/dom/src/platform/getElementRects.ts, packages/utils/src/index.ts
=> fix: avoid rect spreads

.changeset/five-fans-jam.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/hooks/useClick.ts, packages/react/src/hooks/useClientPoint.ts, packages/react/src/hooks/useDismiss.ts, packages/react/src/hooks/useFloating.ts, packages/react/src/hooks/useFocus.ts, packages/react/src/hooks/useHover.ts, packages/react/src/hooks/useInteractions.ts, packages/react/src/hooks/useListNavigation.ts, packages/react/src/hooks/useRole.ts, packages/react/src/hooks/useTransition.ts, packages/react/src/hooks/useTypeahead.ts, packages/react/src/safePolygon.ts, packages/react/src/types.ts
=> fix(types): simplify React types

.changeset/clever-windows-shave.md, packages/react/src/components/FloatingFocusManager.tsx
=> fix(FloatingFocusManager): return focus to reference when applicable even if not focused on open

.changeset/neat-pets-mate.md, packages/react-dom/src/index.ts, packages/react-dom/src/reactiveMiddleware.ts, packages/react-native/src/arrow.ts, packages/react-native/src/index.ts, packages/react-native/src/reactiveMiddleware.ts, packages/react-native/src/types.ts
=> feat: reactive middleware for React

.changeset/six-clouds-glow.md, packages/react/src/components/FloatingDelayGroup.tsx
=> fix(FloatingDelayGroup): prevent hydration error with Suspense

.changeset/pretty-fireants-applaud.md, packages/react/src/components/FloatingArrow.tsx
=> fix(FloatingArrow): allow close transitions to play floating element when grouped in instant phase

.changeset/thirty-dolls-bow.md, packages/react/src/hooks/useListNavigation.ts
=> fix(useListNavigation): avoid reading ref in render

.changeset/wicked-bears-press.md, packages/utils/src/dom.ts
=> fix(getFrameElement): check if `win.parent` is null

.changeset/angry-maps-deliver.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/components/FloatingPortal.tsx, packages/react/src/types.ts
Closes https://github.com/floating-ui/floating-ui/discussions/3012#discussion-7075849
=> feat(react): reason string for `closeOnFocusOut` handling

.changeset/flat-pianos-cough.md, packages/react-dom/src/useFloating.ts
https://github.com/floating-ui/floating-ui/issues/3017#issuecomment-2330517330
=> fix(useFloating): avoid setting `isPositioned` to true when `open` is false

.changeset/dull-bugs-rescue.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/components/FloatingPortal.tsx, packages/react/src/utils/tabbable.ts, packages/react/test/unit/FloatingFocusManager.test.tsx
=> fix(FloatingFocusManager): use fallback return focus element

.changeset/beige-mails-camp.md, packages/react/src/hooks/useListNavigation.ts, packages/react/test/unit/useListNavigation.test.tsx
=> fix(useListNavigation): handle virtual nested Home/End key press

.changeset/metal-dragons-shave.md, packages/react/src/components/FloatingDelayGroup.tsx
=> feat(useDelayGroup): add `enabled` option

.changeset/odd-paws-cheer.md, packages/react/src/hooks/useListNavigation.ts, packages/react/test/unit/useListNavigation.test.tsx
=> fix(useListNavigation): ignore Home/End key press for typeable combobox references

.changeset/red-plants-itch.md, packages/react/src/hooks/useListNavigation.ts, packages/react/test/unit/useListNavigation.test.tsx, packages/react/test/visual/components/MenuVirtual.tsx
=> fix(useListNavigation): ensure submenu references are set as `virtualItemRef` on floating close

.changeset/wet-bottles-sing.md, packages/react/src/components/Composite.tsx, packages/react/src/hooks/useListNavigation.ts, packages/react/src/utils/composite.ts, packages/react/test/unit/useListNavigation.test.tsx, packages/react/test/visual/components/ComplexGrid.tsx
=> fix(useListNavigation): incorrect behaviour with RTL grid

.changeset/fluffy-wombats-fry.md, packages/react/src/components/Composite.tsx, packages/react/test/unit/Composite.test.tsx, website/pages/docs/Composite.mdx
=> feat(Composite): add RTL support

.github/workflows/release-floating-ui.yml
* we tend to use the conventional commit style for commits and PRs. therefore, i added the commit and title fields in changesets/actions to follow the conventional commit rules.
=> chore(.github/workflows/release-floating-ui.yml): add fields(commit, title) in changesets/action

.changeset/plenty-pets-call.md, .changeset/pretty-pots-deny.md, packages/react-dom/package.json, packages/react-native/package.json, packages/react/package.json
=> chore(react): drop React 16 support, support React 19 RC

.changeset/tiny-kiwis-hide.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/test/unit/FloatingFocusManager.test.tsx
=> fix(FloatingFocusManager): check for 'safe-polygon' reason on return focus

.changeset/chatty-kangaroos-cover.md, packages/dom/src/autoUpdate.ts, packages/dom/src/utils/rectsAreEqual.ts
=> fix(autoUpdate): work around bug where intersection ratio is 1 but element actually moved

packages/dom/test/functional/containing-block.test.ts, packages/dom/test/visual/spec/ContainingBlock.tsx
* Relate with https://github.com/floating-ui/floating-ui/pull/3177
* Apply missed prettier config in `dom`
=> style(dom): apply prettier config

.changeset/tiny-bags-brake.md, packages/react/src/hooks/useMergeRefs.ts, packages/react/test/unit/useMergeRefs.test.tsx
=> Support Ref Cleanup in useMergeRefs

.changeset/orange-rings-remember.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/src/components/FloatingPortal.tsx, packages/react/src/utils/tabbable.ts, packages/react/test/unit/FloatingFocusManager.test.tsx
=> fix(FloatingFocusManager): correct tabbing to different document contexts

.changeset/pretty-cats-stare.md, .changeset/tough-geese-guess.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/test/unit/FloatingFocusManager.test.tsx
ref: https://github.com/mui/base-ui/issues/1679
=> fix(FloatingFocusManager): ignore manual `tabindex` handling for listbox roles

.changeset/clean-weeks-relate.md, packages/react/src/components/FloatingFocusManager.tsx, packages/react/test/unit/FloatingFocusManager.test.tsx
=> perf(FloatingFocusManager): move manual tabindex handling on floating element to an event

.changeset/cold-geese-dress.md, packages/dom/src/utils/getRectRelativeToOffsetParent.ts
=> fix: correct position when document scrollbar is on left side with fixed strategy

.changeset/light-mails-greet.md, packages/react/src/components/FloatingFocusManager.tsx
https://github.com/mui/base-ui/pull/1665#issuecomment-2900619495
=> fix(FloatingFocusManager): always prevent scroll upon returning focus

config/src/defineViteConfig.mts
=> refactor(config/defineViteConfig): replace deprecated 'UserConfig' with 'ViteUserConfig'

.changeset/cold-spoons-fry.md, packages/utils/src/dom.ts, packages/utils/src/index.ts
A fix for a couple of small perf issues I noticed while browsing the code - mostly reducing memory allocations.
=> refactor(utils): performance improvements

.changeset/sour-numbers-press.md, packages/dom/src/platform/convertOffsetParentRelativeRectToViewportRelativeRect.ts, packages/dom/src/utils/getHTMLOffset.ts, packages/dom/src/utils/getViewportRect.ts
=> fix(getViewportRect): account for `scrollbar-gutter: stable` space
